### PR TITLE
[FIXED] subsz monitoring endpoint did not account for accounts.

### LINKED ISSUE #1371: Add missing metadata keys to monitoring port subsz JSON
Unlike the other `*z` (e.g., `connz` and `varz`), `subsz` is missing the `server_id` key.

It is also missing `now`.

There are probably other metadata fields that could be added, but these are the notable omissions.

Here is a recent `subsz` payload:

```
{
  "num_subscriptions": 0,
  "num_cache": 0,
  "num_inserts": 0,
  "num_removes": 0,
  "num_matches": 0,
  "cache_hit_rate": 0,
  "max_fanout": 0,
  "avg_fanout": 0
}
```

### PR DESCRIPTION
**Pull request by matthiashanel**
Fixes  #1371 and #1357 by adding up stats and collecting subscriptions
from all accounts.

I will add selecting individual accounts in a separate PR as this has to happen for more than one endpoint.

Signed-off-by: Matthias Hanel <mh@synadia.com>

### CODE REVIEW

File: server/monitor.go [hunk 1]
```diff
@@ -752,6 +752,8 @@ func (s *Server) HandleRoutez(w http.ResponseWriter, r *http.Request) {
 
 // Subsz represents detail information on current connections.
 type Subsz struct {
+	ID  string    `json:"server_id"`
```
Comment (derekcollison) [inline server/monitor.go:755]: Just FYI we need to add in server_name as well here for all of these. server_name survives if set, id is ephemeral.

File: server/monitor_test.go [hunk 2]
```diff
@@ -59,6 +59,18 @@ func runMonitorServer() *Server {
 	return RunServer(opts)
 }
 
+func runMonitorServerWithAccounts() *Server {
+	resetPreviousHTTPConnections()
+	opts := DefaultMonitorOptions()
+	aA := &Account{Name: "A"}
```
Comment (kozlovic) [inline server/monitor_test.go:65]: Would call `NewAccount("A")` here so that account is created with its default settings, etc.. Same for account B obviously.

File: server/monitor.go (hunk 1 above)
Comment (matthiashanel) [reply server/monitor.go:755]: Will add that when adding accounts options. Next on my list

File: server/monitor_test.go (hunk 2 above)
Comment (matthiashanel) [reply server/monitor_test.go]: fixed

File: server/monitor.go (hunk 1 above)
Comment (matthiashanel) [reply server/monitor.go:755]: Will add that in concert with another change

File: server/monitor.go [hunk 3]
```diff
@@ -752,6 +752,8 @@ func (s *Server) HandleRoutez(w http.ResponseWriter, r *http.Request) {
...
+	Now time.Time `json:"now"`
```
Comment (ripienaar) [inline server/monitor.go:756]: sorry a bit late to the party here - but as we use `timestamp` elsewhere for the typed events can we use the same here given its a new field?

Comment (derekcollison) [reply server/monitor.go:756]: Even though this is an addition, all of the other monitoring endpoints use `now` so I would prefer to keep that for consistency with the HTTP endpoints.

Comment (matthiashanel) [reply server/monitor.go:756]: @ripienaar I kept it the same way to be identical with the rest. If we expose the monitoring endpoints via nats, these are wrapped and the outer json will adhere to what we discussed.
