### PR TITLE
[FIXED] Sublist's cache hit rate would be wrong in presence of multiple accounts

### LINKED ISSUE #3590: Cache hit rate gt 1
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [ ] Included `nats-server -DV` output
 - [ ] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats-server` and affected client libraries used:
Version:  2.9.3

#### OS/Container environment:
nats:2.9.3-alpine3.16

#### Steps or code to reproduce the issue:
go to http://{{ ip }}:8222/subsz check cache_hit_rate value
#### Expected result:
cache_hit_rate <= 1.0
#### Actual result:
cache_hit_rate > 1.0

Screenshot_20221028_114330

### PR DESCRIPTION
**Pull request by aopetrov86**
- [x] Link to issue, e.g. `Resolves #NNN`
 - [ ] Documentation added (if applicable)
 - [x] Tests added
 - [ ] Branch rebased on top of current main (`git pull --rebase origin main`)
 - [ ] Changes squashed to a single commit (described [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
 - [x] Build is green in Travis CI
 - [x] You have certified that the contribution is your original work and that you license the work to the project under the [Apache 2 license](https://github.com/nats-io/nats-server/blob/main/LICENSE)

Resolves #3590

/cc @nats-io/core

### CODE REVIEW

File: server/sublist.go [hunk 1]
```diff
@@ -963,8 +967,9 @@ func (s *Sublist) Stats() *SublistStats {
 
 	st.NumCache = uint32(cc)
 	st.NumMatches = atomic.LoadUint64(&s.matches)
+	st.cacheHits = atomic.LoadUint64(&s.cacheHits)
 	if st.NumMatches > 0 {
-		st.CacheHitRate = float64(atomic.LoadUint64(&s.cacheHits)) / float64(st.NumMatches)
+		st.CacheHitRate = float64(st.cacheHits) / float64(st.NumMatches)
```
Comment (kozlovic) [inline server/sublist.go:972]: I would ask that you add the following test that demonstrate the issue (and verifies that your fix work) in `sublist_test.go` (say before the line `// -- Benchmarks Setup --`):
```
func TestSublistAddCacheHitRate(t *testing.T) {
	sl1 := NewSublistWithCache()
	fooSub := newSub("foo")
	sl1.Insert(fooSub)
	for i := 0; i < 4; i++ {
		sl1.Match("foo")
	}
	stats1 := sl1.Stats()
	require_True(t, stats1.CacheHitRate == 0.75)

	sl2 := NewSublistWithCache()
	barSub := newSub("bar")
	sl2.Insert(barSub)
	for i := 0; i < 4; i++ {
		sl2.Match("bar")
	}
	stats2 := sl2.Stats()
	require_True(t, stats2.CacheHitRate == 0.75)

	ts := &SublistStats{}
	ts.add(stats1)
	ts.add(stats2)
	require_True(t, ts.CacheHitRate == 0.75)
}
```

**Review by kozlovic — CHANGES_REQUESTED** [review]

File: server/sublist.go (hunk 1 above)
Comment (aopetrov86) [reply server/sublist.go:972]: Done

**Review by kozlovic — APPROVED** [review]
LGTM. Thank you for the report and contribution!
