### PR TITLE
Fix new replicas late MaxAge expiry

### LINKED ISSUE #3848: After changing the replica of a stream: The non-leaders have more messages
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included `nats-server -DV` output
```
[124] 2023/02/06 08:14:04.050458 [INF] Starting nats-server
[124] 2023/02/06 08:14:04.050483 [INF]   Version:  2.9.11
[124] 2023/02/06 08:14:04.050485 [INF]   Git:      [23ffc16]
[124] 2023/02/06 08:14:04.050491 [DBG]   Go build: go1.19.4
[124] 2023/02/06 08:14:04.050496 [INF]   Name:     NBS3DHEIAJA2NGY2ZQ6IL2MK4YLIDGIZNF3IKORWUNMVAQEJOGJHY3EZ
[124] 2023/02/06 08:14:04.050498 [INF]   ID:       NBS3DHEIAJA2NGY2ZQ6IL2MK4YLIDGIZNF3IKORWUNMVAQEJOGJHY3EZ
```
 - [x] Included a Minimal, Complete, and Verifiable example: Please see section _"Steps or code to reproduce the issue"_

#### Versions of `nats-server` and affected client libraries used:

Reproducible in different versions and setups.

#### OS/Container environment:

Reproducible for various operating systems and environments (k8s, locally mac, locally linux, …).

#### Steps or code to reproduce the issue:

<details>
  <summary><code>docker-compose.yml</code></summary>

  ```yml
  version: '3'
  services:
    nats-1:
      container_name: nats-1
      image: nats:2.9.11
      entrypoint: /nats-server
      command: --name nats-1 --cluster_name NATS --js --sd /data --cluster nats://0.0.0.0:4245 --routes nats://nats-1:4245,nats://nats-2:4245,nats://nats-3:4245 -p 4222 --http_port 8222
      networks:
        - nats
      ports:
        - 14222:4222
        - 18222:8222
  
    nats-2:
      container_name: nats-2
      image: nats:2.9.11
      entrypoint: /nats-server
      command: --name nats-2 --cluster_name NATS --js --sd /data --cluster nats://0.0.0.0:4245 --routes nats://nats-1:4245,nats://nats-2:4245,nats://nats-3:4245 -p 4222 --http_port 8222
      networks:
        - nats
      ports:
        - 24222:4222
        - 28222:8222
  
    nats-3:
      container_name: nats-3
      image: nats:2.9.11
      entrypoint: /nats-server
      command: --name nats-3 --cluster_name NATS --js --sd /data --cluster nats://0.0.0.0:4245 --routes nats://nats-1:4245,nats://nats-2:4245,nats://nats-3:4245 -p 4222 --http_port 8222
      networks:
        - nats
      ports:
        - 34222:4222
        - 38222:8222
  
    nats-setup:
      container_name: nats_setup
      depends_on:
        - nats-1
        - nats-2
        - nats-3
      build:
        context: .
      environment:
        - NATS_URL=nats://host.docker.internal:14222
      networks:
        - nats
  
  networks:
    nats: {}
  ```
</details>

<details>
  <summary><code>Dockerfile</code></summary>

  ```yml
  FROM alpine:3.17
  
  RUN apk add --no-cache wget rclone curl jq && \
      wget -P ~ https://github.com/nats-io/natscli/releases/download/v0.0.35/nats-0.0.35-linux-arm64.zip && \
      unzip -d ~ ~/nats-0.0.35-linux-arm64.zip && \
      cp ~/nats-0.0.35-linux-arm64/nats /usr/local/bin && \
      adduser -D user
  
  WORKDIR /workdir
  
  COPY stream.conf .
  COPY script.sh .
  RUN chmod +x script.sh
  
  USER user
  
  ENTRYPOINT ["/workdir/script.sh"]
  ```
</details>

<details>
  <summary><code>script.sh</code></summary>

  ```sh
  #!/bin/sh
  
  function fetch_stream_information() {
    N1=$(curl --silent "http://nats-1:8222/jsz?consumers=1" | jq ".messages")
    N2=$(curl --silent "http://nats-2:8222/jsz?consumers=1" | jq ".messages")
    N3=$(curl --silent "http://nats-3:8222/jsz?consumers=1" | jq ".messages")
  
    echo "=================="
    echo "nats-1: $N1"
    echo "nats-2: $N2"
    echo "nats-3: $N3"
    echo "=================="
  }
  
  nats stream ls
  nats stream create --config=stream.conf
  nats stream info test
  
  nats pub test.a --count 10 "Message {{Count}} @ {{Time}}"
  sleep 1
  nats pub test.a --count 10 "Message {{Count}} @ {{Time}}"
  sleep 1
  nats pub test.a --count 10 "Message {{Count}} @ {{Time}}"
  sleep 1
  nats pub test.a --count 10 "Message {{Count}} @ {{Time}}"
  sleep 1
  nats pub test.a --count 10 "Message {{Count}} @ {{Time}}"
  sleep 1
  
  fetch_stream_information
  
  nats stream edit --replicas=3 --force test
  
  sleep 2
  fetch_stream_information
  sleep 2
  fetch_stream_information
  sleep 2
  fetch_stream_information
  
  nats pub test.a --count 4 "Message {{Count}} @ {{Time}}"
  
  sleep 1
  fetch_stream_information
  sleep 1
  fetch_stream_information
  sleep 1
  fetch_stream_information
  sleep 1
  fetch_stream_information
  sleep 1
  fetch_stream_information
  ```
</details>

<details>
  <summary><code>stream.conf</code></summary>

  ```json
  {
    "config":{
      "name":"test",
      "subjects":[
        "test.*"
      ],
      "retention":"limits",
      "max_consumers":-1,
      "max_msgs":100,
      "max_bytes":-1,
      "max_age":10000000000,
      "max_msg_size":-1,
      "storage":"file",
      "discard":"old",
      "num_replicas":1,
      "duplicate_window":5000000000,
      "deny_delete":false,
      "deny_purge":false,
      "allow_rollup_hdrs":true
    },
    "created":"2021-02-27T23:49:36.700424Z",
    "state":{
      "messages":0,
      "bytes":0,
      "first_seq":0,
      "first_ts":"0001-01-01T00:00:00Z",
      "last_seq":0,
      "last_ts":"0001-01-01T00:00:00Z",
      "consumer_count":0
    }
  }
  ```
</details>

1. download all files
2. run `docker compose up --build --force-recreate --remove-orphans --renew-anon-volumes`
3. observe logs

Short explanation what this scenario does:

1. Creation of a stream with `replica: 1` and a time based retention
2. Publish 50 messages
3. Change stream configuration to `replica: 3`
4. Wait
5. Publish 4 messages
6. ⚠️ The replicas have more messages than the leader

#### Expected result:

After changing the replica size of a stream and the first retention of a message the messages on all replicas are the same.

#### Actual result:

After changing the replica size of a stream and the first retention of a message the messages on the leader are the correct ones, but the replicas have old messages.

**Thanks in advance! 🙏** 

Cheers
Stefan

### PR DESCRIPTION
**Pull request by Jarema**
Signed-off-by: Tomasz Pietrek <tomasz@nats.io>

This fixes issue when scaling Stream with MaxAge and some older
messages stored. Until this commit, old messages were not properly
expired on new replicas, because new replicas first expiry timer
was set to MaxAge duration.
This commit adds check if received messages expiry happens before
MaxAge, meaning they're messages older than the replica.

Resolves #3848 

/cc @nats-io/core

### CODE REVIEW

File: server/filestore.go [hunk 1]
```diff
@@ -2004,6 +2005,24 @@ func (fs *fileStore) storeRawMsg(subj string, hdr, msg []byte, seq uint64, ts in
 		fs.startAgeChk()
 	}
 
+	// In case this is a replica newer than the original one,
+	// wee need to consider that messages should be expired
```
Comment (derekcollison) [inline server/filestore.go:2009]: we vs wee

File: server/filestore.go [hunk 2]
```diff
@@ -2004,6 +2005,24 @@ func (fs *fileStore) storeRawMsg(subj string, hdr, msg []byte, seq uint64, ts in
...
+	// sooner than stream MaxAge value, as they might have
+	// older timestamps.
+	// This could be simpler, but we try to avoid calling time.Now() and other
+	// functions from time package, as this is a hot hpath.
```
Comment (derekcollison) [inline server/filestore.go:2013]: hotpath vs hpath

**Review by derekcollison — COMMENTED** [review]
Possible to just calculate first expiry time based on the first message vs holding more state?

**Comment by Jarema** [comment]
@derekcollison  fixed the typos.

We could.
Only concern would be adding per subject / per message ttl in the future, would make this approach necessary I think, as first message might not have the smallest ttl.

Is this something we consider?
If no - I will change to checking first message ttl.

File: server/memstore.go [hunk 3]
```diff
@@ -191,6 +192,25 @@ func (ms *memStore) storeRawMsg(subj string, hdr, msg []byte, seq uint64, ts int
...
+	// Especially that it should be called only once per scaling replicas.
+	if ms.cfg.MaxAge != 0 && ts > 0 && ts+int64(ms.cfg.MaxAge) < ms.ageChkTime {
+		now := time.Now().UnixNano()
+		// calculate duration when the next expireMsgs should be called.
+		fireIn := ts - (now - int64(ms.cfg.MaxAge))
+		// if previous age check was meant to happen later than the new one,
+		// update it.
+		if int64(ms.ageChkTime) >= fireIn+now {
+			ms.ageChkTime = now + fireIn
+			ms.ageChk = time.AfterFunc(time.Duration(fireIn), ms.expireMsgs)
```
Comment (wallyqs) [inline server/memstore.go:210]: any chance that ageChk is being set twice in this codepath (first in `startAgeChk`?) just checking whether is needed to call cancelAgeChk so that previous timer does not fire

**Comment by derekcollison** [comment]
Not for now, so checking first msg will work for now.

File: server/memstore.go (hunk 3 above)
Comment (Jarema) [reply server/memstore.go:210]: It doesn't matter - as if not, it was initialized previously.
Switched to calling `ms.resetAgeChk`.

Could inline the if condition from reset, but as if we're here, it happens really rarely, I would prefer simplicity.

good catch, thx!

**Comment by Jarema** [comment]
@derekcollison This is what you meant?
Checking if this message is the first sequence is enough for this case? (first dive into filestore, hence the question).

**Review by derekcollison — COMMENTED** [review]
I think all you have to do is when you realize you are a new replica is make sure you run expireMsgs once.

I can try to assist once I am in a spot to work a bit better.

**Comment by Jarema** [comment]
No worries, grokking that part of the code is a good experience.
I switched to adding a new bool state marking if we ever received a message on a given replica.

Based on that little state, it's easy to check if that's the first message for a new replica, so it fires only once to calculate when to fire expiryMsgs.

Based only on sequences and the number of messages it would trigger whenever stream was emptied for whatever reason.

**Review by derekcollison — COMMENTED** [review]
The replicated messages use StoreRawMsg vs StoreMsg.

If we are receiving a message there we could check for a condition, say 0 msgs before this insertion, and cfg.MaxAge and ts is > 0 and < now + MaxAge then just call expireMsgs() since that already does the calculations etc.

**Comment by Jarema** [comment]
@derekcollison we discussed trying to not introduce new state, but we can't rely on `len(state.Msgs)` as it would trigger whenever stream reaches 0, which can happen often, nor on `state.FirstSeq` if stream was scaled up after purge.

This new `received` boolean makes logic very simple and non-error-prone.
Unless I' missing something obvious ;).

File: server/filestore.go [hunk 4]
```diff
@@ -104,26 +104,27 @@ type psi struct {
...
+	blks     []*msgBlock
+	bim      map[uint32]*msgBlock
+	psim     map[string]*psi
+	hh       hash.Hash64
+	qch      chan struct{}
+	cfs      []ConsumerStore
+	sips     int
+	closed   bool
+	fip      bool
+	received bool
```
Comment (derekcollison) [inline server/filestore.go:127]: Let's call it receivedAny or receivedFirst for clarity.

**Review by derekcollison — COMMENTED** [review]
This looks good, wondering if we could just change name for clarity of bool.

File: server/filestore.go (hunk 4 above)
Comment (Jarema) [reply server/filestore.go]: agree. changed to `receivedAny`

**Review by derekcollison — APPROVED** [review]
LGTM!
