### PR TITLE
[FIXED] Early closed connection may linger in the server

### LINKED ISSUE #1384: Closed connection can linger in server
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [X] Included `nats-server -DV` output
 - [X] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats-server` and affected client libraries used:
Latest server 2.1.6, any client

#### OS/Container environment:
N/A

#### Steps or code to reproduce the issue:
Run the server and have an application create the TCP connection to the server but have the process exit before it has a chance to complete the connect protocol process

#### Expected result:
Monitoring should not show this connection.

#### Actual result:
Monitoring shows a connection with pending bytes, no lang/version, no rtt, etc..
```
"connections": [
    {
      "cid": 1,
      "ip": "::1",
      "port": 50841,
      "start": "2020-05-08T10:42:46.816593-06:00",
      "last_activity": "2020-05-08T10:42:46.816593-06:00",
      "uptime": "2s",
      "idle": "2s",
      "pending_bytes": 280,
      "in_msgs": 0,
      "out_msgs": 0,
      "in_bytes": 0,
      "out_bytes": 0,
      "subscriptions": 0
    }
  ]
```

### PR DESCRIPTION
**Pull request by kozlovic**
If the connection is marked as closed while sending the INFO, the
connection would not be removed from the internal map, which would
cause it to be shown in the monitoring list of opened connections.

Resolves #1384

Signed-off-by: Ivan Kozlovic <ivan@synadia.com>

### CODE REVIEW

File: server/server.go [hunk 1]
```diff
@@ -1793,6 +1793,13 @@ func (s *Server) createClient(conn net.Conn) *client {
 	// The connection may have been closed
 	if c.isClosed() {
 		c.mu.Unlock()
+		// If it was for TLS timeout, the connection has been properly
+		// teardown. However, if no TLS, it could be because the send
```
Comment (derekcollison) [inline server/server.go:1797]: torn down?
