### PR TITLE
Fix config reload when no changes for leafnode remotes

### LINKED ISSUE #1509: Config reload fails if leafnode remotes are defined
#### Versions of `nats-server` and affected client libraries used:

2.2.0-beta.19

#### Steps or code to reproduce the issue:

```hcl
port: 4222
http: 8222

cluster {
  port: 6222
  routes: []
}

leafnodes {
  remotes: [
    {
      url: "nats://foo:bar@localhost:7422"
    }
  ]
}
```

#### Expected result:

No op config reload

#### Actual result:

```
[57372] 2020/07/09 10:20:16.654872 [ERR] Failed to reload server configuration: config reload not supported for LeafNode: old={ 0    [] 0 <nil> 0 false  false 1s [0xc0000ca240] <nil> 0 0}, new={ 0    [] 0 <nil> 0 false  false 1s [0xc000302090] <nil> 0 0}
```

### PR DESCRIPTION
**Pull request by wallyqs**
- [x] Tests added
 - [X] Branch rebased on top of current master (`git pull --rebase origin master`)
 - [x] Changes squashed to a single commit (described [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
 - [x] Build is green in Travis CI
 - [X] You have certified that the contribution is your original work and that you license the work to the project under the [Apache 2 license](https://github.com/nats-io/gnatsd/blob/master/LICENSE)

Resolves #1509 

/cc @nats-io/core

Signed-off-by: Waldemar Quevedo <wally@synadia.com>

### CODE REVIEW

File: server/reload.go [hunk 1]
```diff
@@ -909,6 +909,45 @@ func (s *Server) diffOptions(newOpts *Options) ([]option, error) {
...
+				if len(tmpOld.Remotes) != len(tmpNew.Remotes) {
+					return true
+				}
+
+				// Check whether all remotes URLs are still the same.
+				for _, oldRemote := range tmpOld.Remotes {
+					var found bool
+
+					for _, newRemote := range tmpNew.Remotes {
+						fmt.Println("newRemote:::", newRemote.LocalAccount)
```
Comment (kozlovic) [inline server/reload.go:924]: debug left over?

Comment (wallyqs) [reply server/reload.go]: Thanks, ok removed the Println
