### PR TITLE
Large number of ephemeral consumers could exhaust Go runtime's max OS threads.

### LINKED ISSUE #2742: JetStream `Consumer assignment not cleaned up, retrying`, degraded cluster performance
## Defect

When using a lot of ephemeral consumers, a cluster with significant load eventually starts spamming a sample like below:

```
[1] 2021/12/13 02:44:15.208575 [WRN] Consumer assignment not cleaned up, retrying
[1] 2021/12/13 02:44:15.230045 [WRN] Consumer assignment not cleaned up, retrying
[1] 2021/12/13 02:44:15.241153 [INF] JetStream cluster new consumer leader for 'XXXX > YYYY > ZZZZ'
[1] 2021/12/13 02:44:15.289728 [WRN] Consumer assignment not cleaned up, retrying
[1] 2021/12/13 02:44:15.289972 [WRN] Consumer assignment not cleaned up, retrying
[1] 2021/12/13 02:44:15.300970 [WRN] Consumer assignment not cleaned up, retrying
[1] 2021/12/13 02:44:15.308939 [INF] JetStream cluster new consumer leader for 'XXXX > YYYY > ZZZZ'
[1] 2021/12/13 02:44:15.321413 [WRN] Consumer assignment not cleaned up, retrying
[1] 2021/12/13 02:44:15.359668 [WRN] Consumer assignment not cleaned up, retrying
```

I'm unsure if the leader migration for ephemeral consumers is normal even if none of the servers have rebooted.

`nats str info` of an affected stream:

```
Information for Stream XXXX created 2021-12-10T15:32:39Z

Configuration:

             Subjects: XXXX.>
     Acknowledgements: true
            Retention: File - Limits
             Replicas: 3
       Discard Policy: Old
     Duplicate Window: 2m0s
     Maximum Messages: unlimited
        Maximum Bytes: unlimited
          Maximum Age: 0.00s
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited


Cluster Information:

                 Name: XXXX
               Leader: prod-nats-js-2
              Replica: prod-nats-js-0, current, seen 0.36s ago
              Replica: prod-nats-js-1, current, seen 0.36s ago

State:

             Messages: 308,916
                Bytes: 63 MiB
             FirstSeq: 37,439 @ 2021-12-11T03:57:36 UTC
              LastSeq: 346,354 @ 2021-12-13T03:23:29 UTC
     Active Consumers: 57
```

`nats con info` of an affected ephemeral consumer:

```
Information for Consumer XXXX > 07ix4IRz created 2021-12-13T03:24:25Z

Configuration:

    Delivery Subject: XXXX.deliver.ephemeral.XXXX-34af714a-aa41-4434-8189-a70c80d85af4.01605c32-a7d7-452d-9287-db2b3aa85924
      Filter Subject: XXXX.34af714a-aa41-4434-8189-a70c80d85af4
      Deliver Policy: All
          Ack Policy: None
       Replay Policy: Instant
        Flow Control: false

Cluster Information:

                Name: XXXX
              Leader: XXXX
State:

   Last Delivered Message: Consumer sequence: 0 Stream sequence: 347268
     Unprocessed Messages: 0
          Active Interest: Active
````

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [ ] Included `nats-server -DV` output (can't reproduce in staging)
 - [ ] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats-server` and affected client libraries used:

Server: Docker `nats:2.6.6`

#### OS/Container environment:

docker-compose
Ubuntu 20.04

#### Steps or code to reproduce the issue:

1. Start a 3-node JetStream-enabled cluster
2. Create a stream with replication set to 3
3. Create a large amount of ephemeral consumers, many of which never have any messages delivered

#### Expected result:

Server CPU should remain low. Should not see warnings in console. Ephemeral consumers should be removed and not migrated.

#### Actual result:

CPU load steadily increases. CPU sits at effectively 0% until a steady stream of messages (~70 mps) are sent through the cluster. The two screenshots below are of the same 6-hour window.

image

image

### PR DESCRIPTION
**Pull request by derekcollison**
Under certain situations large number of consumers that are racing to update state or delete their stores during a delete
would start taking up OS threads due to blocking disk IO. When this happened and their were a bunch of Go routines becoming runnable the Go runtime would create extra OS threads to fill in the runnable pool and would exhaust the max thread setting. Even if it did not exhaust it you could see a quick run up in memory and unstable systems.

This code places a channel as a simple semaphore to limit the number of disk IO blocking OS threads.

Signed-off-by: Derek Collison <derek@nats.io>

Resolves #2742 

/cc @nats-io/core

### CODE REVIEW

File: server/consumer.go [hunk 1]
```diff
@@ -1055,15 +1056,19 @@ func (o *consumer) deleteNotActive() {
...
 					ca := js.consumerAssignment(acc, stream, name)
 					js.mu.RUnlock()
-					if ca != nil {
-						s.Warnf("Consumer assignment not cleaned up, retrying")
-						meta.ForwardProposal(removeEntry)
+					if ca != nil && fs {
+						if fs {
+							s.Warnf("Consumer assignment not cleaned up, retrying")
+							meta.ForwardProposal(removeEntry)
+						}
```
Comment (ripienaar) [inline server/consumer.go:1070]: the if on 1066 already checks if `fs` is true, then 1067 again checks if `fs` is true and 1071 in a block where `fs` is always `true` sets it to `true`

File: server/filestore.go [hunk 2]
```diff
@@ -5129,6 +5130,26 @@ func (o *consumerFileStore) encryptState(buf []byte) []byte {
...
+// Used to limit number of disk IO calls in flight since they could all be blocking an OS thread.
+// https://github.com/nats-io/nats-server/issues/2742
+var dios chan struct{}
+
+// Used to setup our simplistic counting semaphore using buffered channels.
+// golang.org's semaphore seemed a bit heavy.
+func init() {
+	// Minimum for blocking disk IO calls.
+	const minNIO = 4
+	nIO := runtime.GOMAXPROCS(0)
```
Comment (ripienaar) [inline server/filestore.go:5142]: I think we recommend a value of around 4 for this dont we? Is that really enough under heavy load? 

I am not sure how the raft layer behaves exactly but this will presumably not slow down handling of the general keep alive of raft membership right? But could slow down significantly committing data there I presume. Would that increase leader elections under very stressed situations?

File: server/consumer.go (hunk 1 above)
Comment (derekcollison) [reply server/consumer.go:1070]: Yea that one got messed up after several revisions, will fix.

Comment (derekcollison) [reply server/consumer.go]: ok fixed.

File: server/filestore.go (hunk 2 above)
Comment (derekcollison) [reply server/filestore.go:5142]: This is usually set to num cores/cpus, so on my machine its 20 (hyper-threads), but on smaller machines we can use up to 4 instead of setting to 1 or 2. I played with increasing this in some tests but makes no difference since the machine can only be really doing N things in parallel.

This is only effecting the consumer stores, not stream stores which is what is used for nrg/raft layer.

Under a loaded test I had yesterday, performance was much better when lots of ephemeral consumers were trying to do those things all at the same time, and of course the crazy number of threads took its toll on the OS. Did both darwin and linux, so feel pretty good after spending yesterday on it perf wise.

Comment (ripienaar) [reply server/filestore.go:5142]: Yes, I know defaults but we often say nats server works best on 4ish cores and recommend setting this to 4, was thinking about that

**Review by ripienaar — APPROVED** [review]
LGTM

File: server/consumer.go (hunk 1 above)
Comment (derekcollison) [reply server/consumer.go:1070]: Actually redid this again, sorry. I had it mostly right before. Please take one more look, apologies.

**Review by ripienaar — APPROVED** [review]
LGTM
