### PR TITLE
Check for overlapping subjects on stream update.

### LINKED ISSUE #2144: stream subjects overlap is not checked on stream edit/update
Streams are not allowed to listen to the same subjects as other streams. When trying to add a stream that listens to the same subjects of an existing stream the error `subjects overlap with an existing stream` is produced.

This check does not occur when editing a streams subject.

To reproduce:

Add a stream that listens to a subject.
Add a second stream that listens to a different subject.
Edit the second stream to listen to the same subject as the first stream.

This is confirmed to be the case using nats.go UpdateStream() as well ass the natscli nats stream edit.

### PR DESCRIPTION
**Pull request by derekcollison**
Resolves #2144 

Signed-off-by: Derek Collison <derek@nats.io>

/cc @nats-io/core

### CODE REVIEW

File: server/jetstream_cluster.go [hunk 1]
```diff
@@ -3466,6 +3466,22 @@ func (s *Server) jsClusteredStreamUpdateRequest(ci *ClientInfo, acc *Account, su
 		return
 	}
 
+	// Check for subject collisions here.
+	for _, sa := range cc.streams[acc.Name] {
+		if sa == osa {
```
Comment (kozlovic) [inline server/jetstream_cluster.go:3471]: This same loop (without this check) exists in jsClusteredStreamRequest(). Could have been made a little function, although this check is specific to jsClusteredStreamUpdateRequest() I presume.

**Review by kozlovic — APPROVED** [review]
LGTM

File: server/jetstream_cluster.go (hunk 1 above)
Comment (derekcollison) [reply server/jetstream_cluster.go:3471]: Agree, we could make a function but this one does need to skip the original assignment unlike create.
