### PR TITLE
Fix crasher on callout for a leafnode connection with hand-rolled creds that are mistmatched

### LINKED ISSUE #7841: Nats Server Crash when mismatched JWT/Seed is used in decentralized auth callout
### Observed behavior

We ran into a scenario where we mixed up the seed (private) key for two different leaf nodes.  During the connection, the nats-server crashed in the auth_callout.go module.  This is BEFORE auth callout is being called.

This is a severe issue because essentially a bad actor is able to take down the cluster.

```
[1] 2026/02/14 15:19:37.699420 [INF] 10.0.5.234:44178 - lid:601 - Leafnode connection closed: Client Closed
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7c4b02]

goroutine 1790 [running]:
github.com/nats-io/nats-server/v2/server.(*Account).subscribeInternalEx(0x0, {0xc002da6900, 0x1d}, 0xc002c301c0, 0x0)
	github.com/nats-io/nats-server/v2/server/accounts.go:2124 +0x42
github.com/nats-io/nats-server/v2/server.(*Account).subscribeInternal(...)
	github.com/nats-io/nats-server/v2/server/accounts.go:2108
github.com/nats-io/nats-server/v2/server.(*Server).processClientOrLeafCallout(0xc0001a6008, 0xc00260e008, 0xc000144008)
	github.com/nats-io/nats-server/v2/server/auth_callout.go:311 +0x5fe
github.com/nats-io/nats-server/v2/server.(*Server).processClientOrLeafAuthentication.func1()
	github.com/nats-io/nats-server/v2/server/auth.go:659 +0x259
github.com/nats-io/nats-server/v2/server.(*Server).processClientOrLeafAuthentication(0xc0001a6008, 0xc00260e008, 0xc000144008)
	github.com/nats-io/nats-server/v2/server/auth.go:986 +0x15a5
github.com/nats-io/nats-server/v2/server.(*Server).isClientAuthorized(0xc0001a6008, 0xc00260e008)
	github.com/nats-io/nats-server/v2/server/auth.go:389 +0x74
github.com/nats-io/nats-server/v2/server.(*Server).isLeafNodeAuthorized(0xc0001a6008, 0xc00260e008)
	github.com/nats-io/nats-server/v2/server/auth.go:1445 +0x2bd
github.com/nats-io/nats-server/v2/server.(*Server).checkAuthentication(0xc00260e260?, 0x457?)
	github.com/nats-io/nats-server/v2/server/auth.go:371 +0x59
github.com/nats-io/nats-server/v2/server.(*client).processConnect(0xc00260e008, {0xc00260e260, 0x457, 0x1000})
	github.com/nats-io/nats-server/v2/server/client.go:2172 +0x897
github.com/nats-io/nats-server/v2/server.(*client).parse(0xc00260e008, {0xc002972400, 0x261, 0x400})
	github.com/nats-io/nats-server/v2/server/parser.go:945 +0xbe5
github.com/nats-io/nats-server/v2/server.(*client).readLoop(0xc00260e008, {0x0, 0x0, 0x0})
	github.com/nats-io/nats-server/v2/server/client.go:1406 +0x1245
github.com/nats-io/nats-server/v2/server.(*Server).createLeafNode.func2()
	github.com/nats-io/nats-server/v2/server/leafnode.go:1200 +0x25
github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine.func1()
	github.com/nats-io/nats-server/v2/server/server.go:3879 +0x32
created by github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine in goroutine 1789
	github.com/nats-io/nats-server/v2/server/server.go:3877 +0x128
```

### Expected behavior

Nats-server should detect the mismatched credentials and reject gracefully without crashing.

### Server and client version

2.11.6 Client (leaf node) and Server

### Host environment

_No response_

### Steps to reproduce

3-node hub cluster in EC2 VMs.  Leaf node spokes

Decentralized Authentication Setup:
```
nsc add operator --generate-signing-key --sys --name local

# A follow-up edit of the operator enforces signing keys are used for
# accounts as well. Setting the server URL is a convenience so that
# it does not need to be specified with call `nsc push`.
nsc edit operator \
  --require-signing-keys \
  --account-jwt-server-url "$NATS_URL"

mkdir -p /etc/nats

# This command generates the bit of configuration to be used by the server
# to setup the embedded JWT resolver.
nsc generate config \
  --nats-resolver \
  --sys-account SYS > /etc/nats/resolver.conf

# Create the most basic config that simply includes the generated
# resolver config.
cat <<- EOF > /etc/nats/server.conf
server_name: hub
debug: true
trace: true
jetstream: {
  domain: hub
}
leafnodes {
  port: 7422
}
log_file: /var/log/nats-server.log
include resolver.conf
EOF

nsc add account Infra
nsc edit account Infra --sk generate
nsc edit account --name Infra --js-mem-storage -1 --js-disk-storage -1 --js-streams -1 --js-consumer -1

ACCOUNT_PUB=$(nsc describe account Infra --field sub | jq -r)
echo $ACCOUNT_PUB > account.pub

nsc add user --account Infra --name auth
AUTH_PUB=$(nsc describe user --account Infra --name auth --field sub | jq -r)
nsc generate creds --account Infra --name auth > auth.creds

nsc add user --account Infra --name user_a
USER_A_PUB=$(nsc describe user --account Infra --name user_a --field sub | jq -r)
nsc generate creds --account Infra --name user_a > user_a.creds

nsc add user --account Infra --name user_b
USER_B_PUB=$(nsc describe user --account Infra --name user_b --field sub | jq -r)
nsc generate creds --account Infra --name user_b > user_b.creds

# Create a creds file for the SYS account
nsc generate creds --account SYS --name sys > sys.creds

nsc generate nkey --curve 2> auth.xk
XKEY_KEY=$(sed -n "2,1p" auth.xk)
XKEY_SEED=$(sed -n "1,1p" auth.xk)

nsc edit authcallout \
  --account Infra \
  --curve $XKEY_KEY \
  --auth-user $AUTH_PUB \
  --allowed-account '*'
```

The auth callout service generates new credentials but since it's not being called you can reproduce without by switching up the JWT and seed between user_a and user_b.

### PR DESCRIPTION
**Pull request by aricart**
this is leafnode scenario only with bad creds rolled for the leafnode (jwt and nkey don't match so user cannot be placed into the account as the user validation fails, but the callout is delegated for verification.

Fixes #7841 

Signed-off-by: Your Name <alberto@synadia.com>

### CODE REVIEW

File: server/auth_callout.go [hunk 1]
```diff
@@ -50,6 +50,12 @@ func (s *Server) processClientOrLeafCallout(c *client, opts *Options, proxyRequi
 	} else {
 		acc = c.acc
 	}
+	if acc == nil {
+		// FIX for 7841 - hand rolled creds on leafnode became crasher here
```
Comment (derekcollison) [inline server/auth_callout.go]: Put full issue URL here..

**Review by derekcollison — APPROVED** [review]
LGTM - One nit to put full issue URL in the comment.

File: server/auth_callout.go (hunk 1 above)
Comment (aricart) [reply server/auth_callout.go]: fixed.

**Review by derekcollison — APPROVED** [review]
LGTM
