### PR TITLE
[FIXED] Scaling up an R1 stream would not replicate existing messages.

### LINKED ISSUE #2955: upgrading a stream's replication factor is not working
```go
func TestJetStreamStreamReplicationUpgrade(t *testing.T) {
	c := createJetStreamClusterExplicit(t, "cluster", 3)
	defer c.shutdown()

	ncSys := natsConnect(t, c.randomServer().ClientURL(), nats.UserInfo("admin", "s3cr3t!"))
	defer ncSys.Close()

	nc := natsConnect(t, c.randomServer().ClientURL())
	defer nc.Close()

	js, err := nc.JetStream()
	require_NoError(t, err)
	cfg := &nats.StreamConfig{Name: "foo", Subjects: []string{"foo"}, Replicas: 1, Retention: nats.LimitsPolicy, MaxMsgs: 10}
	si, err := js.AddStream(cfg)
	require_NoError(t, err)
	require_True(t, si.Config.Replicas == 1)

	msg := [512]byte{}
	for i := 0; i < 10; i++ {
		js.Publish("foo", msg[:])
	}

	cfg.Replicas = 3
	si, err = js.UpdateStream(cfg)
	require_NoError(t, err)
	require_True(t, si.Config.Replicas == 3)
	require_True(t, si.State.Msgs == 10)

	time.Sleep(time.Minute)

	// INSTEAD: one server contains: s.Jsz().Store == blkfi.Size() == 5450 (this is what all server should look like)
	// all other server contain:     s.Jsz().Store == blkfi.Size() == 0
	// indicating that no catchup has happened

	refInfoSize := uint64(0)
	for _, s := range c.servers {
		jsi, err := s.Jsz(nil)
		require_NoError(t, err)
		require_True(t, jsi.Streams == 1)
		refInfoSize = jsi.Store
		fmt.Printf("storesize %d jsinfo %+v\n", refInfoSize, jsi)

		// s.Shutdown() tried shutdown to rule out some weird flush issue, but then 1.blk file is gone
		// (probably because it's empty)
	}

	time.Sleep(time.Minute)

	for _, s := range c.servers {
		blkfi, err := os.Stat(filepath.Join(s.StoreDir(), "$G/streams/foo/msgs/1.blk"))
		require_NoError(t, err)
		fmt.Printf("%d\n", blkfi.Size())
		require_True(t, refInfoSize == uint64(blkfi.Size()))
	}
}


```

### PR DESCRIPTION
**Pull request by derekcollison**
Also fixed a bug where we were incorrectly not spinning up the monitoring loop for a stream when going from 3->1->3.

Signed-off-by: Derek Collison <derek@nats.io>

Resolves #2955 

/cc @nats-io/core

### CODE REVIEW

File: server/jetstream_cluster.go [hunk 1]
```diff
@@ -2272,6 +2281,11 @@ func (js *jetStream) processUpdateStreamAssignment(sa *streamAssignment) {
 	sa.consumers = osa.consumers
 	sa.err = osa.err
 
+	// If we detect we are scaling down to 1, non-clustered, and we had a previous node, clear it here.
+	if sa.Config.Replicas == 1 && sa.Group.node != nil {
+		sa.Group.node = nil
```
Comment (kozlovic) [inline server/jetstream_cluster.go:2286]: If this was a R>1 and now R1, did we stop monitoring of that stream? Is that done somewhere else?

File: server/jetstream_cluster_test.go [hunk 2]
```diff
@@ -10674,6 +10674,23 @@ func TestJetStreamClusterStreamReplicaUpdateFunctionCheck(t *testing.T) {
 	}
 
 	checkSubsPending(t, sub, 3*numMsgs)
+
+	// Make sure cluster replicas are current.
+	for _, r := range si.Cluster.Replicas {
+		if !r.Current {
```
Comment (kozlovic) [inline server/jetstream_cluster_test.go:10680]: Does that need to be protected with a "checkFor()"?

File: server/jetstream_cluster_test.go [hunk 3]
```diff
@@ -10674,6 +10674,23 @@ func TestJetStreamClusterStreamReplicaUpdateFunctionCheck(t *testing.T) {
...
+			t.Fatalf("Expected replica to be current: %+v", r)
+		}
+	}
+
+	// Now check each indidvidual stream on each server to make sure replication occurred.
+	for _, s := range c.servers {
+		mset, err := s.GlobalAccount().lookupStream("TEST")
+		require_NoError(t, err)
+		state := mset.state()
+		if state.Msgs != uint64(3*numMsgs) || state.FirstSeq != 1 || state.LastSeq != 30 || state.Bytes != 1320 {
```
Comment (kozlovic) [inline server/jetstream_cluster_test.go:10690]: Same thing, will that create a flapper? Should both checks be cover under a unique checkFor?

File: server/jetstream_cluster_test.go (hunk 2 above)
Comment (derekcollison) [reply server/jetstream_cluster_test.go:10680]: Do you see this one flapping?

File: server/jetstream_cluster_test.go (hunk 3 above)
Comment (derekcollison) [reply server/jetstream_cluster_test.go:10690]: Probably a good idea, will make that change.

File: server/jetstream_cluster_test.go (hunk 2 above)
Comment (kozlovic) [reply server/jetstream_cluster_test.go:10680]: No, I did not. Was just wondering if the state (Current and number msgs in check below) are guaranteed to be up-to-date at this place in the test. If not, then it may cause flapping on Travis.

Comment (derekcollison) [reply server/jetstream_cluster_test.go]: I could not make it fail after 50 runs with race and non-race but made the change anyway, good call by you.

File: server/jetstream_cluster_test.go [hunk 4]
```diff
@@ -10677,19 +10677,30 @@ func TestJetStreamClusterStreamReplicaUpdateFunctionCheck(t *testing.T) {
 
 	// Make sure cluster replicas are current.
 	for _, r := range si.Cluster.Replicas {
-		if !r.Current {
-			t.Fatalf("Expected replica to be current: %+v", r)
-		}
+		checkFor(t, 5*time.Second, 100*time.Millisecond, func() error {
+			if !r.Current {
```
Comment (kozlovic) [inline server/jetstream_cluster_test.go:10681]: Oh, that's for nothing, the state of si.Cluster.Replicas is not going to change, so r.Current would always be the same. It would have to include the StreamInfo request itself. Since I have not been able to have it flap either, you can remove for now.

**Review by kozlovic — CHANGES_REQUESTED** [review]

File: server/jetstream_cluster_test.go (hunk 4 above)
Comment (derekcollison) [reply server/jetstream_cluster_test.go:10683]: Fixed

File: server/jetstream_cluster_test.go [hunk 5]
```diff
@@ -10676,20 +10676,33 @@ func TestJetStreamClusterStreamReplicaUpdateFunctionCheck(t *testing.T) {
 	checkSubsPending(t, sub, 3*numMsgs)
 
 	// Make sure cluster replicas are current.
-	for _, r := range si.Cluster.Replicas {
-		if !r.Current {
-			t.Fatalf("Expected replica to be current: %+v", r)
+	checkFor(t, 5*time.Second, 100*time.Millisecond, func() error {
+		si, err = js.StreamInfo("TEST")
+		require_NoError(t, err)
```
Comment (kozlovic) [inline server/jetstream_cluster_test.go:10681]: You can't use that here... you would need: `if err != nil { return err }`...

**Review by kozlovic — CHANGES_REQUESTED** [review]

File: server/jetstream_cluster_test.go (hunk 5 above)
Comment (derekcollison) [reply server/jetstream_cluster_test.go:10681]: We should always be able to get stream info, so that is fatal to me for the test if we get an error.

**Review by kozlovic — APPROVED** [review]
LGTM
