### PR TITLE
[Fixed] Skip fetch when a non config based account resolver is used

### LINKED ISSUE #1532: Silent subscription loss on route when the account resolver fails to fetch the account
## Defect
This happens in operator mode with non memory based resolver.

When a subscriber connects to a server in a cluster,
The server it is directly connected to will fetch the account jwt.
The subscription is forwarded to other server in a cluster.
Triggered by this subscription, each server will fetch the corresponding account jwt as well.
**If that fetch fails the subscription is dropped.** 

Later, when a publisher connecting to one of these server sends a message to that subject, that message does not make it to the subscriber.

I created a unit test to demonstrate the issue in master.
I could not find a mechanism to recover from that.

If the fetch is slow, it will also block all other incoming traffic on that route.
In addition to that, an inline fetch would impede receiving a nats based fetch response.

### PR DESCRIPTION
**Pull request by matthiashanel**
[Fixed] Skip fetch when a non config based account resolver is used
    Resolves #1532

    Instead of the fetched account we create a dummy account that is
    expired. Any client connecting will trigger a fetch of the actual
    account jwt.

    This also avoids one fetch, thus the unit test was changed to reflect this.
    Unlike other resolver the memory resolver does not depend on external
    systems. It is purely based on server configuration. Therefore, fetch
    can be done and not finding an account means there is a configuration issue.

Also  reduce usage of tmpAccounts to only location where it is needed imports
    On import handle it with priority as in non recursive situations, it
    won't be present.

### CODE REVIEW

File: server/route.go [hunk 1]
```diff
@@ -992,13 +992,47 @@ func (c *client) processRemoteSub(argo []byte, hasOrigin bool) (err error) {
...
-	acc, _ := srv.LookupAccount(accountName)
+	// Lookup account while avoiding fetch.
+	// A slow fetch delays subsequent remote messages. It also avoids the expired check (see below).
+	// With all but memory resolver lookup can be delayed or fail.
+	// It is also possible that the account can't be resolved yet.
+	// This does not apply to the memory resolver.
+	// When used, perform the fetch.
+	staticResolver := true
+	if res := srv.AccountResolver(); res != nil {
+		if _, ok := res.(*MemAccResolver); ok {
```
Comment (kozlovic) [inline server/route.go:1003]: Maybe could be rewritten:
```
if _, ok := res.(*MemAccResolver); !ok {
    staticResolver = false
}
```
since you already preset `staticResolver := true`

File: server/route.go [hunk 2]
```diff
@@ -992,13 +992,47 @@ func (c *client) processRemoteSub(argo []byte, hasOrigin bool) (err error) {
...
+			staticResolver = true
+		} else {
+			staticResolver = false
+		}
+	}
+	acc := (*Account)(nil)
```
Comment (kozlovic) [inline server/route.go:1009]: Although valid, a simple `var acc *Account` reads better I think, and more inline with rest of the code.

File: server/accounts.go [hunk 3]
```diff
@@ -2353,7 +2353,14 @@ func (s *Server) UpdateAccountClaims(a *Account, ac *jwt.AccountClaims) {
 		}
 	}
 	for _, i := range ac.Imports {
-		acc, err := s.lookupAccount(i.Account)
+		// check tmpAccounts with priority
+		acc := (*Account)(nil)
+		err := error(nil)
```
Comment (kozlovic) [inline server/accounts.go:2358]: Again, would do:
```
var acc *Account
var err error
```

File: server/route.go (hunk 1 above)
Comment (matthiashanel) [reply server/route.go:1003]: true, will change

File: server/route.go (hunk 2 above)
Comment (matthiashanel) [reply server/route.go:1009]: changed

File: server/accounts.go (hunk 3 above)
Comment (matthiashanel) [reply server/accounts.go:2358]: changed

**Comment by matthiashanel** [comment]
@kozlovic Incorporated your comments.
