### PR TITLE
Fix race condition in `clientHasMovedToDifferentAccount`

### LINKED ISSUE #4560: Race condition in reloading config at reload.go:2012
### What version were you using?

2.10.0-beta.56 (latest main branch)

### What environment was the server running in?

Ubuntu 23.04 on intel.

### Is this defect reproducible?

Sometimes, using go test -race on my app

### Given the capability you are leveraging, describe your expectation?

No race conditions occurs

### Given the expectation, what is the defect you are observing?

The race condition occurs during reload of account info in clientHasMovedToDifferentAccount().
The read at reload.go:2012 is outside the mutex lock, while the write at client.go:1974 is within the mutex locked area.

The section of code shows that a read of c.opts.NKey and c.opts.Username occurs before the lock on line 2024:
```go
if c.opts.Nkey != "" {
	if s.nkeys != nil {
		nu = s.nkeys[c.opts.Nkey]
	}
} else if c.opts.Username != "" {
	if s.users != nil {
		u = s.users[c.opts.Username]
	}
} else {
	return false
}
// Get the current account name
c.mu.Lock()
```

race report:
```
[307924] 2023/09/19 09:24:01.680756 [INF] Reloaded: authorization users
[307924] 2023/09/19 09:24:01.680787 [INF] Reloaded: accounts
==================
WARNING: DATA RACE
Write at 0x00c0001fbed0 by goroutine 279:
  reflect.Value.SetString()
      /snap/go/10339/src/reflect/value.go:2463 +0x87
  encoding/json.(*decodeState).literalStore()
      /snap/go/10339/src/encoding/json/decode.go:947 +0x1024
  encoding/json.(*decodeState).value()
      /snap/go/10339/src/encoding/json/decode.go:388 +0x224
  encoding/json.(*decodeState).object()
      /snap/go/10339/src/encoding/json/decode.go:755 +0x14ab
  encoding/json.(*decodeState).value()
      /snap/go/10339/src/encoding/json/decode.go:374 +0xae
  encoding/json.(*decodeState).unmarshal()
      /snap/go/10339/src/encoding/json/decode.go:181 +0x38f
  encoding/json.Unmarshal()
      /snap/go/10339/src/encoding/json/decode.go:108 +0x22b
  github.com/nats-io/nats-server/v2/server.(*client).processConnect()
      /home/henk/dev/hiveot/nats-server/server/client.go:1974 +0x3e7
  github.com/nats-io/nats-server/v2/server.(*client).parse()
      /home/henk/dev/hiveot/nats-server/server/parser.go:926 +0x1409
  github.com/nats-io/nats-server/v2/server.(*client).readLoop()
      /home/henk/dev/hiveot/nats-server/server/client.go:1369 +0x1c98
  github.com/nats-io/nats-server/v2/server.(*Server).createClientEx.func1()
      /home/henk/dev/hiveot/nats-server/server/server.go:3132 +0x54
  github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine.func1()
      /home/henk/dev/hiveot/nats-server/server/server.go:3609 +0x277

Previous read at 0x00c0001fbed0 by goroutine 276:
  github.com/nats-io/nats-server/v2/server.(*Server).clientHasMovedToDifferentAccount()
      /home/henk/dev/hiveot/nats-server/server/reload.go:2012 +0x57
  github.com/nats-io/nats-server/v2/server.(*Server).reloadAuthorization()
      /home/henk/dev/hiveot/nats-server/server/reload.go:1907 +0x58c
  github.com/nats-io/nats-server/v2/server.(*Server).applyOptions()
      /home/henk/dev/hiveot/nats-server/server/reload.go:1704 +0x351
  github.com/nats-io/nats-server/v2/server.(*Server).reloadOptions()
      /home/henk/dev/hiveot/nats-server/server/reload.go:1089 +0x217
  github.com/nats-io/nats-server/v2/server.(*Server).ReloadOptions()
      /home/henk/dev/hiveot/nats-server/server/reload.go:1028 +0x4f0
  github.com/hiveot/hub/core/natsmsgserver.(*NatsMsgServer).ApplyAuth()
      /home/henk/dev/hiveot/hub/core/natsmsgserver/NatsAuth.go:80 +0xf9c
  github.com/hiveot/hub/core/auth/authservice.(*AuthManageProfile).onChange.func1()
      /home/henk/dev/hiveot/hub/core/auth/authservice/AuthManageProfile.go:133 +0x6f

```

### PR DESCRIPTION
**Pull request by neilalexander**
Fixes #4560. The client lock needs to be held before accessing the `c.opts`.

Signed-off-by: Neil Twigg <neil@nats.io>

### CODE REVIEW

**Review by wallyqs — APPROVED** [review]
LGTM

**Review by bruth — APPROVED** [review]
LGTM

File: server/reload.go [hunk 1]
```diff
@@ -2009,6 +2009,8 @@ func (s *Server) clientHasMovedToDifferentAccount(c *client) bool {
 		nu *NkeyUser
 		u  *User
 	)
+	c.mu.Lock()
+	defer c.mu.Unlock()
 	if c.opts.Nkey != "" {
```
Comment (derekcollison) [inline server/reload.go:2014]: _EMPTY_

**Review by derekcollison — APPROVED** [review]
LGTM

File: server/reload.go (hunk 1 above)
Comment (bruth) [reply server/reload.go:2014]: Always a bugger 😄

**Review by derekcollison — COMMENTED** [review]
Thanks.
