### PR TITLE
Don't log error in legitimate nkey auth callout config case (4479).

### LINKED ISSUE #4479: Authorization callout user not valid (when having users in nats options)
### What version were you using?

Latest from main as of 2023-09-02.

### What environment was the server running in?

dev box Ubuntu

### Is this defect reproducible?

Yes. Take a look at auth.go:293
```go
for _, u := range opts.AuthCallout.AuthUsers {
			// Check for user in users and nkeys since this is server config.
			var found bool
			if len(s.users) > 0 {
				_, found = s.users[u]
			} else if len(s.nkeys) > 0 && !found {
				_, found = s.nkeys[u]
			}
			if !found {
				s.Errorf("Authorization callout user %q not valid: %v", u, err)
			}
		}
```
The statement:
> else if len(s.nkeys) > 0 && !found {

is never run when len(s.users) > 0.

This should simply be an "if len()..." without the else.

### Given the capability you are leveraging, describe your expectation?

No errors should be reported if the callout user exists in nkeys

### Given the expectation, what is the defect you are observing?

I'm observing an incorrect error in the log. The callout nkey does exist, but the check doesn't check the nkeys.

### PR DESCRIPTION
**Pull request by tbeets**
`Resolves #4479 `

In AuthCallout server-config system, a spurious error message would be generated on server reload in the edge case that the AuthCallout user is an NKEY and both User and NKEY account members are defined in the config.

### CODE REVIEW

**Review by aricart — APPROVED** [review]
LGTM

**Review by neilalexander — APPROVED** [review]
LGTM

File: server/auth.go [hunk 1]
```diff
@@ -28,10 +28,11 @@ import (
 	"sync/atomic"
 	"time"
 
+	"golang.org/x/crypto/bcrypt"
+
```
Comment (derekcollison) [inline server/auth.go:32]: Remove newline here.

**Review by derekcollison — COMMENTED** [review]
LGTM - one nit, then we can merge.

File: server/auth.go (hunk 1 above)
Comment (tbeets) [reply server/auth.go:32]: I'm using the `goimports -local github.com/nats.io/` style where it [groups our project imports separately from stdlib and everything else](https://stackoverflow.com/questions/38704769/golang-import-grouping-by-package).

Do you specifically just want the stdlib and everything else (including our stuff) style?

Comment (derekcollison) [reply server/auth.go:32]: ok usually we put these at bottom with a single line space.

**Review by derekcollison — APPROVED** [review]
LGTM
