### PR TITLE
[FIXED] Handling of gossiped URLs

### LINKED ISSUE #1515: missing client connect url after re connect of restarted server is processed before disconnect.
## Defect
added a unit test #1516 to illustrate the issue.

Basically we use a map of url, when that kind or re-ordering happens we forget about a url.

This can also be re-produced whit the following setup.
Server_A)
Client_advertise URLA

Server_B and Server_C have the same value in client_advertise
client_advertise URLBC

When starting all 3 server and connecting via telnet to server_A,
connect_urls will contain URLA and URLBC

if Server_B OR Server_C is shut down, server_A will only return URLA.

This can be solved by ref counting the url entires in the map or using a list instead.

Another oddity is that if all server provide the same value for client_advertise, the list will contain two identical entries.
One for the current server, one for the other server.

The unit test and the example here are a bit contrived. 
However, I only looked at this because a user reported that connect_urls was off.

### PR DESCRIPTION
**Pull request by kozlovic**
If some servers in the cluster have the same connect URLs (due
to the use of client advertise), then it would be possible to
have a server sends the connect_urls INFO update to clients with
missing URLs.

Resolves #1515

Signed-off-by: Ivan Kozlovic <ivan@synadia.com>

### CODE REVIEW

File: server/server.go [hunk 1]
```diff
@@ -97,6 +97,8 @@ type Info struct {
 	LeafNodeURLs []string `json:"leafnode_urls,omitempty"` // LeafNode URLs that the server can reconnect to.
 }
 
+type gossipURLs map[string]int
```
Comment (matthiashanel) [inline server/server.go:100]: maybe move to util where it's functions are?

Comment (kozlovic) [reply server/server.go:100]: I wonder even if I make that a type. It does not prevent one from using map[string]int directly anyway. But if I keep as a type, should I name it differently? Should it be more mapOfURLsWithRefcount or something like that? (I am very bad at naming)

Comment (matthiashanel) [reply server/server.go:100]: I'm fine with the current name. Maybe refCountedUrlSet?

Comment (kozlovic) [reply server/server.go]: I have renamed, moved to util and made the add/remove/get receivers for this new type. I think it is cleaner. I you could have another look, I would appreciate it.
