### PR TITLE
FIX #1128 - allow cluster urls with -1 to work again

### LINKED ISSUE #1128: behaviour to create a cluster on a random port fails due to different option parsing
Previous version of nats-server allowed the creation of clusters on random ports by:
`nats-server --http_port -1 --cluster nats://127.0.0.1:-1 --port -1 --ports_file_dir /tmp` with the ports file describing where the cluster lives. This is enables automated tests to be more reliable for other platforms that cannot inline the server process.

### PR DESCRIPTION
**Pull request by aricart**
Modified the cluster listenstr parsing to allow cluster urls that have a -1 for a port. This re-enables ability to create clusters on a random port for testing.

### CODE REVIEW

**Comment by aricart** [comment]
This is a regression on the nats-server. Looks like the flow to parse the cluster information changed.

File: server/opts.go [hunk 1]
```diff
@@ -2885,6 +2885,15 @@ func overrideCluster(opts *Options) error {
 		opts.Cluster.Port = 0
 		return nil
 	}
+	// -1 will fail url.Parse, so if we have -1, change it to
+	// 0, and then on parse, replace the port with -1 so we get
```
Comment (kozlovic) [inline server/opts.go]: Should `and then on parse` be `and then after parse`?

File: server/opts.go [hunk 2]
```diff
@@ -2885,6 +2885,15 @@ func overrideCluster(opts *Options) error {
...
+	// automatic port allocation
+	wantsRandom := false
+	if strings.HasSuffix(opts.Cluster.ListenStr, ":-1") {
```
Comment (kozlovic) [inline server/opts.go]: I have checked and we don't use `opts.Cluster.ListenStr` anywhere in the server code (outside of command line parsing I mean), so I think it is ok. Otherwise, I would have suggested to do `listenStr := opts.Cluster.ListenStr` and do all the changes/reference from there on on `listenStr` so that we don't alter opts.Cluster.ListenStr.
