### PR TITLE
[FIXED] Possible deadlock with solicited leafnodes when cluster conflict

### LINKED ISSUE #1543: Server can deadlock when solicited leafnode connection is closed on update
During the dynamic cluster name negotiation, a cluster name update can trigger a notification via the leafnode that could trigger a cluster name conflict error that causes the connection to be closed and leave the server hanging.

```
goroutine 43 [semacquire]:
sync.runtime_SemacquireMutex(0xc0000d0034, 0xc000186a00, 0x1)
	/usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc0000d0030)
	/usr/local/go/src/sync/mutex.go:138 +0xfc
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
github.com/nats-io/nats-server/v2/server.(*Server).removeLeafNodeConnection(0xc0000d0000, 0xc000304000)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/leafnode.go:985 +0x167
github.com/nats-io/nats-server/v2/server.(*Server).removeClient(0xc0000d0000, 0xc000304000)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:2326 +0x1d5
github.com/nats-io/nats-server/v2/server.(*client).teardownConn(0xc000304000)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/client.go:4079 +0x44e
github.com/nats-io/nats-server/v2/server.(*client).closeConnection(0xc000304000, 0x1d)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/client.go:3993 +0xd2
github.com/nats-io/nats-server/v2/server.(*Server).updatedSolicitedLeafnodes(0xc0000d0000)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/leafnode.go:1846 +0x101
github.com/nats-io/nats-server/v2/server.(*Server).setClusterName(0xc0000d0000, 0xc00018d100, 0x16)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:438 +0xd1
github.com/nats-io/nats-server/v2/server.(*client).processRouteInfo(0xc0001b7980, 0xc0001ded00)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/route.go:519 +0x271
github.com/nats-io/nats-server/v2/server.(*client).processInfo(0xc0001b7980, 0xc0001f6405, 0x1c2, 0x1fb, 0x103fe2f, 0xc000035000)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/client.go:1382 +0x107
github.com/nats-io/nats-server/v2/server.(*client).parse(0xc0001b7980, 0xc0001f6400, 0x1c9, 0x200, 0x1c9, 0x0)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/parser.go:982 +0x4322
github.com/nats-io/nats-server/v2/server.(*client).readLoop(0xc0001b7980, 0x0, 0x0, 0x0)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/client.go:971 +0x50a
github.com/nats-io/nats-server/v2/server.(*Server).createRoute.func2()
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/route.go:1394 +0x3b
created by github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:2523 +0xc1
```

## Defect

 - [X] Included `nats-server -DV` output
 - [X] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats-server` and affected client libraries used:

2.2.0-beta.20 (not yet released)

#### Steps or code to reproduce the issue:

- Start a node that can be used for leafnode connections

```hcl
port = 4222
leaf    { port = 7422 }
```

- Connect a couple of node as a leafnode that has it as a remote and that can also be used as a seed server

```hcl
server_name = X-A

port = 23234
cluster { port = 63234  }

leaf {
  remotes [
    { url = "nats://localhost:7422" }
  ]
}
```

- Start another server that becomes part of a cluster that has the same leafnode remote connection and that becomes part of the cluster with a static route.  Sometimes this can end up in a deadlock.

```hcl
server_name = X-C

port = 23236

cluster { 
  port = 63236 
   routes [
     "nats://localhost:63234"
    ]
}

leaf {
  remotes [
    { url = "nats://localhost:7422" }
  ]
}
```

From the stack trace, it looks like the reason could be that on cluster name change the lock is held at:
https://github.com/nats-io/nats-server/blob/fbab1daf063e3ed8e26b89ee69f752148fefea3d/server/server.go#L430

and still held when this is called:
https://github.com/nats-io/nats-server/blob/4a4a36f9ec7efe674e9975b4a3e69cf042140902/server/leafnode.go#L985

#### Expected result:

Server to start or exit without hanging.

#### Actual result:

Deadlock of the server, have to use SIGKILL/SIGABRT can be used to stop it.

Sample run:

```
nats-server-head -c /tmp/X-C.conf -DV
[73694] 2020/07/29 22:44:02.407035 [INF] Starting nats-server version 2.2.0-beta.20
[73694] 2020/07/29 22:44:02.407135 [DBG] Go build version go1.14.4
[73694] 2020/07/29 22:44:02.407138 [INF] Git commit [not set]
[73694] 2020/07/29 22:44:02.407140 [INF] Using configuration file: /tmp/X-C.conf
[73694] 2020/07/29 22:44:02.407157 [DBG] Created system account: "$SYS"
[73694] 2020/07/29 22:44:02.407665 [INF] Listening for client connections on 0.0.0.0:23236
[73694] 2020/07/29 22:44:02.407670 [INF] Server id is NBUSECKWQPSXH2AW6NXKZXHYL3AE2XQZUZB34DEJCZP32ZP2JLCNHVXQ
[73694] 2020/07/29 22:44:02.407672 [INF] Server is ready
[73694] 2020/07/29 22:44:02.407676 [DBG] Get non local IPs for "0.0.0.0"
[73694] 2020/07/29 22:44:02.407860 [DBG]   ip=10.0.0.144
[73694] 2020/07/29 22:44:02.407864 [DBG]   ip=2601:644:680:2530:145d:2149:ac90:d4bf
[73694] 2020/07/29 22:44:02.407866 [DBG]   ip=2601:644:680:2530:9bc:a483:3169:1b71
[73694] 2020/07/29 22:44:02.407868 [DBG]   ip=2601:644:680:2530::68c8
[73694] 2020/07/29 22:44:02.407988 [INF] Cluster name is NROFpxO6EYjh4vG82C55ed
[73694] 2020/07/29 22:44:02.407993 [WRN] Cluster name was dynamically generated, consider setting one
[73694] 2020/07/29 22:44:02.408046 [INF] Listening for route connections on 0.0.0.0:63236
[73694] 2020/07/29 22:44:02.408305 [DBG] Trying to connect to route on localhost:63234
[73694] 2020/07/29 22:44:02.409482 [DBG] Trying to connect as leafnode to remote server on "localhost:7422" ([::1]:7422)
[73694] 2020/07/29 22:44:02.409797 [DBG] [::1]:63234 - rid:2 - Route connect msg sent
[73694] 2020/07/29 22:44:02.409875 [INF] [::1]:63234 - rid:2 - Route connection created
[73694] 2020/07/29 22:44:02.409956 [DBG] [::1]:7422 - lid:3 - Remote leafnode connect msg sent
[73694] 2020/07/29 22:44:02.409964 [DBG] [::1]:7422 - lid:3 - Leafnode connection created
[73694] 2020/07/29 22:44:02.409984 [DBG] [::1]:7422 - lid:3 - Leafnode connection closed: Cluster Name Conflict
[73694] 2020/07/29 22:44:02.410009 [TRC] [::1]:7422 - lid:3 - ->> [LS+ $LDS.NROFpxO6EYjh4vG82C55fp]
[73694] 2020/07/29 22:44:03.598038 [DBG] [::1]:63234 - rid:2 - Router Ping Timer
[73694] 2020/07/29 22:44:03.598080 [TRC] [::1]:63234 - rid:2 - ->> [PING]
[73694] 2020/07/29 22:44:03.598131 [ERR] [::1]:63234 - rid:2 - Error flushing: writev tcp [::1]:59910->[::1]:63234: writev: broken pipe
[73694] 2020/07/29 22:44:03.598142 [INF] [::1]:63234 - rid:2 - Router connection closed: Write Error




^C[73694] 2020/07/29 22:44:08.834187 [DBG] Trapped "interrupt" signal


^C^C^C^C
SIGABRT: abort
PC=0x7fff6c19386a m=0 sigcode=0

goroutine 0 [idle]:
runtime.pthread_cond_wait(0x1ad1ce8, 0x1ad1ca8, 0x7ffe00000000)
	/usr/local/go/src/runtime/sys_darwin.go:390 +0x39
runtime.semasleep(0xffffffffffffffff, 0x7ffeefbff760)
	/usr/local/go/src/runtime/os_darwin.go:63 +0x85
runtime.notesleep(0x1ad1aa8)
	/usr/local/go/src/runtime/lock_sema.go:173 +0xe0
runtime.stoplockedm()
	/usr/local/go/src/runtime/proc.go:1977 +0x88
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2460 +0x4a6
runtime.park_m(0xc000082480)
	/usr/local/go/src/runtime/proc.go:2696 +0x9d
runtime.mcall(0x1066576)
	/usr/local/go/src/runtime/asm_amd64.s:318 +0x5b

goroutine 1 [chan receive]:
github.com/nats-io/nats-server/v2/server.(*Server).WaitForShutdown(...)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:1598
main.main()
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/main.go:118 +0x15f

goroutine 34 [semacquire]:
sync.runtime_SemacquireMutex(0xc0000d0034, 0x1ad0900, 0x1)
	/usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc0000d0030)
	/usr/local/go/src/sync/mutex.go:138 +0xfc
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
github.com/nats-io/nats-server/v2/server.(*Server).eventsRunning(0xc0000d0000, 0x1ac1820)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/events.go:384 +0xae
github.com/nats-io/nats-server/v2/server.(*Server).shutdownEventing(0xc0000d0000)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/events.go:760 +0x3c
github.com/nats-io/nats-server/v2/server.(*Server).Shutdown(0xc0000d0000)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:1459 +0x43
github.com/nats-io/nats-server/v2/server.(*Server).handleSignals.func1(0xc00008e4e0, 0xc0000d0000)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/signal.go:52 +0x30f
created by github.com/nats-io/nats-server/v2/server.(*Server).handleSignals
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/signal.go:45 +0x11a

goroutine 18 [syscall]:
os/signal.signal_recv(0x170f340)
	/usr/local/go/src/runtime/sigqueue.go:144 +0x96
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.Notify.func1
	/usr/local/go/src/os/signal/signal.go:127 +0x44

goroutine 35 [semacquire]:
sync.runtime_SemacquireMutex(0xc0000d0034, 0x0, 0x1)
	/usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc0000d0030)
	/usr/local/go/src/sync/mutex.go:138 +0xfc
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
github.com/nats-io/nats-server/v2/server.(*Server).eventsRunning(0xc0000d0000, 0x0)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/events.go:384 +0xae
github.com/nats-io/nats-server/v2/server.(*Server).internalSendLoop(0xc0000d0000, 0xc0001ae0f0)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/events.go:256 +0xc2
created by github.com/nats-io/nats-server/v2/server.(*Server).setSystemAccount
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:1001 +0x30a

goroutine 36 [select]:
github.com/nats-io/nats-server/v2/server.(*Server).startGWReplyMapExpiration.func1()
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/gateway.go:2999 +0x15b
created by github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:2523 +0xc1

goroutine 37 [semacquire]:
sync.runtime_SemacquireMutex(0xc0000d0034, 0x0, 0x1)
	/usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc0000d0030)
	/usr/local/go/src/sync/mutex.go:138 +0xfc
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
github.com/nats-io/nats-server/v2/server.(*Server).removeLeafNodeConnection(0xc0000d0000, 0xc000304000)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/leafnode.go:985 +0x167
github.com/nats-io/nats-server/v2/server.(*Server).createLeafNode(0xc0000d0000, 0x1719680, 0xc0000960a8, 0xc00019e100, 0x3b9aca00)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/leafnode.go:814 +0xadd
github.com/nats-io/nats-server/v2/server.(*Server).connectToRemoteLeafNode(0xc0000d0000, 0xc00019e100, 0x1)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/leafnode.go:316 +0x6f2
github.com/nats-io/nats-server/v2/server.(*Server).solicitLeafNodeRemotes.func1()
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/leafnode.go:109 +0x38
created by github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:2523 +0xc1

goroutine 11 [semacquire]:
sync.runtime_SemacquireMutex(0xc0000d0034, 0x1e40100, 0x1)
	/usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc0000d0030)
	/usr/local/go/src/sync/mutex.go:138 +0xfc
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
github.com/nats-io/nats-server/v2/server.(*Server).globalAccount(0xc0000d0000, 0xc00016c000)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:521 +0x8c
github.com/nats-io/nats-server/v2/server.(*Server).createClient(0xc0000d0000, 0x1719680, 0xc000010070, 0x0, 0xc0001d77d0)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:1990 +0x1d5
github.com/nats-io/nats-server/v2/server.(*Server).AcceptLoop.func2(0x1719680, 0xc000010070)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:1658 +0x47
github.com/nats-io/nats-server/v2/server.(*Server).acceptConnections.func1()
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:1692 +0x40
created by github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:2523 +0xc1

goroutine 39 [IO wait]:
internal/poll.runtime_pollWait(0x7b15f18, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc00019e198, 0x72, 0x0, 0x0, 0x16312cb)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc00019e180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:384 +0x1d4
net.(*netFD).accept(0xc00019e180, 0xc000051ec8, 0x1065ac0, 0xc000051f10)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc0001846a0, 0x14d5961, 0xc000000000, 0xc00007f710)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc0001846a0, 0xc00007f710, 0xc000010001, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock.go:261 +0x64
github.com/nats-io/nats-server/v2/server.(*Server).acceptConnections(0xc0000d0000, 0x1712300, 0xc0001846a0, 0x1630fd1, 0x6, 0xc000186790, 0xc0001867a0)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:1680 +0x42
created by github.com/nats-io/nats-server/v2/server.(*Server).AcceptLoop
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:1658 +0x947

goroutine 40 [IO wait]:
internal/poll.runtime_pollWait(0x7b15e38, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc00019fa18, 0x72, 0x0, 0x0, 0x16312cb)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc00019fa00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:384 +0x1d4
net.(*netFD).accept(0xc00019fa00, 0x1007ecb, 0xc00008e780, 0xc0001be8f8)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc0001847e0, 0xc00008e780, 0x0, 0xc000192780)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc0001847e0, 0x0, 0xc0001d5f78, 0x1007b1b, 0xc0001be8a0)
	/usr/local/go/src/net/tcpsock.go:261 +0x64
github.com/nats-io/nats-server/v2/server.(*Server).acceptConnections(0xc0000d0000, 0x1712300, 0xc0001847e0, 0x16305aa, 0x5, 0xc000186970, 0x0)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:1680 +0x42
created by github.com/nats-io/nats-server/v2/server.(*Server).startRouteAcceptLoop
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/route.go:1753 +0x90a

goroutine 45 [semacquire]:
sync.runtime_SemacquireMutex(0xc0000d0034, 0xc00004db00, 0x1)
	/usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc0000d0030)
	/usr/local/go/src/sync/mutex.go:138 +0xfc
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
github.com/nats-io/nats-server/v2/server.(*Server).accountDisconnectEvent(0xc0000d0000, 0xc000304000, 0xbfc0b56898702a20, 0x6017e1, 0x1ad09e0, 0x163ada3, 0x15)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/events.go:1098 +0x708
github.com/nats-io/nats-server/v2/server.(*Server).saveClosedClient(0xc0000d0000, 0xc000304000, 0x1719680, 0xc0000960a8, 0x1d)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:2169 +0xe7
created by github.com/nats-io/nats-server/v2/server.(*client).markConnAsClosed
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/client.go:1315 +0x215

goroutine 43 [semacquire]:
sync.runtime_SemacquireMutex(0xc0000d0034, 0xc000186a00, 0x1)
	/usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc0000d0030)
	/usr/local/go/src/sync/mutex.go:138 +0xfc
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
github.com/nats-io/nats-server/v2/server.(*Server).removeLeafNodeConnection(0xc0000d0000, 0xc000304000)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/leafnode.go:985 +0x167
github.com/nats-io/nats-server/v2/server.(*Server).removeClient(0xc0000d0000, 0xc000304000)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:2326 +0x1d5
github.com/nats-io/nats-server/v2/server.(*client).teardownConn(0xc000304000)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/client.go:4079 +0x44e
github.com/nats-io/nats-server/v2/server.(*client).closeConnection(0xc000304000, 0x1d)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/client.go:3993 +0xd2
github.com/nats-io/nats-server/v2/server.(*Server).updatedSolicitedLeafnodes(0xc0000d0000)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/leafnode.go:1846 +0x101
github.com/nats-io/nats-server/v2/server.(*Server).setClusterName(0xc0000d0000, 0xc00018d100, 0x16)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:438 +0xd1
github.com/nats-io/nats-server/v2/server.(*client).processRouteInfo(0xc0001b7980, 0xc0001ded00)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/route.go:519 +0x271
github.com/nats-io/nats-server/v2/server.(*client).processInfo(0xc0001b7980, 0xc0001f6405, 0x1c2, 0x1fb, 0x103fe2f, 0xc000035000)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/client.go:1382 +0x107
github.com/nats-io/nats-server/v2/server.(*client).parse(0xc0001b7980, 0xc0001f6400, 0x1c9, 0x200, 0x1c9, 0x0)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/parser.go:982 +0x4322
github.com/nats-io/nats-server/v2/server.(*client).readLoop(0xc0001b7980, 0x0, 0x0, 0x0)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/client.go:971 +0x50a
github.com/nats-io/nats-server/v2/server.(*Server).createRoute.func2()
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/route.go:1394 +0x3b
created by github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:2523 +0xc1

goroutine 44 [semacquire]:
sync.runtime_SemacquireMutex(0xc0000d0034, 0xc000281a00, 0x1)
	/usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc0000d0030)
	/usr/local/go/src/sync/mutex.go:138 +0xfc
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
github.com/nats-io/nats-server/v2/server.(*Server).removeRoute(0xc0000d0000, 0xc0001b7980)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/route.go:1985 +0x336
github.com/nats-io/nats-server/v2/server.(*Server).removeClient(0xc0000d0000, 0xc0001b7980)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:2322 +0x1ad
github.com/nats-io/nats-server/v2/server.(*client).teardownConn(0xc0001b7980)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/client.go:4079 +0x44e
github.com/nats-io/nats-server/v2/server.(*client).writeLoop(0xc0001b7980)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/client.go:839 +0x204
github.com/nats-io/nats-server/v2/server.(*Server).createRoute.func3()
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/route.go:1397 +0x2a
created by github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:2523 +0xc1

goroutine 12 [semacquire]:
sync.runtime_SemacquireMutex(0xc0000d0034, 0x1e40100, 0x1)
	/usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc0000d0030)
	/usr/local/go/src/sync/mutex.go:138 +0xfc
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
github.com/nats-io/nats-server/v2/server.(*Server).globalAccount(0xc0000d0000, 0xc00016d980)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:521 +0x8c
github.com/nats-io/nats-server/v2/server.(*Server).createClient(0xc0000d0000, 0x1719680, 0xc000010078, 0x0, 0x103f176)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:1990 +0x1d5
github.com/nats-io/nats-server/v2/server.(*Server).AcceptLoop.func2(0x1719680, 0xc000010078)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:1658 +0x47
github.com/nats-io/nats-server/v2/server.(*Server).acceptConnections.func1()
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:1692 +0x40
created by github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:2523 +0xc1

goroutine 48 [semacquire]:
sync.runtime_SemacquireMutex(0xc0000d0034, 0x1e40e00, 0x1)
	/usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc0000d0030)
	/usr/local/go/src/sync/mutex.go:138 +0xfc
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
github.com/nats-io/nats-server/v2/server.(*Server).globalAccount(0xc0000d0000, 0xc0001b9300)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:521 +0x8c
github.com/nats-io/nats-server/v2/server.(*Server).createClient(0xc0000d0000, 0x1719680, 0xc0001880d0, 0x0, 0x165f770)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:1990 +0x1d5
github.com/nats-io/nats-server/v2/server.(*Server).AcceptLoop.func2(0x1719680, 0xc0001880d0)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:1658 +0x47
github.com/nats-io/nats-server/v2/server.(*Server).acceptConnections.func1()
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:1692 +0x40
created by github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:2523 +0xc1

goroutine 22 [semacquire]:
sync.runtime_SemacquireMutex(0xc0000d0034, 0x1e40700, 0x1)
	/usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc0000d0030)
	/usr/local/go/src/sync/mutex.go:138 +0xfc
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
github.com/nats-io/nats-server/v2/server.(*Server).globalAccount(0xc0000d0000, 0xc000305980)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:521 +0x8c
github.com/nats-io/nats-server/v2/server.(*Server).createClient(0xc0000d0000, 0x1719680, 0xc0000960d8, 0x0, 0x1068761)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:1990 +0x1d5
github.com/nats-io/nats-server/v2/server.(*Server).AcceptLoop.func2(0x1719680, 0xc0000960d8)
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:1658 +0x47
github.com/nats-io/nats-server/v2/server.(*Server).acceptConnections.func1()
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:1692 +0x40
created by github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine
	/Users/wallyqs/repos/k8s-dev/src/github.com/nats-io/nats-server/server/server.go:2523 +0xc1

rax    0x104
rbx    0x2
rcx    0x7ffeefbff598
rdx    0x1b00
rdi    0x1ad1ce8
rsi    0x200100002100
rbp    0x7ffeefbff620
rsp    0x7ffeefbff598
r8     0x0
r9     0xa0
r10    0x0
r11    0x202
r12    0x1ad1ce8
r13    0x16
r14    0x200100002100
r15    0x7c5b5c0
rip    0x7fff6c19386a
rflags 0x203
cs     0x7
fs     0x0
gs     0x0
```

### PR DESCRIPTION
**Pull request by kozlovic**
We cannot call c.closeConnection() under the server lock because
closeConnection() can invoke server lock in some cases.

Created a test that should run without `-race` to reproduce the deadlock
(which it does) but sometimes would fail because cluster would not be
formed. This unconvered an issue with conflict resolution which
test TestRouteClusterNameConflictBetweenStaticAndDynamic() can reproduce
easily. The issue was that we were not updating a dynamic name with
the remote if the remote was non dynamic.

Resolves #1543

Signed-off-by: Ivan Kozlovic <ivan@synadia.com>

### CODE REVIEW

File: server/route.go [hunk 1]
```diff
@@ -515,7 +515,8 @@ func (c *client) processRouteInfo(info *Info) {
 	if info.Cluster != "" && info.Cluster != clusterName {
 		c.mu.Unlock()
 		// If we are dynamic we may update our cluster name.
-		if s.isClusterNameDynamic() && strings.Compare(clusterName, info.Cluster) < 0 {
+		// Use other if remote is non dynamic or their name is "bigger"
+		if s.isClusterNameDynamic() && (!info.Dynamic || (strings.Compare(clusterName, info.Cluster) < 0)) {
```
Comment (kozlovic) [inline server/route.go:519]: By the way, I had this comment in the original PR: https://github.com/nats-io/nats-server/pull/1476#discussion_r439693453 and it was not addressed. @derekcollison What you had addressed is the use of isClusterNameDynamic() instead of accessing the cluster name form options here, but not the fact that we should take into account if the remote is dynamic or not.
Without this change, test https://github.com/nats-io/nats-server/pull/1545/files#diff-30fc7b8a07520e58a86a61dbe200433aR1270 fails 100% of the times.
