### PR TITLE
[FIXED] - Message cleanup for interest stream and no-ack consumers in clustered mode.

### LINKED ISSUE #2488: Consumers stops receiving messages
#### Versions of `nats-server` and affected client libraries used:

Nats server version
```
[83] 2021/09/04 18:51:12.239432 [INF] Starting nats-server
[83] 2021/09/04 18:51:12.239488 [INF]   Version:  2.4.0
[83] 2021/09/04 18:51:12.239494 [INF]   Git:      [219a7c98]
[83] 2021/09/04 18:51:12.239496 [DBG]   Go build: go1.16.7
[83] 2021/09/04 18:51:12.239517 [INF]   Name:     NBVE7O7DMRAZ63STC7Z644KHF5HJ6QQUGLZVGDIKEG32CFL2J6O2456M
[83] 2021/09/04 18:51:12.239533 [INF]   ID:       NBVE7O7DMRAZ63STC7Z644KHF5HJ6QQUGLZVGDIKEG32CFL2J6O2456M
[83] 2021/09/04 18:51:12.239605 [DBG] Created system account: "$SYS"
```

Go client version: `v1.12.0`

#### OS/Container environment:

GKE Kubernetes. Running nats js HA cluster. Deployed via nats helm chart.

#### Steps or code to reproduce the issue:

Stream configuration:
```yaml
apiVersion: jetstream.nats.io/v1beta1
kind: Stream
metadata:
  name: agent
spec:
  name: agent
  subjects: ["data.*"]
  storage: file
  maxAge: 1h
  replicas: 3
  retention: interest
```

There are two consumers to this stream. Each runs as queue subscriber in two services with 2 pod replicas. Note that I don't care if message is not processed, this is why ack none is set.
```go

// 2 pods for service A.
js.QueueSubscribe(
	"data.received",
	"service1_queue",
	func(msg *nats.Msg) {},
	nats.DeliverNew(),
	nats.AckNone(),
)

// 2 pods for service B.
s.js.QueueSubscribe(
	"data.received",
	"service2_queue",
	func(msg *nats.Msg) {},
	nats.DeliverNew(),
	nats.AckNone(),
)
```

#### Expected result:

Consumer receives messages.

#### Actual result:

Stream stats after few days:

```
agent                  │ File    │ 3         │ 28,258   │ 18 MiB  │ 0    │ 84      │ nats-js-0, nats-js-1*, nats-js-2
```

Consumers stats:

```
service1_queue │ Push │ None       │ 0.00s    │ 0           │ 0           │ 0           │ 60,756    │ nats-js-0, nats-js-1*, nats-js-2
service2_queue │ Push │ None       │ 0.00s    │ 0           │ 0           │ 8,193 / 28% │ 60,843    │ nats-js-0, nats-js-1*, nats-js-2
```

1. Non of the nats server pods contains errors indicating any problem.
2. Unprocessed messages count for second consumer stays the same and doesn't decrease.
3. The only fix which helped is after I changed second consumer raft leader with `nats consumer cluster step-down`. But after some time problem still comes back.
4. There are active connections to the server. Checked with `nats server report connections`.

/cc @kozlovic @derekcollison

### PR DESCRIPTION
**Pull request by derekcollison**
Fixed a bug when an interest retention stream with noack consumers is in clustered mode.
We were not properly propagating the ack state and proper cleanup of the stream messages.

Signed-off-by: Derek Collison <derek@nats.io>

Resolves #2488 (Related)

/cc @nats-io/core

### CODE REVIEW

File: server/consumer.go [hunk 1]
```diff
@@ -2359,6 +2354,15 @@ func (o *consumer) deliverMsg(dsubj, subj string, hdr, msg []byte, seq, dc uint6
 
 	// FIXME(dlc) - Capture errors?
 	o.updateDelivered(dseq, seq, dc, ts)
+
+	// If we are ack none and mset is interest only we should make sure stream removes interest.
+	if ap == AckNone && mset.cfg.Retention != LimitsPolicy {
+		if o.node == nil || o.cfg.Direct {
+			mset.amch <- seq
```
Comment (kozlovic) [inline server/consumer.go:2361]: You used to check for `amch != nil`, not sure if this was necessary or not, but you don't do that anymore.

**Review by kozlovic — APPROVED** [review]
LGTM, but small comment about mset.amch

File: server/consumer.go (hunk 1 above)
Comment (derekcollison) [reply server/consumer.go:2361]: In stream.go we always create when cfg.Retention != LimitsPolicy, and since we capture that condition above in line 2359 it has to be present.

Comment (kozlovic) [reply server/consumer.go:2361]: As long as it is not set to nil (which I just checked it is not), then indeed it is ok.
