### PR TITLE
FIXES #2828. 

### LINKED ISSUE #2828: jetstream: consumer edit does not get persisted
#### Versions of `nats-server` and affected client libraries used:

```
[1] 2022/01/28 14:33:34.360155 [INF] Starting nats-server
[1] 2022/01/28 14:33:34.360190 [INF]   Version:  2.7.1
[1] 2022/01/28 14:33:34.360193 [INF]   Git:      [7cf537e]
[1] 2022/01/28 14:33:34.360195 [DBG]   Go build: go1.17.6
[1] 2022/01/28 14:33:34.360197 [INF]   Name:     NCZTFSSNQCCVNR2XMOVOADBZPBELLISODVQBQ52N6SKB6WQ3WQQVN5KG
[1] 2022/01/28 14:33:34.360202 [INF]   Node:     0TCzfDtY
[1] 2022/01/28 14:33:34.360204 [INF]   ID:       NCZTFSSNQCCVNR2XMOVOADBZPBELLISODVQBQ52N6SKB6WQ3WQQVN5KG
[1] 2022/01/28 14:33:34.360247 [DBG] Created system account: "$SYS"
```

#### OS/Container environment:

nats-server running on docker, natscli on arch-linux.

#### Steps or code to reproduce the issue:

1. Start a nats server, with Jetstream
2. Create a consumer with `nats con add BARN --config stream.json`
```json
{
    "ack_policy": "explicit",
    "ack_wait": 15000000000,
    "deliver_policy": "all",
    "deliver_subject": "_INBOX.26GitoJ5vZyz0joszY9X1w",
    "deliver_group": "MOVER",
    "durable_name": "MOVER",
    "filter_subject": "BARN.project.move_to_scalc",
    "max_ack_pending": 1024,
    "max_deliver": -1,
    "replay_policy": "instant"
}
```
3. Use natscli to adjust the MaxAckPending: `nats con edit BARN MOVER --max-outstanding=1`
4. Restart the server
5. Check the consumer config `nats con info BARN MOVER`

#### Expected result:

The `Max Ack Pending:` has been updated to 1.

#### Actual result:

The `Max Ack Pending:` has the original value 1024.

Checking the storage, I see that the `/tmp/nats/jetstream/$G/streams/BARN/obs/MOVER/meta.inf` file did not get updated after the `edit`.

Is there any API call to make to persist the `nats con edit` ? Or should it be persisted automatically?

If you can provide me some guidance, I could try to craft a PR (somehow the `mset.store` needs to be called, but I have no idea where)

### PR DESCRIPTION
**Pull request by derekcollison**
The original design of the consumer and the subsequent storage layer did not allow for config updates.
Now that we do, we need to store the new config into our storage layer.

Signed-off-by: Derek Collison <derek@nats.io>

/cc @nats-io/core

### CODE REVIEW

File: server/filestore.go [hunk 1]
```diff
@@ -5074,6 +5074,17 @@ func encodeConsumerState(state *ConsumerState) []byte {
 	return buf[:n]
 }
 
+func (o *consumerFileStore) UpdateConfig(cfg *ConsumerConfig) error {
+	o.mu.Lock()
+	defer o.mu.Unlock()
+
+	// This is mostly unchecked here. We are assuming the uppwer layers have done sanity checking.
```
Comment (kozlovic) [inline server/filestore.go:5081]: typo: `uppwer`.

**Review by kozlovic — APPROVED** [review]
LGTM (just a typo)

File: server/filestore.go (hunk 1 above)
Comment (derekcollison) [reply server/filestore.go]: Fixed.
