### PR TITLE
fixed bad issuer check performed against account issuer instead account subject (Name)

### LINKED ISSUE #1740: user jwts that set account issuer to be same as the account public key fail authentication
an user JWT which sets "issuer_account" to be the same as the account id, gets rejected.
The server has a check for that tests signing keys and the issuer to match - however the public key for the account is set on the 'Name` field, and so the test fails rejecting the user.

### PR DESCRIPTION
**Pull request by aricart**
fixed check of user issuer against the account id (Name) - was set to Issuer instead (issuer is always an operator)
added tests

FIX #1740

/cc @nats-io/core

### CODE REVIEW

**Comment by kozlovic** [comment]
@aricart Asking @matthiashanel instead since he is more familiar with that part of the code than I am.

File: server/auth.go [hunk 1]
```diff
@@ -525,6 +525,7 @@ func (s *Server) processClientOrLeafAuthentication(c *client, opts *Options) boo
 			c.Debugf("Account JWT not signed by trusted operator")
 			return false
 		}
+		// this only executes IF there's an issuer on the Juc - otherwise the account is already
```
Comment (matthiashanel) [inline server/auth.go:528]: already what?

I know what, but seems like smth. is missing in this sentence

File: server/accounts.go [hunk 2]
```diff
@@ -2693,7 +2693,7 @@ func (a *Account) hasIssuer(issuer string) bool {
 // hasIssuerNoLock is the unlocked version of hasIssuer
 func (a *Account) hasIssuerNoLock(issuer string) bool {
 	// same issuer
```
Comment (matthiashanel) [inline server/accounts.go:2695]: change the name of the function to match its functionality?
account IsIssuing?

File: server/auth.go [hunk 3]
```diff
@@ -525,6 +525,7 @@ func (s *Server) processClientOrLeafAuthentication(c *client, opts *Options) boo
...
 		if juc.IssuerAccount != "" && !acc.hasIssuer(juc.Issuer) {
```
Comment (matthiashanel) [inline server/auth.go:529]: why go back to this from what we ended up with?

Comment (aricart) [reply server/auth.go:529]: because in the end the function that we dispatch is doing that check. Here we are propagating knowledge of an edge condition where the issuer account is set, but it also matches the account name. Let the `hasIssuer()` verification do what it does.

File: server/accounts.go (hunk 2 above)
Comment (aricart) [reply server/accounts.go:2695]: that name is correct - it is checking the issuer of the user JWT. The account has such an issuer key.

File: server/auth.go (hunk 1 above)
Comment (aricart) [reply server/auth.go]: Fixed.

File: server/accounts.go (hunk 2 above)
Comment (matthiashanel) [reply server/accounts.go]: ok

File: server/auth.go (hunk 3 above)
Comment (matthiashanel) [reply server/auth.go:529]: ok

**Review by matthiashanel — APPROVED** [review]
LGTM

**Comment by kozlovic** [comment]
Deferring to Matthias, so LGTM.

**Comment by matthiashanel** [comment]
@kozlovic I'm fine with the change
