### PR TITLE
[FIXED] Better support for distinguishedNameMatch in TLS Auth

### LINKED ISSUE #1571: RDN elements order shouldn't change when NATS server check for the authorization
NATS server changes the sequence of the DN element in the principal name of the cert while authorization. Also, it removes the <space> after the comma in the principal name string.
It should exact match of the DN  from the cert string.  And it shouldn’t remove the spaces. Please find the examples below.

Actual cert: **CN= hostname, O=company name, OU=ou, L= location, ST=state, C= country**
Using certificate subject for auth **["CN=hostname,OU=ou,O=company name,L=location,ST=state,C=country"]**
In my above example, we can see that OU and O elements got interchanged which authorization and removed spaces

And the same issue observed with DC elements as well.

Please let me know if you need any more details from my side. 
Thank you.

### PR DESCRIPTION
**Pull request by wallyqs**
This fixes an issue related to the ordering of the names from a `DN` when using TLS Authentication in the NATS Server (`tlsmap`). Currently the TLS certs auth support uses the [string representation of the RDNSequence](https://github.com/golang/go/blob/12debf4a6574c8fa521e76629f20f8ff77a35e0e/src/crypto/x509/pkix/pkix.go#L40), but it has a few limitations such as not including the domain components (`DC`) names and ignoring the ordering of the elements (https://github.com/golang/go/issues/40876). 

In order to work around this issue, we try to [avoid using strings for the comparison](https://frasertweedale.github.io/blog-redhat/posts/2019-05-28-a-dn-is-not-a-string.html) of the `pkix.Name` from a TLS cert and instead create a struct that represents the `DN` and use that to make an equality check from the [go-ldap/ldap](https://github.com/go-ldap/ldap/) library (MIT Licensed).  This check takes precedence over the previous implementation for adding the domain components from #1386 since ordering was not being respected either, and also still allow the string comparison when it exactly matches the output of the string representation of [ToRDNSequence](https://github.com/golang/go/blob/12debf4a6574c8fa521e76629f20f8ff77a35e0e/src/crypto/x509/pkix/pkix.go#L226) from Go.

 - [x] Documentation added (if applicable)
 - [x] Tests added
 - [X] Branch rebased on top of current master (`git pull --rebase origin master`)
 - [X] Changes squashed to a single commit (described [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
 - [x] Build is green in Travis CI
 - [X] You have certified that the contribution is your original work and that you license the work to the project under the [Apache 2 license](https://github.com/nats-io/gnatsd/blob/master/LICENSE)

Resolves #1571 

### Changes proposed in this pull request:

- Add portion of DN parsing library from [go-ldap](https://github.com/go-ldap/ldap/blob/63c350fc27139fd81f0caebfa9446649e8d9d276/v3/dn.go) project as an internal dependency.

/cc @nats-io/core

Signed-off-by: Waldemar Quevedo <wally@synadia.com>

### CODE REVIEW

File: internal/ldap/dn.go [hunk 1]
```diff
@@ -0,0 +1,231 @@
...
+		}
+		rdn := &RelativeDN{
+			Attributes: []*AttributeTypeAndValue{
+				{
+					Type:  typeName,
+					Value: v,
+				},
+			},
+		}
+		defer func() {
```
Comment (kozlovic) [inline internal/ldap/dn.go:70]: I know defer are cheap now, but this could have been avoided by having the for loop above going down, something like:
```
for i:=len(subject.Names)-1; i>=0; i-- {
   name := subject.Names[i]
   ..
   dn.RDNs = append(dn.RDNs, rdn)
}
```

File: internal/ldap/dn.go [hunk 2]
```diff
@@ -0,0 +1,231 @@
...
+// that uses the same set.
+func FromCertSubject(subject pkix.Name) (*DN, error) {
+	dn := &DN{
+		RDNs: make([]*RelativeDN, 0),
+	}
+	for _, name := range subject.Names {
+		oidString := name.Type.String()
+		typeName, ok := attributeTypeNames[oidString]
+		if !ok {
+			return nil, fmt.Errorf("invalid Type Name: %+v", name)
```
Comment (kozlovic) [inline internal/ldap/dn.go:56]: I know you removed the "Invalid" from staticcheck output, but I would also remove the upper case for the other words: `invalid type name: %+v`

File: internal/ldap/dn.go [hunk 3]
```diff
@@ -0,0 +1,231 @@
...
+		}
+		v, ok := name.Value.(string)
+		if !ok {
+			return nil, fmt.Errorf("invalid Type Value: %+v", v)
```
Comment (kozlovic) [inline internal/ldap/dn.go:60]: Same than above.

File: server/auth.go [hunk 4]
```diff
@@ -707,8 +706,8 @@ func (s *Server) isRouterAuthorized(c *client) bool {
 	}
 
 	if opts.Cluster.TLSMap {
-		return checkClientTLSCertSubject(c, func(user string) bool {
-			return opts.Cluster.Username == user
+		return checkClientTLSCertSubject(c, func(user string, dn *ldap.DN) (string, bool) {
```
Comment (kozlovic) [inline server/auth.go:709]: since you are not using `dn` here and to make it clear, would use ` _ *ldap.DN`

File: server/auth.go [hunk 5]
```diff
@@ -731,8 +730,8 @@ func (s *Server) isGatewayAuthorized(c *client) bool {
 
 	// Check whether TLS map is enabled, otherwise use single user/pass.
 	if opts.Gateway.TLSMap {
-		return checkClientTLSCertSubject(c, func(user string) bool {
-			return opts.Gateway.Username == user
+		return checkClientTLSCertSubject(c, func(user string, dn *ldap.DN) (string, bool) {
```
Comment (kozlovic) [inline server/auth.go:733]: since you are not using `dn` here and to make it clear, would use ` _ *ldap.DN`

File: server/auth.go [hunk 6]
```diff
@@ -781,16 +780,15 @@ func (s *Server) isLeafNodeAuthorized(c *client) bool {
 	} else if len(opts.LeafNode.Users) > 0 {
 		if opts.LeafNode.TLSMap {
 			var user *User
-			found := checkClientTLSCertSubject(c, func(u string) bool {
+			found := checkClientTLSCertSubject(c, func(u string, dn *ldap.DN) (string, bool) {
```
Comment (kozlovic) [inline server/auth.go:783]: since you are not using `dn` here and to make it clear, would use ` _ *ldap.DN`

File: internal/ldap/dn_test.go [hunk 7]
```diff
@@ -0,0 +1,212 @@
...
+		"OU=Sales+CN=J. Smith,DC=example,DC=net": {[]*RelativeDN{
+			{[]*AttributeTypeAndValue{
+				{"OU", "Sales"},
+				{"CN", "J. Smith"}}},
+			{[]*AttributeTypeAndValue{{"DC", "example"}}},
+			{[]*AttributeTypeAndValue{{"DC", "net"}}}}},
+		//
+		// "1.3.6.1.4.1.1466.0=#04024869": {[]*RelativeDN{
+		// 	{[]*AttributeTypeAndValue{{"1.3.6.1.4.1.1466.0", "Hi"}}}}},
+		// "1.3.6.1.4.1.1466.0=#04024869,DC=net": {[]*RelativeDN{
```
Comment (wallyqs) [inline internal/ldap/dn_test.go:30]: These tests omitted since we do not support parsing DNs that use BER encoding in the subject currently /cc @philpennock

File: server/auth.go [hunk 8]
```diff
@@ -647,48 +647,47 @@ func checkClientTLSCertSubject(c *client, fn func(string) bool) bool {
...
+			if match, ok := fn(u.String(), nil); ok {
+				c.Debugf("Using URI found in cert for auth [%q]", match)
 				return true
 			}
 		}
 	}
 
-	// Try to get the full RDN Sequence that includes the domain components.
-	var rdns pkix.RDNSequence
-	if _, err := asn1.Unmarshal(cert.RawSubject, &rdns); err == nil {
```
Comment (wallyqs) [inline server/auth.go:674]: I will add this back and consider removal in another release

Comment (kozlovic) [reply server/auth.go:674]: But then is that not going to "disable" the new code below (calling ldap.FromCertSubject)?

Comment (kozlovic) [reply server/auth.go:674]: Or will that be a fall through and if auth with that failed, we will still invoke the correct RDN sequence check

Comment (wallyqs) [reply server/auth.go:674]: What I went for is first try the match that has the correct order and the domain component (DC) elements, if that fails then fall through and match with the appended domain components (so not correct order) and if that fails then match the string representation without the domain components.  Eventually I think we will deprecate both last two checks only use the one with the right order to stop relying on ToRDNSequence from `pkix.Name`  /cc @philpennock

File: test/tls_test.go [hunk 9]
```diff
@@ -1261,16 +1294,96 @@ func TestTLSClientAuthWithRDNSequence(t *testing.T) {
...
+				    { user = "DC=com,DC=example,CN=*.example.com,O=NATS,OU=NATS,L=Los Angeles,ST=CA,C=US" }
+				    { user = "CN=*.example.com,OU=NATS,O=NATS,L=Los Angeles,ST=CA,C=US",
+                                        permissions = { subscribe = { deny = ">" }} }
+				  ]
+				}
+			`,
+			//
+			// C = US, ST = CA, L = Los Angeles, OU = NATS, O = NATS, CN = *.example.com, DC = example, DC = com
+			//
+			nats.ClientCert("./configs/certs/rdns/client-d.pem", "./configs/certs/rdns/client-d.key"),
```
Comment (wallyqs) [inline test/tls_test.go:1383]: This cert better matches the order that is described at #1571

File: server/auth.go (hunk 8 above)
Comment (philpennock) [reply server/auth.go:674]: Might be worth logging at some verbosity level when we do this fall-through, or if that's going to be too spammy then incrementing some varz counters.

**Review by philpennock — APPROVED** [review]

File: server/auth.go [hunk 10]
```diff
@@ -419,18 +420,39 @@ func (s *Server) processClientOrLeafAuthentication(c *client, opts *Options) boo
...
-				euser = u
-				return true
+
+				if certRDN == nil {
+					return "", false
+				}
+
+				// Look through the accounts for an RDN that is equal to the one
+				// presented by the certificate.
+				for _, usr := range users {
```
Comment (wallyqs) [inline server/auth.go:443]: Also TODO here, that we could optimize later into a map for the users
