### PR TITLE
[FIXED] JetStream: panic "could not decode consumer snapshot"

### LINKED ISSUE #2720: JetStream cluster could not decode consumer snapshot
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [ ] Included `nats-server -DV` output
 - [ ] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats-server` and affected client libraries used:
2.6.5

#### OS/Container environment:
alpine 

#### Steps or code to reproduce the issue:
- stop 1 of 3 pods
- start 1 of 3 pods

#### Expected result:
- correct start

#### Actual result:
- incorrect start

```
kubectl -n production  logs collector-event-nats-2 -c nats
[87] 2021/12/01 17:08:48.861842 [INF] Starting nats-server
[87] 2021/12/01 17:08:48.861966 [INF]   Version:  2.6.5
[87] 2021/12/01 17:08:48.861971 [INF]   Git:      [ea48105]
[87] 2021/12/01 17:08:48.861974 [INF]   Name:     collector-event-nats-2
[87] 2021/12/01 17:08:48.861989 [INF]   Node:     dcRC6Zf4
[87] 2021/12/01 17:08:48.861992 [INF]   ID:       NBPSM6UJMEPOKF6FNJODGZX2YDULV3L7NVNK4RNXECA72OE467G27VDD
[87] 2021/12/01 17:08:48.861998 [INF] Using configuration file: /etc/nats-config/nats.conf
[87] 2021/12/01 17:08:48.863486 [INF] Starting JetStream
[87] 2021/12/01 17:08:48.863829 [INF]     _ ___ _____ ___ _____ ___ ___   _   __  __
[87] 2021/12/01 17:08:48.863846 [INF]  _ | | __|_   _/ __|_   _| _ \ __| /_\ |  \/  |
[87] 2021/12/01 17:08:48.863848 [INF] | || | _|  | | \__ \ | | |   / _| / _ \| |\/| |
[87] 2021/12/01 17:08:48.863850 [INF]  \__/|___| |_| |___/ |_| |_|_\___/_/ \_\_|  |_|
[87] 2021/12/01 17:08:48.863851 [INF] 
[87] 2021/12/01 17:08:48.863853 [INF]          https://docs.nats.io/jetstream
[87] 2021/12/01 17:08:48.863854 [INF] 
[87] 2021/12/01 17:08:48.863856 [INF] ---------------- JETSTREAM ----------------
[87] 2021/12/01 17:08:48.863869 [INF]   Max Memory:      512.00 MB
[87] 2021/12/01 17:08:48.863872 [INF]   Max Storage:     50.00 GB
[87] 2021/12/01 17:08:48.863875 [INF]   Store Directory: "/data/jetstream"
[87] 2021/12/01 17:08:48.863876 [INF] -------------------------------------------
[87] 2021/12/01 17:08:48.870153 [INF]   Restored 0 messages for stream "error-collector"
[87] 2021/12/01 17:08:56.299199 [INF]   Restored 5,019,337 messages for stream "event-collector"
[87] 2021/12/01 17:09:08.709647 [INF]   Restored 5,184,221 messages for stream "request-collector"
[87] 2021/12/01 17:09:08.709714 [INF]   Recovering 1 consumers for stream - "error-collector"
[87] 2021/12/01 17:09:08.710007 [INF]   Recovering 1 consumers for stream - "event-collector"
[87] 2021/12/01 17:09:08.710163 [INF]   Recovering 1 consumers for stream - "request-collector"
[87] 2021/12/01 17:09:08.710383 [INF] Starting JetStream cluster
[87] 2021/12/01 17:09:08.710387 [INF] Creating JetStream metadata controller
[87] 2021/12/01 17:09:08.710598 [INF] JetStream cluster recovering state
[87] 2021/12/01 17:09:08.712197 [INF] Starting http monitor on 0.0.0.0:8222
[87] 2021/12/01 17:09:08.712280 [INF] Listening for client connections on 0.0.0.0:4222
[87] 2021/12/01 17:09:08.712503 [INF] Server is ready
[87] 2021/12/01 17:09:08.712522 [INF] Cluster name is nats
[87] 2021/12/01 17:09:08.712548 [INF] Listening for route connections on 0.0.0.0:6222
[87] 2021/12/01 17:09:08.716585 [INF] 10.244.243.194:6222 - rid:22 - Route connection created
[87] 2021/12/01 17:09:08.716643 [INF] 10.244.69.177:6222 - rid:23 - Route connection created
[87] 2021/12/01 17:09:08.753549 [WRN] Error applying entries to '$G > event-collector': last sequence mismatch
[87] 2021/12/01 17:09:08.768254 [WRN] Resetting stream cluster state for '$G > event-collector'
[87] 2021/12/01 17:09:08.795096 [WRN] Error applying entries to '$G > event-collector': last sequence mismatch
[87] 2021/12/01 17:09:08.797944 [ERR] JetStream cluster could not decode consumer snapshot for '$G > request-collector > request-collector-1' [C-R3F-XO5nmQ6F]
panic: corrupt state file

goroutine 179 [running]:
github.com/nats-io/nats-server/server.(*jetStream).applyConsumerEntries(0xc000162160, 0xc000625500, 0xc00059e4c0, 0x0, 0x5, 0x1)
        /home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:3037 +0xe6f
github.com/nats-io/nats-server/server.(*jetStream).monitorConsumer(0xc000162160, 0xc000625500, 0xc00067eab0)
        /home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:3006 +0x68f
github.com/nats-io/nats-server/server.(*jetStream).processClusterCreateConsumer.func1()
        /home/travis/gopath/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:2800 +0x3c
created by github.com/nats-io/nats-server/server.(*Server).startGoRoutine
        /home/travis/gopath/src/github.com/nats-io/nats-server/server/server.go:2867 +0xc5

```

### PR DESCRIPTION
**Pull request by kozlovic**
Resolves #2720

Signed-off-by: Ivan Kozlovic <ivan@synadia.com>

### CODE REVIEW

File: server/filestore.go [hunk 1]
```diff
@@ -5348,11 +5348,14 @@ func decodeConsumerState(buf []byte) (*ConsumerState, error) {
 				dseq = readSeq()
 			}
 			ts := readTimeStamp()
-			if sseq == 0 || ts == -1 {
+			if ts == -1 {
 				return nil, errCorruptState
 			}
 			// Adjust seq back.
 			sseq += state.AckFloor.Stream
+			if sseq == 0 {
```
Comment (kozlovic) [inline server/filestore.go:5356]: @derekcollison I don't know if `dseq == 0` is valid or not. If not valid, then this test could be moved down few lines with `if sseq == 0 || dseq == 0 { return nil, errCorruptState}`

Comment (derekcollison) [reply server/filestore.go:5356]: Stream and Consumer can only be 0 with no activity at all, they are 1s based meaning the first message for a stream and a consumer is always 1.

**Review by derekcollison — APPROVED** [review]
LGTM

File: server/filestore.go (hunk 1 above)
Comment (kozlovic) [reply server/filestore.go:5356]: Sorry, not sure I understand. Should we check for both sseq and dseq == 0 meaning corrupt state or not? You wrote "stream and consumer can only be 0 with no activity at all", but that does not tell me if it is possible to have a consumer state with those values at 0. Seem to me that it is not since I believe that stream sequence (and therefore consumer?) starts at 1, and there can't be a *pending* with sseq/dseq == 0, right?

Comment (derekcollison) [reply server/filestore.go:5356]: Just sseq
