### PR TITLE
[FIXED] Reduce memory usage on routes

### LINKED ISSUE #1082: memory increase in clustered mode
This is a follow on from https://github.com/nats-io/nats-server/issues/1065

While looking into the above issue I noticed memory growth, we wanted to focus on one issue at a time so with 1065 done I looked at the memory situation.  The usage patterns and so forth is identical to 1065.

12 hours

Above is 12 hours, now as you know I embed your broker into one of my apps and I run a bunch of things in there.  However in order to isolate the problem I did a few things:

1. Same version of everything with the same usage pattern on a single unclustered broker does not show memory growth
1. Turning off all the related feature in my code where I embed nats-server when clustered I still see the growth
1. I made my code respond to SIGQUIT to write memory profiles on demand so I can interrogate a running nats server

The nats-server is `github.com/nats-io/nats-server/v2                                 v2.0.3-0.20190723153225-9cf534bc5e97`

From above memory dumps when comparing 6 hours apart dumps I see:

8am:
```
(pprof) top10
Showing nodes accounting for 161.44MB, 90.17% of 179.04MB total
Dropped 66 nodes (cum <= 0.90MB)
Showing top 10 nodes out of 51
      flat  flat%   sum%        cum   cum%
   73.82MB 41.23% 41.23%    73.82MB 41.23%  github.com/nats-io/nats-server/v2/server.(*client).queueOutbound
   29.18MB 16.30% 57.53%    29.68MB 16.58%  github.com/nats-io/nats-server/v2/server.(*Server).createClient
   19.60MB 10.95% 68.48%    19.60MB 10.95%  math/rand.NewSource
   15.08MB  8.42% 76.90%   140.30MB 78.37%  github.com/nats-io/nats-server/v2/server.(*client).readLoop
    6.50MB  3.63% 80.53%       12MB  6.70%  github.com/nats-io/nats-server/v2/server.(*client).processSub
    5.25MB  2.93% 83.46%    11.25MB  6.28%  github.com/nats-io/nats-server/v2/server.(*Sublist).Insert
    4.01MB  2.24% 85.70%    65.85MB 36.78%  github.com/nats-io/nats-server/v2/server.(*client).processInboundClientMsg
    3.50MB  1.95% 87.65%     3.50MB  1.95%  github.com/nats-io/nats-server/v2/server.newLevel
    2.50MB  1.40% 89.05%     2.50MB  1.40%  github.com/nats-io/nats-server/v2/server.newNode
       2MB  1.12% 90.17%        2MB  1.12%  github.com/nats-io/nats-server/v2/server.(*client).addSubToRouteTargets
```

1pm

```
(pprof) top10
Showing nodes accounting for 185.64MB, 90.87% of 204.29MB total
Dropped 69 nodes (cum <= 1.02MB)
Showing top 10 nodes out of 46
      flat  flat%   sum%        cum   cum%
   86.33MB 42.26% 42.26%    86.33MB 42.26%  github.com/nats-io/nats-server/v2/server.(*client).queueOutbound
   30.19MB 14.78% 57.04%    30.69MB 15.02%  github.com/nats-io/nats-server/v2/server.(*Server).createClient
   25.75MB 12.60% 69.64%   165.05MB 80.79%  github.com/nats-io/nats-server/v2/server.(*client).readLoop
   19.60MB  9.59% 79.24%    19.60MB  9.59%  math/rand.NewSource
    6.50MB  3.18% 82.42%    12.55MB  6.14%  github.com/nats-io/nats-server/v2/server.(*client).processSub
    5.25MB  2.57% 84.99%    11.25MB  5.51%  github.com/nats-io/nats-server/v2/server.(*Sublist).Insert
    4.02MB  1.97% 86.95%    73.70MB 36.08%  github.com/nats-io/nats-server/v2/server.(*client).processInboundClientMsg
    3.50MB  1.71% 88.67%     3.50MB  1.71%  github.com/nats-io/nats-server/v2/server.newLevel
    2.50MB  1.22% 89.89%     2.50MB  1.22%  github.com/nats-io/nats-server/v2/server.newNode
       2MB  0.98% 90.87%        2MB  0.98%  github.com/nats-io/nats-server/v2/server.(*client).addSubToRouteTargets
```

### PR DESCRIPTION
**Pull request by kozlovic**
When a route receives a message, it uses a thread local cache to
find the account and subscriptions match for a given subject.
When not found, an entry is added to this cache. The problem is
that this cache will reference subscriptions that in turn
reference connections.
When the subscriptions/connections are closed, this thread local
cannot be purged from those closed subscriptions (since it is
thread local - no locking is used).
The real issue is that connection's buffer was not set to nil on
close, which then could cause more than expected memory to be
still referenced. Setting the buffer to nil will help reduce the
memory being used.
When an entry is added to the cache, the cache may reach a size
that will cause the server to prune some entries. From time to
time, the cache will be scanned to look for entries that contain
only closed subscriptions and remove those.

Resolves #1082

Signed-off-by: Ivan Kozlovic <ivan@synadia.com>

### CODE REVIEW

File: server/client.go [hunk 1]
```diff
@@ -298,8 +299,15 @@ type readCache struct {
 }
 
 const (
-	maxPerAccountCacheSize   = 32768
-	prunePerAccountCacheSize = 512
+	defaultMaxPerAccountCacheSie    = 4096
```
Comment (derekcollison) [inline server/client.go]: Sie -> Size

File: server/client.go [hunk 2]
```diff
@@ -333,17 +341,29 @@ func (c *client) GetTLSConnectionState() *tls.ConnectionState {
...
 	subject []byte
 	queue   []byte
 	sid     []byte
-	nm      int64
 	max     int64
 	qw      int32
 }
 
+// Indicate that this subscription is closed.
+// This is used in pruning of some cache.
```
Comment (derekcollison) [inline server/client.go]: pruning of route cache items.

File: server/client.go [hunk 3]
```diff
@@ -685,9 +705,13 @@ func (c *client) writeLoop() {
 		c.mu.Unlock()
 
 		if isClosed {
-			return
+			break
 		}
 	}
+
+	c.mu.Lock()
+	c.out.p, c.out.s = nil, nil
```
Comment (derekcollison) [inline server/client.go]: Can move this to where we set the isClosed bool to avoid the second lock/unlock.

File: server/client.go [hunk 4]
```diff
@@ -735,6 +759,7 @@ func (c *client) readLoop() {
 	nc := c.nc
 	s := c.srv
 	c.in.rsz = startBufSize
+	c.in.losc = time.Now().UnixNano()
```
Comment (derekcollison) [inline server/client.go]: Can be second resolution yes? We would not do sub-second would we?

File: server/client.go [hunk 5]
```diff
@@ -751,6 +776,12 @@ func (c *client) readLoop() {
 		return
 	}
 
+	defer func() {
```
Comment (derekcollison) [inline server/client.go]: Why do we need to do here as a defer?

File: server/client.go [hunk 6]
```diff
@@ -281,6 +281,7 @@ type readCache struct {
 
 	// This is for routes and gateways to have their own L1 as well that is account aware.
 	pacache map[string]*perAccountCache
+	losc    int64 // last orphan subs check
```
Comment (derekcollison) [inline server/client.go]: Why not just a time.Time?

File: server/client.go [hunk 7]
```diff
@@ -3192,10 +3225,40 @@ func (c *client) Account() *Account {
 // prunePerAccountCache will prune off a random number of cache entries.
 func (c *client) prunePerAccountCache() {
 	n := 0
-	for cacheKey := range c.in.pacache {
-		delete(c.in.pacache, cacheKey)
-		if n++; n > prunePerAccountCacheSize {
-			break
+	if time.Now().UnixNano()-c.in.losc >= int64(orphanSubsCheckInterval) {
```
Comment (derekcollison) [inline server/client.go]: Make simple time.Time?

File: server/client.go [hunk 8]
```diff
@@ -3192,10 +3225,40 @@ func (c *client) Account() *Account {
...
+		for cacheKey, pac := range c.in.pacache {
+			canRemove := true
```
Comment (derekcollison) [inline server/client.go]: If we have any sub or qsub as part of a result that has been closed we can invalidate the result and delete the whole thing. It will come back properly if used again.

File: server/client.go (hunk 1 above)
Comment (kozlovic) [reply server/client.go]: ok

File: server/client.go (hunk 2 above)
Comment (kozlovic) [reply server/client.go]: and gateway..

Comment (derekcollison) [reply server/client.go]: Same cache?

Comment (kozlovic) [reply server/client.go]: Same structure, but each route/gateway connection has its own.

File: server/client.go (hunk 3 above)
Comment (kozlovic) [reply server/client.go]: I would rather do this here once when the connection is closed, than having to check isClosed (twice) at each loop iteration, no?

File: server/client.go (hunk 4 above)
Comment (kozlovic) [reply server/client.go]: In tests.. using 1sec is likely to cause to wait closer than 2 sec instead.. will make the test that check this one a bit longer..

File: server/client.go (hunk 5 above)
Comment (kozlovic) [reply server/client.go]: because readLoop has 4 returns. Again, this is a one time event when connection is closed.

Comment (derekcollison) [reply server/client.go]: ok

Comment (kozlovic) [reply server/client.go]: could replace `return` statements with `break` and do this at end of loop. Hopefully people working on readLoop code won't add returns in middle (although this is not dramatic if this is not set to nil, just helps).

File: server/client.go (hunk 6 above)
Comment (kozlovic) [reply server/client.go]: time.Time is 24 bytes...

File: server/client.go (hunk 7 above)
Comment (kozlovic) [reply server/client.go]: 24 bytes... I thought we were trying to put things on a diet ;-)

File: server/client.go (hunk 8 above)
Comment (kozlovic) [reply server/client.go]: True.. it is a cache and ok to remove even when valid. I will change that.

File: server/client.go (hunk 4 above)
Comment (derekcollison) [reply server/client.go]: ok, maybe just do time.Time here.

File: server/client.go (hunk 5 above)
Comment (derekcollison) [reply server/client.go]: Can we clear these in closeConnection (or clearConnection)?

File: server/client.go (hunk 7 above)
Comment (derekcollison) [reply server/client.go]: hmm, good point.

File: server/client.go (hunk 5 above)
Comment (kozlovic) [reply server/client.go]: No, it would not be safe because these are used in readLoop without lock and so should not be cleared from any other thread.

Comment (derekcollison) [reply server/client.go]: ok

File: server/client.go (hunk 7 above)
Comment (kozlovic) [reply server/client.go]: So keeping the way it is then?

File: server/client.go (hunk 3 above)
Comment (kozlovic) [reply server/client.go]: Please confirm if ok to do it at end of loop like this or want me to check in the loop.

File: server/client.go (hunk 7 above)
Comment (derekcollison) [reply server/client.go]: I think just Unix() no? Why Nano?

File: server/client.go (hunk 3 above)
Comment (derekcollison) [reply server/client.go]: I would check in the loop.

File: server/client.go (hunk 7 above)
Comment (kozlovic) [reply server/client.go]: so that we can use less than 1sec.. Remember the jwt expiration tests flapping tests? I can do it, but then understand that test around this will have to be slower.

File: server/client.go (hunk 3 above)
Comment (kozlovic) [reply server/client.go]: ok...

File: server/client.go (hunk 7 above)
Comment (derekcollison) [reply server/client.go]: I understand, but I don't think setting it sub-second make sense which this suggest we can do. But we only do it for tests.

**Comment by kozlovic** [comment]
@derekcollison Please have another look to see if I have addressed all your concerns.

File: server/client.go [hunk 9]
```diff
@@ -3225,33 +3224,35 @@ func (c *client) Account() *Account {
...
+	now := time.Now().Unix()
+	if now-c.in.losc >= orphanSubsCheckInterval {
 		for cacheKey, pac := range c.in.pacache {
-			canRemove := true
+			remove := false
 			for _, sub := range pac.results.psubs {
-				if !sub.isClosed() {
-					canRemove = false
+				if sub.isClosed() {
+					remove = true
```
Comment (derekcollison) [inline server/client.go]: I would just delete here and continue instead of tracking the remove boolean etc.

Comment (kozlovic) [reply server/client.go]: there are several level of loops, so continue would just move to next psub (or qsub). What you want is continue the outer loop. I could use labels and gotos, but the code to remove (delete, n++) will have to be copied 3 times. Is that ok?

Comment (kozlovic) [reply server/client.go]: ok, goto label REMOVE at the end that removes and a continue before that label.. will submit and tell me if that's what you had in mind.
