### PR TITLE
[FIXED] Unnecessary account reloads

### LINKED ISSUE #1372: configuration reload that changes the system account does not take effect everywere
The reason for this is that config reload recreates all accounts including the system account  but does not change the pointer server.sys.account and it's copy server.sys.client.acc (taken by internalSendLoop).

Below config change changes the field to from CONNECT to DISCONNECT, then calls reload.
While the server is running, the change does not take effect.

As far as I can tell, JWT code actually updates the account instead of creating a new one.
I don't think we should allow modifying the system account.
While the config may seem contrived for now, it's hard to say that the pointer in question will always remain being used this way. Meaning future usages of c.acc may introduce another problem.

With the below config before and after reload, this subscriber will only receive the CONNECT event. `nats -s nats://user:pwd@localhost:4222 sub ">"`

Config before/after reload
```bash
> cat test.cfg
listen: localhost:4222
accounts: {
    USERS {
        users: [
            {user: "user", password: "pwd"}
        ]
        exports: [{service: "test"}]
    },
    SYS: {
        users: [
            {user: admin, password: changeit}
        ]
        imports: [
            {service: {account: USERS, subject: "test"}, to: "$SYS.ACCOUNT.USERS.CONNECT"},
        ]
    },
}
system_account: SYS
> vi test.cfg
> nats-server --signal reload
> cat test.cfg
listen: localhost:4222
accounts: {
    USERS {
        users: [
            {user: "user", password: "pwd"}
        ]
        exports: [{service: "test"}]
    },
    SYS: {
        users: [
            {user: admin, password: changeit}
        ]
        imports: [
            {service: {account: USERS, subject: "test"}, to: "$SYS.ACCOUNT.USERS.DISCONNECT"},
        ]
    },
}
system_account: SYS
>
```

### PR DESCRIPTION
**Pull request by matthiashanel**
Fixes #1372 by updating s.sys.account pointer.

This issue also showed that accounts are unnecessarily reloaded.
This happened because account imports were not copied and thus,
deepEqual detected a difference were none was.
This was addressed by making the copy less shallow.

Furthermore did deepEqual detects a difference when it compared 
slices that were appended to while processing a map.
This was fixed by sorting before comparison.

Noticed that Account.clients stored an unnecessary pointer.
Removed duplicated code in systemAccount.

Signed-off-by: Matthias Hanel <mh@synadia.com>

I did not outright eliminate sys.account pointer as we do not necessarily always have a name that is specified.

### CODE REVIEW

File: server/events.go [hunk 1]
```diff
@@ -64,22 +64,23 @@ var eventsHBInterval = 30 * time.Second
...
+	client    *client
+	seq       uint64
+	sid       uint64
+	servers   map[string]*serverUpdate
+	sweeper   *time.Timer
+	stmr      *time.Timer
+	subs      map[string]msgHandler
+	replies   map[string]msgHandler
+	sendq     chan *pubMsg
+	resetChan chan struct{}
```
Comment (kozlovic) [inline server/events.go:77]: `resetCh` may have been enough?

File: server/events.go [hunk 2]
```diff
@@ -618,13 +623,17 @@ func (s *Server) initEventTracking() {
...
-	sacc := s.sys.account
-
 	// This is for simple debugging of number of subscribers that exist in the system.
 	if _, err := s.sysSubscribeInternal(accSubsSubj, s.debugSubscribers); err != nil {
 		s.Errorf("Error setting up internal debug service for subscribers: %v", err)
 	}
+}
+
+// add all exports a system account will need
+func (s *Server) addSystemAccountExports(sacc *Account) {
```
Comment (kozlovic) [inline server/events.go:633]: Since we call eventsEnabled(), caller needs to have s.mu.Lock(). If that is the case, maybe add comment:
```
// Server lock held on entry
```
at top of this function.

File: server/events.go [hunk 3]
```diff
@@ -289,6 +292,8 @@ func (s *Server) internalSendLoop(wg *sync.WaitGroup) {
 				c.flushClients(time.Second)
 				return
 			}
+		case <-resetChan:
+			goto RESET
```
Comment (kozlovic) [inline server/events.go:296]: A close() of the this channel would then cause this function to go back to RESET, which is kind of useless since we are likely close s.quitCh too. 
Note that you can check that the channel was not actually closed:
```
case _, ok := <-resetChan:
  if ok {
      goto RESET
  }
```

File: server/server.go [hunk 4]
```diff
@@ -507,8 +507,17 @@ func (s *Server) configureAccounts() error {
...
 		// Lock may be acquired in lookupAccount, so release to call lookupAccount.
 		s.mu.Unlock()
-		_, err := s.lookupAccount(opts.SystemAccount)
+		acc, err := s.lookupAccount(opts.SystemAccount)
 		s.mu.Lock()
+		if err == nil && s.sys != nil && acc != s.sys.account {
+			// sys.account.clients (including internal client)/respmap/etc... are transferred separately
+			s.sys.account = acc
+			s.addSystemAccountExports(acc)
+			// can't hold the lock as go routine reading it may be waiting for lock as well
```
Comment (kozlovic) [inline server/server.go:516]: That's fine though, meaning that you can send to this channel under the server lock. The internalSendLoop will pick up the change when the server lock is released (if loop is blocked trying to grab the server lock).
Even the way you do it here (releasing the lock, sending, then reacquiring) does not guarantee that the internalSendLoop will have time to refresh in that interval.

File: server/events.go (hunk 3 above)
Comment (matthiashanel) [reply server/events.go:296]: In the case you describe the go routine would start to spin. 
In either case close has to happen after s.sys.wg.Wait().

File: server/events.go (hunk 2 above)
Comment (matthiashanel) [reply server/events.go:633]: will add

File: server/events.go (hunk 1 above)
Comment (matthiashanel) [reply server/events.go:77]: will rename

File: server/server.go (hunk 4 above)
Comment (matthiashanel) [reply server/server.go:516]: This is a blocking channel as I want the go routine to return from reload when the update is already started, not a lot earlier.
My understanding of blocking channels is that both go routines have to be using the channel in order to make progress. 
However I am holding a lock and so, if the other go routine is waiting for the lock  it will never get to the receiving part.

File: server/events.go (hunk 2 above)
Comment (matthiashanel) [reply server/events.go:633]: Actually this was a result of moving the code out of initEventTracking, no lock held there either. I'll change it to EventsEnabled

File: server/server.go (hunk 4 above)
Comment (kozlovic) [reply server/server.go:516]: You can create the channel buffered (size1): `make(chan struct{}, 1)` and you should send using a select:
```
select {
  case s.sys.resetCh <- struct{}{}:
  default:
}
```

File: server/events.go (hunk 3 above)
Comment (kozlovic) [reply server/events.go:296]: You are right. Since we close the quitCh first and then wait on wg.Wait(), it is fine to leave the wait it is in the PR.

File: server/server.go (hunk 4 above)
Comment (kozlovic) [reply server/server.go:516]: We discussed and ok, you at least guarantee that all sys messages using the old one have been sent.

**Comment by matthiashanel** [comment]
@kozlovic , incorporated your comments. added waiting for disconnect event to unit test and moved to single re-lock in configureAccounts.

File: server/reload_test.go [hunk 5]
```diff
@@ -4155,3 +4155,156 @@ func TestReloadValidate(t *testing.T) {
...
+	urlUsr := fmt.Sprintf("nats://usr:pwd@%s:%d", o.Host, o.Port)
+	oldAcc, ok := s.accounts.Load("SYS")
+	if !ok {
+		t.Fatal("No SYS account")
+	}
+
+	testSrvState := func(oldAcc interface{}) {
+		sysAcc := s.SystemAccount()
+		s.mu.Lock()
+		fatal := func() string {
```
Comment (kozlovic) [inline server/reload_test.go:4195]: You should have the defer s.mu.Unlock() for this test function. If there is an error, you would return without the unlock and the test would probably "stall" due to a deadlock (not reporting the actual error)

File: server/server.go [hunk 6]
```diff
@@ -505,11 +505,29 @@ func (s *Server) configureAccounts() error {
...
+		}
+		// Lock may be acquired in lookupAccount and addSystemAccountExports, so release to call lookupAccount.
 		s.mu.Unlock()
-		_, err := s.lookupAccount(opts.SystemAccount)
+		acc, err := s.lookupAccount(opts.SystemAccount)
+		if err == nil && acc != oldAcc {
+			s.addSystemAccountExports(acc)
+			// can't hold the lock as go routine reading it may be waiting for lock as well
+			if resetCh != nil {
+				resetCh <- struct{}{}
```
Comment (kozlovic) [inline server/server.go:521]: But I don't understand, you notify here, but we set s.sys.account = acc after reacquiring the lock. So there is a chance that the internal send loop "goto RESET" before the system account is updated, no?

File: server/reload_test.go (hunk 5 above)
Comment (matthiashanel) [reply server/reload_test.go:4195]: I used a closure so this wouldn't happen, but you are right, defer is much better.

File: server/server.go (hunk 6 above)
Comment (matthiashanel) [reply server/server.go:521]: Yes you are right. will go back to two relock.
