### PR TITLE
[FIXED] #2401

### LINKED ISSUE #2401: When two server are connected via leaf node and both have JS enabled and domain set to the same value, JS is currently not extended
It would be expected that they behave as if domain where not set at all.
Meaning they should be part of the same meta group.

### PR DESCRIPTION
**Pull request by derekcollison**
Leafnodes with same domain and shared system account should behave like flat jetstream network.

Signed-off-by: Derek Collison <derek@nats.io>

Resolves #2401 

/cc @nats-io/core

### CODE REVIEW

**Review by matthiashanel — APPROVED** [review]
LGTM

File: server/jetstream_cluster_test.go [hunk 1]
```diff
@@ -6615,6 +6615,21 @@ func TestJetStreamClusterLeafNodesWithoutJS(t *testing.T) {
...
+func TestJetStreamClusterLeafNodesWithSameDomainNames(t *testing.T) {
+	tmpl := strings.Replace(jsClusterAccountsTempl, "store_dir:", "domain: HUB, store_dir:", 1)
+	c := createJetStreamCluster(t, tmpl, "HUB", _EMPTY_, 3, 11233, true)
+	defer c.shutdown()
+
+	tmpl = strings.Replace(jsClusterTemplWithLeafNode, "store_dir:", "domain: HUB, store_dir:", 1)
+	lnc := c.createLeafNodesWithTemplateAndStartPort(tmpl, "SPOKE", 3, 11311)
+	defer lnc.shutdown()
+
+	//lncm := c.createLeafNodesWithTemplateMixedMode(tmpl, "SPOKE", 3, 2, true)
```
Comment (kozlovic) [inline server/jetstream_cluster_test.go:6627]: Remove?

File: server/leafnode.go [hunk 2]
```diff
@@ -1057,7 +1058,7 @@ func (c *client) processLeafnodeInfo(info *Info) {
 						c.Debugf("Error adding JetStream domain mapping: %v", err)
 					}
 				}
-			} else if hasJSDomain {
+			} else if hasJSDomain && opts.JetStreamDomain != info.Domain {
```
Comment (kozlovic) [inline server/leafnode.go:1061]: Do we need to treat `info.Domain` possibly empty (old server?) differently here or not?

**Review by kozlovic — APPROVED** [review]
LGTM but not sure if info.Domain empty should be treated differently.

File: server/jetstream_cluster_test.go (hunk 1 above)
Comment (derekcollison) [reply server/jetstream_cluster_test.go:6627]: Yes will update.

File: server/leafnode.go (hunk 2 above)
Comment (derekcollison) [reply server/leafnode.go:1061]: No for this one we want both empty or exact match.
