### PR TITLE
[FIXED] JetStream: issue with max deliver and server/cluster restart

### LINKED ISSUE #3361: Zombie re-deliveries
## Defect

If you have a durable consumer with explicit ack and some message reached the maximum number of delivery attempts, if you restart the nats-server then the server tries again to re-deliver those messages.

2.8.4

#### Steps or code to reproduce the issue:

Create a storage=file stream and a durable (push or pull), start a subscriber on that consumer that doesn't acknowledge messages (e.g. `nats sub --no-akc` or `nats consumer next --no-ack`) publish a message into the stream and see that the message is delivered only n times (n = max deliveries), after that is over, stop and restart the nats-server(s) and after that restart the server attempts to deliver that message again.

### PR DESCRIPTION
**Pull request by kozlovic**
This is a regression introduced in v2.8.3. If a message reaches
the max redeliver count, it stops being delivered to the consumer.
However, after a server or cluster restart, those messages would
be redelivered again.

Resolves #3361

Signed-off-by: Ivan Kozlovic <ivan@synadia.com>

### CODE REVIEW

**Review by derekcollison — APPROVED** [review]
LGTM

**Comment by kozlovic** [comment]
@derekcollison I am seeing that the cluster test is flapping, so will investigate more. Not merging at this time until I figure out if it is test timing or something more.

File: server/norace_test.go [hunk 1]
```diff
@@ -3561,6 +3561,9 @@ func TestNoRaceJetStreamClusterCorruptWAL(t *testing.T) {
 		t.Fatalf("Error looking up consumer %q", "dlc")
 	}
 	// Grab underlying raft node and the WAL (filestore) and we will attempt to "corrupt" it.
+	o.mu.Lock()
+	o.skipSnapshotOnExit = true
```
Comment (derekcollison) [inline server/norace_test.go:3565]: I think I would rather pull the consumer in this test and stop the raft node directly versus having a boolean for every consumer in normal operations.

So just call o.raftNode().Stop()

**Review by derekcollison — CHANGES_REQUESTED** [review]

File: server/norace_test.go (hunk 1 above)
Comment (kozlovic) [reply server/norace_test.go]: Removed the boolean and did just that. Force pushed this commit.

**Review by derekcollison — APPROVED** [review]
LGTM
