### PR TITLE
Fix config parsing with self referencing environment variables

### LINKED ISSUE #7730: Recursive substitution of environment variables in config file causes out of memory failure.
### Observed behavior

With the following environment variables:

```env
EXAMPLE_ROUTES='$EXAMPLE_ROUTES'
```

And the following routes configuration:

```conf
// --snip--

cluster {
    // --snip--

    routes = [
        $EXAMPLE_ROUTES
    ]

    // --snip--
}
```

It seems that $EXAMPLE_ROUTES is recursively substituted until the process is killed due to an out of memory exception.

### Expected behavior

Ideally, there would be some mechanism to catch recursive substitution and give an informative error.

### Server and client version

3.23.2

### Host environment

_No response_

### Steps to reproduce

_No response_

### PR DESCRIPTION
**Pull request by sciascid**
The config parser allows for environment variables to reference other environment variables. However, self references or cycles would cause the parser to enter an infinite recursion.

This commit introduces cycle detection in the environment variable lookup process, so that the parser handles cycles and self-references gracefully.
A set of tests check that the current behavior of the parser did not change:

    - variables can reference other variables, as well as environment variables
    - environment variables can reference other evironment variables, but not local variables

Fixes #7730

Signed-off-by: Daniele Sciascia <daniele@nats.io>

### CODE REVIEW

File: server/opts_test.go [hunk 1]
```diff
@@ -4180,3 +4180,130 @@ func TestWebsocketPingIntervalConfig(t *testing.T) {
...
+	if err == nil {
+		t.Fatalf("Expected an error")
+	}
+	require_Contains(t, err.Error(), "variable reference cycle")
+}
+
+// Test an environment variable that references itself through a cycle
+func TestEnvVarReferencesSelfCycle(t *testing.T) {
+	confFileName := createConfFile(t, []byte(`
+		TEST: $_TEST_ENV_A_
```
Comment (wallyqs) [inline server/opts_test.go:4294]: I think might be fine, but maybe add a few tests to check what happens with `include` just in case?

Comment (sciascid) [reply server/opts_test.go:4294]: Added a test to include from environment variable. Such attempts produce an error, which is the right thing to do, in my opinion.
Did you have something else in mind?

Comment (wallyqs) [reply server/opts_test.go:4294]: ah I was thinking more like, you create two files then call `include` from one to load the definitions from the other

Comment (sciascid) [reply server/opts_test.go:4294]: done
