### PR TITLE
[FIXED] Fix for server panic when consumer state was not decoded correctly.

### LINKED ISSUE #3535: After lot of restart due to oom nats panic: corrupt state file
## Defect
On nats cluster affected by 
[https://github.com/nats-io/nats-server/issues/3517](https://github.com/nats-io/nats-server/issues/3517)
afer 1115 restarts on container nats server panic on start.

#### Versions of `nats-server` and affected client libraries used:
[56] 2022/10/10 11:11:13.961798 [INF] Starting nats-server
[56] 2022/10/10 11:11:13.961853 [INF]   Version:  2.9.3-beta.1
[56] 2022/10/10 11:11:13.961859 [INF]   Git:      [cb086bce]
[56] 2022/10/10 11:11:13.961863 [DBG]   Go build: go1.19.1
#### OS/Container environment:
AWS EKS 
#### Steps or code to reproduce the issue:
start 3x nats cluster, with slow disks, create jetstream with file storage and 3 replicas. Push more data than disk are able consume, until nats write disk cache cause container to OOM. Since that nats cluster is in OOM loop after while data on disk are corrupted and nats panic.
#### Expected result:
nats and try to recover from last state
#### Actual result:

nats fail to start:
[142] 2022/10/10 11:00:45.333410 [DBG] Exiting consumer monitor for '$G > STX_SERVER_DATA > DB_SERVICE' [C-R3F-OuTvxCQ0]
panic: corrupt state file

goroutine 51 [running]:
github.com/nats-io/nats-server/v2/server.(*jetStream).applyConsumerEntries(0xc00024c000, 0xc000262d80, 0x0?, 0x0)
	/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:3992 +0x816
github.com/nats-io/nats-server/v2/server.(*jetStream).monitorConsumer(0xc00024c000, 0xc000262d80, 0xc000251680)
	/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:3871 +0xdc6
github.com/nats-io/nats-server/v2/server.(*jetStream).processClusterCreateConsumer.func1()
	/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/jetstream_cluster.go:3585 +0x25
created by github.com/nats-io/nats-server/v2/server.(*Server).startGoRoutine
	/home/runner/work/nats-server/src/github.com/nats-io/nats-server/server/server.go:3077 +0x85

### PR DESCRIPTION
**Pull request by derekcollison**
The bug was when a timestamp for the pending state was exactly -1 which could happen based on timing of the redlivered pending items which would set pending.Timestamp into the future potentially and the timing on the encodeConsumerState call.

Minor fixes to raft.

Signed-off-by: Derek Collison <derek@nats.io>

Resolves #3535 

/cc @nats-io/core

### CODE REVIEW

File: server/norace_test.go [hunk 1]
```diff
@@ -5879,3 +5879,23 @@ func TestJetStreamLargeNumConsumersPerfImpact(t *testing.T) {
 	fmt.Printf("\n1000 consumers time is %v\n", tt)
 	fmt.Printf("%.0f msgs/sec\n", float64(toSend)/tt.Seconds())
 }
+
+// Bug when we encode a timestamp that upon decode causes an error which causes server to panic.
+// This can happen on consumer redelivery since they adjusted timstamps can be in the future, and result
+// in a negative encoding. If that encoding was exactly -1 seconds, would cause decodeConsumerState to fail
+// and the server to panic.
+func TestEncodeConsumerStateBug(t *testing.T) {
```
Comment (derekcollison) [inline server/norace_test.go:5887]: NoRace Pre

File: server/norace_test.go [hunk 2]
```diff
@@ -5879,3 +5879,23 @@ func TestJetStreamLargeNumConsumersPerfImpact(t *testing.T) {
...
 	fmt.Printf("%.0f msgs/sec\n", float64(toSend)/tt.Seconds())
 }
+
+// Bug when we encode a timestamp that upon decode causes an error which causes server to panic.
+// This can happen on consumer redelivery since they adjusted timstamps can be in the future, and result
+// in a negative encoding. If that encoding was exactly -1 seconds, would cause decodeConsumerState to fail
+// and the server to panic.
+func TestNoRaceEncodeConsumerStateBug(t *testing.T) {
+	for i := 0; i < 200_000; i++ {
+		// Pretend we redlivered and updated the timestamp to reflect the new start time for expiration.
```
Comment (ColinSullivan1) [inline server/norace_test.go:5889]: nitpick - typo...  redelivered

Comment (derekcollison) [reply server/norace_test.go]: Fixed - thx

**Review by ColinSullivan1 — APPROVED** [review]
LGTM.

**Review by ColinSullivan1 — APPROVED** [review]
