### PR TITLE
[FIXED] JetStream: Sources with OptStartTime gets redelivered

### LINKED ISSUE #3559: opt_start_time causing previously purged messages to be redelivered from source on server stop/start
## Defect

When adding a source to a stream and using the opt_start_time option all messages are being redelivered to the stream from the source when the server is stopped and started. 

This doesn't happen if opt_start_time is not included in the config.

#### Versions of `nats-server` and affected client libraries used:

2.9.3

#### OS/Container environment:

mac montery

#### Steps or code to reproduce the issue:

Launch 3 servers hub, aleaf & bleaf using the same config as this ticket: https://github.com/nats-io/nats-server/issues/2920

Create queue stream on a-leaf:
`nats --server nats://localhost:4111 str add --config ./queue.json`

Create test stream on b-leaf:
`nats --server nats://localhost:2111 str add --config ./test.json`

Add entries to test stream:
`nats --server nats://localhost:2111 pub test hello --count 10`

Add test as source to queue:
```nats --server nats://localhost:4111 pub '$JS.a-leaf.API.STREAM.UPDATE.queue' '{ "name": "queue", "subjects": [ "queue" ], "retention": "limits", "max_consumers": -1, "max_msgs": -1, "max_bytes": -1, "max_age": 0, "max_msgs_per_subject": -1, "max_msg_size": -1, "discard": "old", "storage": "file", "num_replicas": 1, "duplicate_window": 120000000000, "sealed": false, "deny_delete": false, "deny_purge": false, "allow_rollup_hdrs": false, "sources": [ { "name": "test", "opt_start_time": "2022-10-14T12:32:06.122Z", "external": { "api": "$JS.b-leaf.API", "deliver": "" } } ] }'```

Verify entries are in queue:
`nats --server nats://localhost:4111 str report`

Purge queue
`nats --server nats://localhost:4111 str purge`

Verify no entries are in queue:
`nats --server nats://localhost:4111 str report`

Stop and start server that has queue (a-leaf)

Report stream will show messages redelivered to stream
`nats --server nats://localhost:4111 str report`

#### Expected result:

Report shows no messages in queue after stop/start.

#### Actual result:

Messages are being redelivered from source stream.

### PR DESCRIPTION
**Pull request by kozlovic**
If start by time is before what we remember during recovery use that instead

Resolves #3559

Signed-off-by: Derek Collison <derek@nats.io>
Signed-off-by: Ivan Kozlovic <ivan@synadia.com>

### CODE REVIEW

File: server/jetstream_cluster_3_test.go [hunk 1]
```diff
@@ -1050,3 +1050,117 @@ func TestJetStreamClusterSignalPullConsumersOnDelete(t *testing.T) {
...
+		defer removeDir(t, config.StoreDir)
+	}
+	defer s.Shutdown()
+
+	c := createJetStreamClusterExplicit(t, "R3S", 3)
+	defer c.shutdown()
+
+	test := func(t *testing.T, c *cluster, s *Server) {
+
+		replicas := 1
```
Comment (derekcollison) [inline server/jetstream_cluster_3_test.go:1067]: LGTM

**Review by derekcollison — APPROVED** [review]
LGTM
