### PR TITLE
[FIXED] Route: Infinite retry cluster connection with invalid credentials

### LINKED ISSUE #7194: Infinite retry cluster connection with invalid credentials
### Observed behavior

With invalid credentials the client-cluster-server will continuously retry to connect without timeout resulting in hogging the CPU.

### Expected behavior

A configuration setting to limit this with a retry-timeout

### Server and client version

Both are on latest master d034f6484060638e4220b9cca7866bea6d830746
Version:  2.12.0-preview.1

### Host environment

Vanilla Ubuntu

### Steps to reproduce

Server config:
```
listen: 127.0.0.1:4222
cluster {
  name: clustername
  listen: 0.0.0.0:4248
  authorization {
    user: "correct" 
    password: "correct" 
    timeout: 5 
  }
}
```

client config:
```
listen: 127.0.0.1:4222
cluster {
  name: clustername
  listen: 0.0.0.0:4248
  routes = [ nats-route://incorrect:incorrect@172.149.4.123:4248 ]
}
```

client CLI output
```
# go run main.go --config nats.conf -D
[8741] 2025/08/21 14:36:42.672426 [INF] Starting nats-server
[8741] 2025/08/21 14:36:42.672464 [INF]   Version:  2.12.0-preview.1
[8741] 2025/08/21 14:36:42.672468 [INF]   Git:      [not set]
[8741] 2025/08/21 14:36:42.672470 [DBG]   Go build: go1.24.6
[8741] 2025/08/21 14:36:42.672472 [INF]   Cluster:  clustername
[8741] 2025/08/21 14:36:42.672474 [INF]   Name:     NBZKPTHPAJMEND56H24U6GMS5KV7NYSQZQYT7HBAOLF5XOQJWL5QGRWJ
[8741] 2025/08/21 14:36:42.672475 [INF]   ID:       NBZKPTHPAJMEND56H24U6GMS5KV7NYSQZQYT7HBAOLF5XOQJWL5QGRWJ
[8741] 2025/08/21 14:36:42.672480 [INF] Using configuration file: nats.conf (sha256:cc60b1377e6376ae99e8e778bb0c452f314eec3bb30f8e2a6e686401038561c3)
[8741] 2025/08/21 14:36:42.672486 [DBG] Created system account: "$SYS"
[8741] 2025/08/21 14:36:42.672832 [INF] Listening for client connections on 127.0.0.1:4222
[8741] 2025/08/21 14:36:42.672841 [INF] Server is ready
[8741] 2025/08/21 14:36:42.672906 [INF] Cluster name is clustername
[8741] 2025/08/21 14:36:42.672966 [INF] Listening for route connections on 0.0.0.0:4248
[8741] 2025/08/21 14:36:42.673012 [DBG] maxprocs: Leaving GOMAXPROCS=20: CPU quota undefined
[8741] 2025/08/21 14:36:42.673054 [DBG] Trying to connect to route on 172.149.4.123:4248 (172.149.4.123:4248)
[8741] 2025/08/21 14:36:42.673054 [DBG] Trying to connect to route on 172.149.4.123:4248 (172.149.4.123:4248)
[8741] 2025/08/21 14:36:42.673560 [DBG] 172.149.4.123:4248 - rid:5 - Route connect msg sent
[8741] 2025/08/21 14:36:42.673608 [DBG] 172.149.4.123:4248 - rid:6 - Route connect msg sent
[8741] 2025/08/21 14:36:42.673629 [INF] 172.149.4.123:4248 - rid:6 - Route connection created
[8741] 2025/08/21 14:36:42.673635 [INF] 172.149.4.123:4248 - rid:5 - Route connection created
[8741] 2025/08/21 14:36:42.674603 [DBG] 172.149.4.123:4248 - rid:5 - Registering remote route "NDM22DTJIP3CFMH42ZD45U63Z3TCA3OQOJKBMIBZXD3CJYEJ5JIVB5QL"
[8741] 2025/08/21 14:36:42.674695 [DBG] 172.149.4.123:4248 - rid:6 - Sent local subscriptions to route
[8741] 2025/08/21 14:36:42.674700 [DBG] 172.149.4.123:4248 - rid:6 - Registering remote route "NDM22DTJIP3CFMH42ZD45U63Z3TCA3OQOJKBMIBZXD3CJYEJ5JIVB5QL" for account "$SYS"
[8741] 2025/08/21 14:36:42.675054 [ERR] 172.149.4.123:4248 - rid:6 - Route Error 'Authorization Violation'
[8741] 2025/08/21 14:36:42.675064 [ERR] 172.149.4.123:4248 - rid:5 - Route Error 'Authorization Violation'
[8741] 2025/08/21 14:36:42.675061 [INF] 172.149.4.123:4248 - rid:6 - Router connection closed: Parse Error - Remote: NDM22DTJIP3CFMH42ZD45U63Z3TCA3OQOJKBMIBZXD3CJYEJ5JIVB5QL
[8741] 2025/08/21 14:36:42.675077 [INF] 172.149.4.123:4248 - rid:5 - Router connection closed: Parse Error - Remote: NDM22DTJIP3CFMH42ZD45U63Z3TCA3OQOJKBMIBZXD3CJYEJ5JIVB5QL
[8741] 2025/08/21 14:36:42.675110 [DBG] Attempting reconnect for solicited route "nats-route://ed08863a-79ce-41e1-b335-f67ed3f773a9:xxxxx@172.149.4.123:4248"
[8741] 2025/08/21 14:36:42.675121 [DBG] Attempting reconnect for solicited route "nats-route://ed08863a-79ce-41e1-b335-f67ed3f773a9:xxxxx@172.149.4.123:4248"
[8741] 2025/08/21 14:36:42.696216 [DBG] Trying to connect to route on 172.149.4.123:4248 (172.149.4.123:4248)
[8741] 2025/08/21 14:36:42.696816 [DBG] 172.149.4.123:4248 - rid:7 - Route connect msg sent
[8741] 2025/08/21 14:36:42.696840 [INF] 172.149.4.123:4248 - rid:7 - Route connection created
[8741] 2025/08/21 14:36:42.697741 [DBG] 172.149.4.123:4248 - rid:7 - Registering remote route "NDM22DTJIP3CFMH42ZD45U63Z3TCA3OQOJKBMIBZXD3CJYEJ5JIVB5QL"
[8741] 2025/08/21 14:36:42.698992 [ERR] 172.149.4.123:4248 - rid:7 - Route Error 'Authorization Violation'
[8741] 2025/08/21 14:36:42.699001 [INF] 172.149.4.123:4248 - rid:7 - Router connection closed: Parse Error - Remote: NDM22DTJIP3CFMH42ZD45U63Z3TCA3OQOJKBMIBZXD3CJYEJ5JIVB5QL
[8741] 2025/08/21 14:36:42.699059 [DBG] Attempting reconnect for solicited route "nats-route://ed08863a-79ce-41e1-b335-f67ed3f773a9:xxxxx@172.149.4.123:4248"
[8741] 2025/08/21 14:36:42.768357 [DBG] Trying to connect to route on 172.149.4.123:4248 (172.149.4.123:4248)
[8741] 2025/08/21 14:36:42.768999 [DBG] 172.149.4.123:4248 - rid:8 - Route connect msg sent
[8741] 2025/08/21 14:36:42.769022 [INF] 172.149.4.123:4248 - rid:8 - Route connection created
[8741] 2025/08/21 14:36:42.769922 [DBG] 172.149.4.123:4248 - rid:8 - Registering remote route "NDM22DTJIP3CFMH42ZD45U63Z3TCA3OQOJKBMIBZXD3CJYEJ5JIVB5QL"
[8741] 2025/08/21 14:36:42.770091 [ERR] 172.149.4.123:4248 - rid:8 - Route Error 'Authorization Violation'
[8741] 2025/08/21 14:36:42.770098 [INF] 172.149.4.123:4248 - rid:8 - Router connection closed: Parse Error - Remote: NDM22DTJIP3CFMH42ZD45U63Z3TCA3OQOJKBMIBZXD3CJYEJ5JIVB5QL
[8741] 2025/08/21 14:36:42.770345 [DBG] Attempting reconnect for solicited route "nats-route://ed08863a-79ce-41e1-b335-f67ed3f773a9:xxxxx@172.149.4.123:4248"
[8741] 2025/08/21 14:36:42.775312 [DBG] Trying to connect to route on 172.149.4.123:4248 (172.149.4.123:4248)
[8741] 2025/08/21 14:36:42.775835 [DBG] 172.149.4.123:4248 - rid:9 - Route connect msg sent
[8741] 2025/08/21 14:36:42.775856 [INF] 172.149.4.123:4248 - rid:9 - Route connection created
[8741] 2025/08/21 14:36:42.776766 [DBG] 172.149.4.123:4248 - rid:9 - Registering remote route "NDM22DTJIP3CFMH42ZD45U63Z3TCA3OQOJKBMIBZXD3CJYEJ5JIVB5QL"
[8741] 2025/08/21 14:36:42.776865 [ERR] 172.149.4.123:4248 - rid:9 - Route Error 'Authorization Violation'
[8741] 2025/08/21 14:36:42.776872 [INF] 172.149.4.123:4248 - rid:9 - Router connection closed: Parse Error - Remote: NDM22DTJIP3CFMH42ZD45U63Z3TCA3OQOJKBMIBZXD3CJYEJ5JIVB5QL
[8741] 2025/08/21 14:36:42.776944 [DBG] Attempting reconnect for solicited route "nats-route://ed08863a-79ce-41e1-b335-f67ed3f773a9:xxxxx@172.149.4.123:4248"
...
```

This patch "fixes" the issue for us.
```
diff --git a/server/client.go b/server/client.go
index b5bc04dc..20e53e4b 100644
--- a/server/client.go
+++ b/server/client.go
@@ -5883,6 +5883,7 @@ func (c *client) reconnect() {
                        srv.Debugf("Attempting reconnect for solicited route %q", rurl.Redacted())
                        // Keep track of this go-routine so we can wait for it on
                        // server shutdown.
+                       time.Sleep(10 * time.Second)
                        srv.startGoRoutine(func() { srv.reConnectToRoute(rurl, rtype, accName) })
                }
        } else if srv != nil && kind == GATEWAY && gwIsOutbound {
```

### PR DESCRIPTION
**Pull request by kozlovic**
With route pooling, the server would create a connection to the remote and when receiving the INFO protocol, would start a new route if the amount of routes was below the effective pool size. But if the route failed due to authentication error, this would cause a rapid infinite attempt to recreate a route.

The approach here is to delay the creation of the new route after receiving the first PONG after sending a PING.

Resolves #7194

Signed-off-by: Ivan Kozlovic <ivan@synadia.com>

### CODE REVIEW

File: server/client.go [hunk 1]
```diff
@@ -2605,6 +2614,11 @@ func (c *client) processPong() {
 	if reorderGWs {
 		srv.gateway.orderOutboundConnections()
 	}
+	if ri != nil {
+		srv.startGoRoutine(func() {
+			srv.connectToRoute(ri.url, ri.rtype, true, ri.gossipMode, _EMPTY_)
```
Comment (MauriceVanVeen) [inline server/client.go:2619]: Should this also include the `case <-time.After(time.Duration(rand.Intn(100)) * time.Millisecond):` from here? https://github.com/nats-io/nats-server/pull/7200/files#diff-e02d4430ca4d47be9db1b632ddb92d22c34c0919348bc020ce809e64fca8631cL2386-L2394

Comment (kozlovic) [reply server/client.go:2619]: I don't think this is needed. The routes will now be more serialized than before, and even then, I am not sure this was really needed (I think I had that in case where they both connect to each other A <-> B, which could cause at the end more routes to be closed than I would have liked).
