### PR TITLE
Fix operator list config

### LINKED ISSUE #5810: Unable to add multiple trusted operators using a config file
### Observed behavior

It looks like parsing the `operators` field in a config file is broken since it's trying to interpret the line as an `[]interface` instead of `[]string`.

This patch mostly ripped off from the implementation of the `server_tags` case shows a fix illustrating that the parser is misidentifying the type of the line:

```diff --git a/server/opts.go b/server/opts.go
index ac398823..414d2312 100644
--- a/server/opts.go
+++ b/server/opts.go
@@ -1195,6 +1195,22 @@ func (o *Options) processConfigFileLine(k string, v any, errors *[]error, warnin
 			opFiles = append(opFiles, v)
 		case []string:
 			opFiles = append(opFiles, v...)
+		case []any:
+			for _, t := range v {
+				if token, ok := t.(token); ok {
+					if ts, ok := token.Value().(string); ok {
+						opFiles = append(opFiles, ts)
+						continue
+					} else {
+						err := &configErr{tk, fmt.Sprintf("error parsing tags: unsupported type %T where string is expected", token)}
+						*errors = append(*errors, err)
+					}
+				} else {
+					err := &configErr{tk, fmt.Sprintf("error parsing tags: unsupported type %T", t)}
+					*errors = append(*errors, err)
+				}
+				break
+			}
 		default:
 			err := &configErr{tk, fmt.Sprintf("error parsing operators: unsupported type %T", v)}
 			*errors = append(*errors, err)```
```
Running `nats-server` v2.10.18 with multiple operator JWTs defined as an array then works.

### Expected behavior

The parser should correctly identify `operators: ["$jwt", "$jwt2"] as a valid configuration option so that you can add multiple trusted operators if needed.

### Server and client version

nats-server: v2.10.18

### Host environment

_No response_

### Steps to reproduce

_No response_

### PR DESCRIPTION
**Pull request by Jarema**
fixes #5810 

Signed-off-by: Tomasz Pietrek <tomasz@nats.io>

### CODE REVIEW

File: server/opts_test.go [hunk 1]
```diff
@@ -2932,6 +2932,32 @@ func TestReadOperatorJWT(t *testing.T) {
...
+`
+
+func TestReadMultipleOperatorJWT(t *testing.T) {
+	confFileName := createConfFile(t, []byte(operatorJwtList))
+	opts, err := ProcessConfigFile(confFileName)
+	if err != nil {
+		t.Fatalf("Received unexpected error %s", err)
+	}
+
+	require_True(t, len(opts.TrustedOperators) == 2)
```
Comment (neilalexander) [inline server/opts_test.go:2951]: `require_Equal` for all of these please, otherwise the log output when the test fails is useless.

File: server/opts.go [hunk 2]
```diff
@@ -1286,6 +1286,22 @@ func (o *Options) processConfigFileLine(k string, v any, errors *[]error, warnin
 			opFiles = append(opFiles, v)
 		case []string:
 			opFiles = append(opFiles, v...)
+		case []any:
+			for _, t := range v {
+				if token, ok := t.(token); ok {
+					if v, ok := token.Value().(string); ok {
+						opFiles = append(opFiles, v)
+						continue
```
Comment (neilalexander) [inline server/opts.go:1294]: It's a bit weird having the flow logic inverted here. Can we move the `break`s to the error cases and remove the `continue`?

**Review by neilalexander — CHANGES_REQUESTED** [review]

File: server/opts.go (hunk 2 above)
Comment (Jarema) [reply server/opts.go:1294]: Sure. I tried to be consistent and followed the `server_tags` logic.

**Review by neilalexander — APPROVED** [review]
LGTM

File: server/opts.go [hunk 3]
```diff
@@ -1286,6 +1286,22 @@ func (o *Options) processConfigFileLine(k string, v any, errors *[]error, warnin
 			opFiles = append(opFiles, v)
 		case []string:
 			opFiles = append(opFiles, v...)
+		case []any:
```
Comment (kozlovic) [inline server/opts.go:1289]: You could have a look at the helper `parseStringArray()`. That could simplify the `case "operator"` a bit, I think.

Comment (derekcollison) [reply server/opts.go:1289]: @Jarema Do you want to look at using that helper or are we good as is?
