### PR TITLE
[FIXED] Subscription interest could remain after slow consumer error

### LINKED ISSUE #5539: Incoming messages to the host without connections
### Observed behavior

We have a NATS cluster with 3 nodes in different AZ and connecting clients also to the node in the same AZ.
We have 1 node without connections, and once we got the situation when this node has no connections but a lot of incoming "orphan" messages from the other nodes:

CleanShot 2024-06-14 at 17 13 40@2x

We tried to change "pool_size = -1" - cluster updated the configuration but it did not help to down-crease incoming traffic.

<details>
  <summary>Routes before the pool_size parameter change</summary>

  ```js
  {
  "server": {
    "name": "nats-cluster-v4-0",
    "host": "0.0.0.0",
    "id": "NBYFQSZJA3Q42WRHRMDH6SCBQ3YJKBZZXH62P4BDZW73PCMFXZCQVKKS",
    "cluster": "nats-cluster-v4",
    "ver": "2.10.14",
    "jetstream": false,
    "flags": 0,
    "seq": 27816,
    "time": "2024-06-14T09:00:15.936315993Z"
  },
  "data": {
    "server_id": "NBYFQSZJA3Q42WRHRMDH6SCBQ3YJKBZZXH62P4BDZW73PCMFXZCQVKKS",
    "server_name": "nats-cluster-v4-0",
    "now": "2024-06-14T09:00:15.936260353Z",
    "num_routes": 8,
    "routes": [
      {
        "rid": 6,
        "remote_id": "NCS7TNLPVKAI7YA777FKARHZAEVIUOQ5CKFYXSKP6RDO2ZGE2TSFGE25",
        "remote_name": "nats-cluster-v4-1",
        "did_solicit": true,
        "is_configured": true,
        "ip": "10.202.142.65",
        "port": 6222,
        "start": "2024-06-04T17:45:20.530656125Z",
        "last_activity": "2024-06-04T17:45:20.531406265Z",
        "rtt": "218µs",
        "uptime": "9d15h14m55s",
        "idle": "9d15h14m55s",
        "pending_size": 0,
        "in_msgs": 0,
        "out_msgs": 0,
        "in_bytes": 0,
        "out_bytes": 0,
        "subscriptions": 0,
        "compression": "off"
      },
      {
        "rid": 9,
        "remote_id": "NCS7TNLPVKAI7YA777FKARHZAEVIUOQ5CKFYXSKP6RDO2ZGE2TSFGE25",
        "remote_name": "nats-cluster-v4-1",
        "did_solicit": true,
        "is_configured": true,
        "ip": "10.202.142.65",
        "port": 6222,
        "start": "2024-06-04T17:45:20.578446619Z",
        "last_activity": "2024-06-04T17:45:20.578905629Z",
        "rtt": "207µs",
        "uptime": "9d15h14m55s",
        "idle": "9d15h14m55s",
        "pending_size": 0,
        "in_msgs": 0,
        "out_msgs": 0,
        "in_bytes": 0,
        "out_bytes": 0,
        "subscriptions": 0,
        "compression": "off"
      },
      {
        "rid": 12,
        "remote_id": "NCS7TNLPVKAI7YA777FKARHZAEVIUOQ5CKFYXSKP6RDO2ZGE2TSFGE25",
        "remote_name": "nats-cluster-v4-1",
        "did_solicit": true,
        "is_configured": true,
        "ip": "10.202.142.65",
        "port": 6222,
        "start": "2024-06-04T17:45:20.660375Z",
        "last_activity": "2024-06-14T09:00:15.936291023Z",
        "rtt": "219µs",
        "uptime": "9d15h14m55s",
        "idle": "0s",
        "pending_size": 0,
        "in_msgs": 1045046185,
        "out_msgs": 65460384,
        "in_bytes": 1868687327845,
        "out_bytes": 51359890769,
        "subscriptions": 6252,
        "compression": "off"
      },
      {
        "rid": 8,
        "remote_id": "NC34AP6LAJSBGRNQOZHE5OYXNEAEDITZXBGYQP4USZ3GHMBJP2DGCKO2",
        "remote_name": "nats-cluster-v4-2",
        "did_solicit": true,
        "is_configured": true,
        "ip": "10.202.172.33",
        "port": 6222,
        "start": "2024-06-04T17:45:20.530737765Z",
        "last_activity": "2024-06-04T17:45:20.531492214Z",
        "rtt": "292µs",
        "uptime": "9d15h14m55s",
        "idle": "9d15h14m55s",
        "pending_size": 0,
        "in_msgs": 0,
        "out_msgs": 0,
        "in_bytes": 0,
        "out_bytes": 0,
        "subscriptions": 0,
        "compression": "off"
      },
      {
        "rid": 10,
        "remote_id": "NC34AP6LAJSBGRNQOZHE5OYXNEAEDITZXBGYQP4USZ3GHMBJP2DGCKO2",
        "remote_name": "nats-cluster-v4-2",
        "did_solicit": true,
        "is_configured": true,
        "ip": "10.202.172.33",
        "port": 6222,
        "start": "2024-06-04T17:45:20.604039586Z",
        "last_activity": "2024-06-04T17:45:20.604548357Z",
        "rtt": "308µs",
        "uptime": "9d15h14m55s",
        "idle": "9d15h14m55s",
        "pending_size": 0,
        "in_msgs": 0,
        "out_msgs": 0,
        "in_bytes": 0,
        "out_bytes": 0,
        "subscriptions": 0,
        "compression": "off"
      },
      {
        "rid": 11,
        "remote_id": "NC34AP6LAJSBGRNQOZHE5OYXNEAEDITZXBGYQP4USZ3GHMBJP2DGCKO2",
        "remote_name": "nats-cluster-v4-2",
        "did_solicit": true,
        "is_configured": true,
        "ip": "10.202.172.33",
        "port": 6222,
        "start": "2024-06-04T17:45:20.633688383Z",
        "last_activity": "2024-06-14T09:00:15.931065823Z",
        "rtt": "243µs",
        "uptime": "9d15h14m55s",
        "idle": "0s",
        "pending_size": 0,
        "in_msgs": 33948303,
        "out_msgs": 14153420,
        "in_bytes": 11515003051,
        "out_bytes": 10301579698,
        "subscriptions": 13,
        "compression": "off"
      },
      {
        "rid": 5,
        "remote_id": "NCS7TNLPVKAI7YA777FKARHZAEVIUOQ5CKFYXSKP6RDO2ZGE2TSFGE25",
        "remote_name": "nats-cluster-v4-1",
        "did_solicit": true,
        "is_configured": true,
        "ip": "10.202.142.65",
        "port": 6222,
        "start": "2024-06-04T17:45:20.530645194Z",
        "last_activity": "2024-06-14T09:00:15.936240633Z",
        "rtt": "248µs",
        "uptime": "9d15h14m55s",
        "idle": "0s",
        "pending_size": 0,
        "in_msgs": 27798,
        "out_msgs": 27786,
        "in_bytes": 42873121,
        "out_bytes": 42789916,
        "subscriptions": 48,
        "account": "$SYS",
        "compression": "off"
      },
      {
        "rid": 7,
        "remote_id": "NC34AP6LAJSBGRNQOZHE5OYXNEAEDITZXBGYQP4USZ3GHMBJP2DGCKO2",
        "remote_name": "nats-cluster-v4-2",
        "did_solicit": true,
        "is_configured": true,
        "ip": "10.202.172.33",
        "port": 6222,
        "start": "2024-06-04T17:45:20.530697954Z",
        "last_activity": "2024-06-14T09:00:15.936240633Z",
        "rtt": "311µs",
        "uptime": "9d15h14m55s",
        "idle": "0s",
        "pending_size": 0,
        "in_msgs": 27765,
        "out_msgs": 27775,
        "in_bytes": 42166135,
        "out_bytes": 42464040,
        "subscriptions": 48,
        "account": "$SYS",
        "compression": "off"
      }
    ]
  }
}
{
  "server": {
    "name": "nats-cluster-v4-1",
    "host": "0.0.0.0",
    "id": "NCS7TNLPVKAI7YA777FKARHZAEVIUOQ5CKFYXSKP6RDO2ZGE2TSFGE25",
    "cluster": "nats-cluster-v4",
    "ver": "2.10.14",
    "jetstream": false,
    "flags": 0,
    "seq": 27874,
    "time": "2024-06-14T09:00:15.936405351Z"
  },
  "data": {
    "server_id": "NCS7TNLPVKAI7YA777FKARHZAEVIUOQ5CKFYXSKP6RDO2ZGE2TSFGE25",
    "server_name": "nats-cluster-v4-1",
    "now": "2024-06-14T09:00:15.936370711Z",
    "num_routes": 8,
    "routes": [
      {
        "rid": 6,
        "remote_id": "NC34AP6LAJSBGRNQOZHE5OYXNEAEDITZXBGYQP4USZ3GHMBJP2DGCKO2",
        "remote_name": "nats-cluster-v4-2",
        "did_solicit": true,
        "is_configured": true,
        "ip": "10.202.172.33",
        "port": 6222,
        "start": "2024-06-04T17:45:08.358281524Z",
        "last_activity": "2024-06-04T17:45:08.358675434Z",
        "rtt": "380µs",
        "uptime": "9d15h15m7s",
        "idle": "9d15h15m7s",
        "pending_size": 0,
        "in_msgs": 0,
        "out_msgs": 0,
        "in_bytes": 0,
        "out_bytes": 0,
        "subscriptions": 0,
        "compression": "off"
      },
      {
        "rid": 11,
        "remote_id": "NC34AP6LAJSBGRNQOZHE5OYXNEAEDITZXBGYQP4USZ3GHMBJP2DGCKO2",
        "remote_name": "nats-cluster-v4-2",
        "did_solicit": true,
        "is_configured": true,
        "ip": "10.202.172.33",
        "port": 6222,
        "start": "2024-06-04T17:45:08.373206593Z",
        "last_activity": "2024-06-04T17:45:08.373595833Z",
        "rtt": "295µs",
        "uptime": "9d15h15m7s",
        "idle": "9d15h15m7s",
        "pending_size": 0,
        "in_msgs": 0,
        "out_msgs": 0,
        "in_bytes": 0,
        "out_bytes": 0,
        "subscriptions": 0,
        "compression": "off"
      },
      {
        "rid": 13,
        "remote_id": "NC34AP6LAJSBGRNQOZHE5OYXNEAEDITZXBGYQP4USZ3GHMBJP2DGCKO2",
        "remote_name": "nats-cluster-v4-2",
        "did_solicit": true,
        "is_configured": true,
        "ip": "10.202.172.33",
        "port": 6222,
        "start": "2024-06-04T17:45:08.401488062Z",
        "last_activity": "2024-06-14T09:00:15.936183591Z",
        "rtt": "234µs",
        "uptime": "9d15h15m7s",
        "idle": "0s",
        "pending_size": 0,
        "in_msgs": 79617062,
        "out_msgs": 1027217544,
        "in_bytes": 68925666034,
        "out_bytes": 1863523035076,
        "subscriptions": 13,
        "compression": "off"
      },
      {
        "rid": 22,
        "remote_id": "NBYFQSZJA3Q42WRHRMDH6SCBQ3YJKBZZXH62P4BDZW73PCMFXZCQVKKS",
        "remote_name": "nats-cluster-v4-0",
        "did_solicit": true,
        "is_configured": true,
        "ip": "10.202.173.11",
        "port": 52636,
        "start": "2024-06-04T17:45:20.530854683Z",
        "last_activity": "2024-06-04T17:45:20.531027283Z",
        "rtt": "223µs",
        "uptime": "9d15h14m55s",
        "idle": "9d15h14m55s",
        "pending_size": 0,
        "in_msgs": 0,
        "out_msgs": 0,
        "in_bytes": 0,
        "out_bytes": 0,
        "subscriptions": 0,
        "compression": "off"
      },
      {
        "rid": 23,
        "remote_id": "NBYFQSZJA3Q42WRHRMDH6SCBQ3YJKBZZXH62P4BDZW73PCMFXZCQVKKS",
        "remote_name": "nats-cluster-v4-0",
        "did_solicit": true,
        "is_configured": true,
        "ip": "10.202.173.11",
        "port": 52648,
        "start": "2024-06-04T17:45:20.578585482Z",
        "last_activity": "2024-06-04T17:45:20.578741222Z",
        "rtt": "270µs",
        "uptime": "9d15h14m55s",
        "idle": "9d15h14m55s",
        "pending_size": 0,
        "in_msgs": 0,
        "out_msgs": 0,
        "in_bytes": 0,
        "out_bytes": 0,
        "subscriptions": 0,
        "compression": "off"
      },
      {
        "rid": 24,
        "remote_id": "NBYFQSZJA3Q42WRHRMDH6SCBQ3YJKBZZXH62P4BDZW73PCMFXZCQVKKS",
        "remote_name": "nats-cluster-v4-0",
        "did_solicit": true,
        "is_configured": true,
        "ip": "10.202.173.11",
        "port": 52652,
        "start": "2024-06-04T17:45:20.660517999Z",
        "last_activity": "2024-06-14T09:00:15.936183591Z",
        "rtt": "219µs",
        "uptime": "9d15h14m55s",
        "idle": "0s",
        "pending_size": 0,
        "in_msgs": 65460384,
        "out_msgs": 1045046186,
        "in_bytes": 51359890769,
        "out_bytes": 1868687328185,
        "subscriptions": 1286,
        "compression": "off"
      },
      {
        "rid": 5,
        "remote_id": "NC34AP6LAJSBGRNQOZHE5OYXNEAEDITZXBGYQP4USZ3GHMBJP2DGCKO2",
        "remote_name": "nats-cluster-v4-2",
        "did_solicit": true,
        "is_configured": true,
        "ip": "10.202.172.33",
        "port": 6222,
        "start": "2024-06-04T17:45:08.356582374Z",
        "last_activity": "2024-06-14T09:00:12.199988588Z",
        "rtt": "246µs",
        "uptime": "9d15h15m7s",
        "idle": "3s",
        "pending_size": 0,
        "in_msgs": 27777,
        "out_msgs": 27804,
        "in_bytes": 42177782,
        "out_bytes": 42809896,
        "subscriptions": 48,
        "account": "$SYS",
        "compression": "off"
      },
      {
        "rid": 21,
        "remote_id": "NBYFQSZJA3Q42WRHRMDH6SCBQ3YJKBZZXH62P4BDZW73PCMFXZCQVKKS",
        "remote_name": "nats-cluster-v4-0",
        "did_solicit": true,
        "is_configured": true,
        "ip": "10.202.173.11",
        "port": 52630,
        "start": "2024-06-04T17:45:20.530829183Z",
        "last_activity": "2024-06-14T09:00:15.936356571Z",
        "rtt": "337µs",
        "uptime": "9d15h14m55s",
        "idle": "0s",
        "pending_size": 0,
        "in_msgs": 27786,
        "out_msgs": 27798,
        "in_bytes": 42789916,
        "out_bytes": 42873121,
        "subscriptions": 49,
        "account": "$SYS",
        "compression": "off"
      }
    ]
  }
}
{
  "server": {
    "name": "nats-cluster-v4-2",
    "host": "0.0.0.0",
    "id": "NC34AP6LAJSBGRNQOZHE5OYXNEAEDITZXBGYQP4USZ3GHMBJP2DGCKO2",
    "cluster": "nats-cluster-v4",
    "ver": "2.10.14",
    "jetstream": false,
    "flags": 0,
    "seq": 27816,
    "time": "2024-06-14T09:00:15.936489307Z"
  },
  "data": {
    "server_id": "NC34AP6LAJSBGRNQOZHE5OYXNEAEDITZXBGYQP4USZ3GHMBJP2DGCKO2",
    "server_name": "nats-cluster-v4-2",
    "now": "2024-06-14T09:00:15.936449387Z",
    "num_routes": 8,
    "routes": [
      {
        "rid": 26,
        "remote_id": "NCS7TNLPVKAI7YA777FKARHZAEVIUOQ5CKFYXSKP6RDO2ZGE2TSFGE25",
        "remote_name": "nats-cluster-v4-1",
        "did_solicit": true,
        "is_configured": true,
        "ip": "10.202.142.65",
        "port": 59576,
        "start": "2024-06-04T17:45:08.358430289Z",
        "last_activity": "2024-06-04T17:45:08.358559849Z",
        "rtt": "255µs",
        "uptime": "9d15h15m7s",
        "idle": "9d15h15m7s",
        "pending_size": 0,
        "in_msgs": 0,
        "out_msgs": 0,
        "in_bytes": 0,
        "out_bytes": 0,
        "subscriptions": 0,
        "compression": "off"
      },
      {
        "rid": 27,
        "remote_id": "NCS7TNLPVKAI7YA777FKARHZAEVIUOQ5CKFYXSKP6RDO2ZGE2TSFGE25",
        "remote_name": "nats-cluster-v4-1",
        "did_solicit": true,
        "is_configured": true,
        "ip": "10.202.142.65",
        "port": 59578,
        "start": "2024-06-04T17:45:08.373324948Z",
        "last_activity": "2024-06-04T17:45:08.373466167Z",
        "rtt": "249µs",
        "uptime": "9d15h15m7s",
        "idle": "9d15h15m7s",
        "pending_size": 0,
        "in_msgs": 0,
        "out_msgs": 0,
        "in_bytes": 0,
        "out_bytes": 0,
        "subscriptions": 0,
        "compression": "off"
      },
      {
        "rid": 28,
        "remote_id": "NCS7TNLPVKAI7YA777FKARHZAEVIUOQ5CKFYXSKP6RDO2ZGE2TSFGE25",
        "remote_name": "nats-cluster-v4-1",
        "did_solicit": true,
        "is_configured": true,
        "ip": "10.202.142.65",
        "port": 59588,
        "start": "2024-06-04T17:45:08.401617335Z",
        "last_activity": "2024-06-14T09:00:15.936316987Z",
        "rtt": "290µs",
        "uptime": "9d15h15m7s",
        "idle": "0s",
        "pending_size": 0,
        "in_msgs": 1027217544,
        "out_msgs": 79617062,
        "in_bytes": 1863523035076,
        "out_bytes": 68925666034,
        "subscriptions": 6252,
        "compression": "off"
      },
      {
        "rid": 29,
        "remote_id": "NBYFQSZJA3Q42WRHRMDH6SCBQ3YJKBZZXH62P4BDZW73PCMFXZCQVKKS",
        "remote_name": "nats-cluster-v4-0",
        "did_solicit": true,
        "is_configured": true,
        "ip": "10.202.173.11",
        "port": 44962,
        "start": "2024-06-04T17:45:20.530866763Z",
        "last_activity": "2024-06-04T17:45:20.531103313Z",
        "rtt": "215µs",
        "uptime": "9d15h14m55s",
        "idle": "9d15h14m55s",
        "pending_size": 0,
        "in_msgs": 0,
        "out_msgs": 0,
        "in_bytes": 0,
        "out_bytes": 0,
        "subscriptions": 0,
        "compression": "off"
      },
      {
        "rid": 31,
        "remote_id": "NBYFQSZJA3Q42WRHRMDH6SCBQ3YJKBZZXH62P4BDZW73PCMFXZCQVKKS",
        "remote_name": "nats-cluster-v4-0",
        "did_solicit": true,
        "is_configured": true,
        "ip": "10.202.173.11",
        "port": 44970,
        "start": "2024-06-04T17:45:20.604194468Z",
        "last_activity": "2024-06-04T17:45:20.604339128Z",
        "rtt": "277µs",
        "uptime": "9d15h14m55s",
        "idle": "9d15h14m55s",
        "pending_size": 0,
        "in_msgs": 0,
        "out_msgs": 0,
        "in_bytes": 0,
        "out_bytes": 0,
        "subscriptions": 0,
        "compression": "off"
      },
      {
        "rid": 32,
        "remote_id": "NBYFQSZJA3Q42WRHRMDH6SCBQ3YJKBZZXH62P4BDZW73PCMFXZCQVKKS",
        "remote_name": "nats-cluster-v4-0",
        "did_solicit": true,
        "is_configured": true,
        "ip": "10.202.173.11",
        "port": 44984,
        "start": "2024-06-04T17:45:20.633770436Z",
        "last_activity": "2024-06-14T09:00:15.930918998Z",
        "rtt": "238µs",
        "uptime": "9d15h14m55s",
        "idle": "0s",
        "pending_size": 0,
        "in_msgs": 14153420,
        "out_msgs": 33948303,
        "in_bytes": 10301579698,
        "out_bytes": 11515003051,
        "subscriptions": 1286,
        "compression": "off"
      },
      {
        "rid": 25,
        "remote_id": "NCS7TNLPVKAI7YA777FKARHZAEVIUOQ5CKFYXSKP6RDO2ZGE2TSFGE25",
        "remote_name": "nats-cluster-v4-1",
        "did_solicit": true,
        "is_configured": true,
        "ip": "10.202.142.65",
        "port": 59560,
        "start": "2024-06-04T17:45:08.356758569Z",
        "last_activity": "2024-06-14T09:00:12.199711305Z",
        "rtt": "323µs",
        "uptime": "9d15h15m7s",
        "idle": "3s",
        "pending_size": 0,
        "in_msgs": 27804,
        "out_msgs": 27777,
        "in_bytes": 42809896,
        "out_bytes": 42177782,
        "subscriptions": 48,
        "account": "$SYS",
        "compression": "off"
      },
      {
        "rid": 30,
        "remote_id": "NBYFQSZJA3Q42WRHRMDH6SCBQ3YJKBZZXH62P4BDZW73PCMFXZCQVKKS",
        "remote_name": "nats-cluster-v4-0",
        "did_solicit": true,
        "is_configured": true,
        "ip": "10.202.173.11",
        "port": 44952,
        "start": "2024-06-04T17:45:20.530884863Z",
        "last_activity": "2024-06-14T09:00:15.936429307Z",
        "rtt": "341µs",
        "uptime": "9d15h14m55s",
        "idle": "0s",
        "pending_size": 0,
        "in_msgs": 27775,
        "out_msgs": 27765,
        "in_bytes": 42464040,
        "out_bytes": 42166135,
        "subscriptions": 49,
        "account": "$SYS",
        "compression": "off"
      }
    ]
  }
}
  ```
</details>

<details>
  <summary>Routes after the change</summary>
  
  ```js
{
  "server": {
    "name": "nats-cluster-v4-1",
    "host": "0.0.0.0",
    "id": "NCS7TNLPVKAI7YA777FKARHZAEVIUOQ5CKFYXSKP6RDO2ZGE2TSFGE25",
    "cluster": "nats-cluster-v4",
    "ver": "2.10.14",
    "jetstream": false,
    "flags": 0,
    "seq": 30506,
    "time": "2024-06-14T15:48:01.505977662Z"
  },
  "data": {
    "server_id": "NCS7TNLPVKAI7YA777FKARHZAEVIUOQ5CKFYXSKP6RDO2ZGE2TSFGE25",
    "server_name": "nats-cluster-v4-1",
    "now": "2024-06-14T15:48:01.505934692Z",
    "num_routes": 2,
    "routes": [
      {
        "rid": 6264,
        "remote_id": "NBRW5CG3HCOJSGMMXDGDGHPHTFUDLEYFUP3PXFWLNVFZ4PXCVLCQXNCI",
        "remote_name": "nats-cluster-v4-2",
        "did_solicit": true,
        "is_configured": true,
        "ip": "10.202.172.149",
        "port": 52110,
        "start": "2024-06-14T12:46:40.646080193Z",
        "last_activity": "2024-06-14T15:48:01.505911722Z",
        "rtt": "332µs",
        "uptime": "3h1m20s",
        "idle": "0s",
        "pending_size": 0,
        "in_msgs": 53161,
        "out_msgs": 882,
        "in_bytes": 75416839,
        "out_bytes": 335060,
        "subscriptions": 56,
        "compression": "off"
      },
      {
        "rid": 6122,
        "remote_id": "NBYFQSZJA3Q42WRHRMDH6SCBQ3YJKBZZXH62P4BDZW73PCMFXZCQVKKS",
        "remote_name": "nats-cluster-v4-0",
        "did_solicit": true,
        "is_configured": true,
        "ip": "10.202.173.11",
        "port": 52472,
        "start": "2024-06-14T12:34:42.848411331Z",
        "last_activity": "2024-06-14T15:48:01.505957832Z",
        "rtt": "291µs",
        "uptime": "3h13m18s",
        "idle": "0s",
        "pending_size": 0,
        "in_msgs": 682786,
        "out_msgs": 87690088,
        "in_bytes": 690431012,
        "out_bytes": 180559446164,
        "subscriptions": 1502,
        "compression": "off"
      }
    ]
  }
}
{
  "server": {
    "name": "nats-cluster-v4-0",
    "host": "0.0.0.0",
    "id": "NBYFQSZJA3Q42WRHRMDH6SCBQ3YJKBZZXH62P4BDZW73PCMFXZCQVKKS",
    "cluster": "nats-cluster-v4",
    "ver": "2.10.14",
    "jetstream": false,
    "flags": 0,
    "seq": 28927,
    "time": "2024-06-14T15:48:01.506207613Z"
  },
  "data": {
    "server_id": "NBYFQSZJA3Q42WRHRMDH6SCBQ3YJKBZZXH62P4BDZW73PCMFXZCQVKKS",
    "server_name": "nats-cluster-v4-0",
    "now": "2024-06-14T15:48:01.506158393Z",
    "num_routes": 2,
    "routes": [
      {
        "rid": 6056,
        "remote_id": "NBRW5CG3HCOJSGMMXDGDGHPHTFUDLEYFUP3PXFWLNVFZ4PXCVLCQXNCI",
        "remote_name": "nats-cluster-v4-2",
        "did_solicit": true,
        "is_configured": true,
        "ip": "10.202.172.149",
        "port": 58960,
        "start": "2024-06-14T12:46:40.646873006Z",
        "last_activity": "2024-06-14T15:48:01.485820224Z",
        "rtt": "402µs",
        "uptime": "3h1m20s",
        "idle": "0s",
        "pending_size": 0,
        "in_msgs": 582011,
        "out_msgs": 1127420,
        "in_bytes": 246896380,
        "out_bytes": 3392144265,
        "subscriptions": 56,
        "compression": "off"
      },
      {
        "rid": 6038,
        "remote_id": "NCS7TNLPVKAI7YA777FKARHZAEVIUOQ5CKFYXSKP6RDO2ZGE2TSFGE25",
        "remote_name": "nats-cluster-v4-1",
        "did_solicit": true,
        "is_configured": true,
        "ip": "10.202.142.65",
        "port": 6222,
        "start": "2024-06-14T12:34:42.848315979Z",
        "last_activity": "2024-06-14T15:48:01.506126813Z",
        "rtt": "266µs",
        "uptime": "3h13m18s",
        "idle": "0s",
        "pending_size": 0,
        "in_msgs": 87690088,
        "out_msgs": 682786,
        "in_bytes": 180559446164,
        "out_bytes": 690431012,
        "subscriptions": 6132,
        "compression": "off"
      }
    ]
  }
}
{
  "server": {
    "name": "nats-cluster-v4-2",
    "host": "0.0.0.0",
    "id": "NBRW5CG3HCOJSGMMXDGDGHPHTFUDLEYFUP3PXFWLNVFZ4PXCVLCQXNCI",
    "cluster": "nats-cluster-v4",
    "ver": "2.10.14",
    "jetstream": false,
    "flags": 0,
    "seq": 401,
    "time": "2024-06-14T15:48:01.506191192Z"
  },
  "data": {
    "server_id": "NBRW5CG3HCOJSGMMXDGDGHPHTFUDLEYFUP3PXFWLNVFZ4PXCVLCQXNCI",
    "server_name": "nats-cluster-v4-2",
    "now": "2024-06-14T15:48:01.506164282Z",
    "num_routes": 2,
    "routes": [
      {
        "rid": 5,
        "remote_id": "NCS7TNLPVKAI7YA777FKARHZAEVIUOQ5CKFYXSKP6RDO2ZGE2TSFGE25",
        "remote_name": "nats-cluster-v4-1",
        "did_solicit": true,
        "is_configured": true,
        "ip": "10.202.142.65",
        "port": 6222,
        "start": "2024-06-14T12:46:40.645912846Z",
        "last_activity": "2024-06-14T15:48:01.506142912Z",
        "rtt": "302µs",
        "uptime": "3h1m20s",
        "idle": "0s",
        "pending_size": 0,
        "in_msgs": 882,
        "out_msgs": 53161,
        "in_bytes": 335060,
        "out_bytes": 75416839,
        "subscriptions": 6132,
        "compression": "off"
      },
      {
        "rid": 6,
        "remote_id": "NBYFQSZJA3Q42WRHRMDH6SCBQ3YJKBZZXH62P4BDZW73PCMFXZCQVKKS",
        "remote_name": "nats-cluster-v4-0",
        "did_solicit": true,
        "is_configured": true,
        "ip": "10.202.173.11",
        "port": 6222,
        "start": "2024-06-14T12:46:40.646706926Z",
        "last_activity": "2024-06-14T15:48:01.485658073Z",
        "rtt": "301µs",
        "uptime": "3h1m20s",
        "idle": "0s",
        "pending_size": 0,
        "in_msgs": 1127420,
        "out_msgs": 582011,
        "in_bytes": 3392144265,
        "out_bytes": 246896380,
        "subscriptions": 1502,
        "compression": "off"
      }
    ]
  }
}
  ```
</details>

Only node restart did the trick. Situation after restart (0 connections, ~0 incoming bytes, ~0 outgoing bytes):

CleanShot 2024-06-14 at 17 25 50@2x

### Expected behavior

Remove the subscription route when there are no consumers to read messages.

### Server and client version

Server version: 2.10.14
Client: -

### Host environment

GKE host:

OS: Container-Optimized OS from Google
OS version: 109
Architecture: x86-64
CR: containerd

### Steps to reproduce

In our case a few slow consumers had appeared in a cluster and incoming messages ran to the free node.

In logs we could see only messages like:

<details>
  <summary>Logs</summary>

  ```js
nats [7] 2024/06/10 11:05:42.004110 [INF] 10.202.171.13:52058 - cid:3207 - Slow Consumer Detected: WriteDeadline of 4s exceeded with 2 chunks of 4435 total bytes.
nats [7] 2024/06/10 11:11:03.923105 [INF] 10.202.171.13:55020 - cid:3211 - Slow Consumer Detected: WriteDeadline of 4s exceeded with 2 chunks of 535 total bytes.
nats [7] 2024/06/10 11:11:29.156916 [INF] 10.202.171.13:47712 - cid:3212 - Slow Consumer Detected: WriteDeadline of 4s exceeded with 1 chunks of 176 total bytes.
nats [7] 2024/06/10 11:12:13.039384 [INF] 10.202.171.13:36508 - cid:3214 - Slow Consumer Detected: WriteDeadline of 4s exceeded with 44 chunks of 601458 total bytes.
nats [7] 2024/06/10 11:13:49.470739 [INF] 10.202.171.13:36666 - cid:3216 - Slow Consumer Detected: WriteDeadline of 4s exceeded with 14 chunks of 258264 total bytes.
nats [7] 2024/06/10 11:26:42.056093 [INF] 10.202.171.13:33510 - cid:3219 - Slow Consumer Detected: WriteDeadline of 4s exceeded with 2 chunks of 848 total bytes.
nats [7] 2024/06/10 11:31:57.516530 [INF] 10.202.171.13:55710 - cid:3221 - Slow Consumer Detected: WriteDeadline of 4s exceeded with 1 chunks of 69 total bytes.
nats [7] 2024/06/10 11:33:56.144849 [INF] 10.202.171.13:58652 - cid:3223 - Slow Consumer Detected: WriteDeadline of 4s exceeded with 2 chunks of 4319 total bytes.
nats [7] 2024/06/10 11:37:48.260718 [INF] 10.202.171.13:59468 - cid:3227 - Slow Consumer Detected: WriteDeadline of 4s exceeded with 30 chunks of 789327 total bytes.
nats [7] 2024/06/10 11:38:29.813781 [INF] 10.202.171.13:40308 - cid:3229 - Slow Consumer Detected: WriteDeadline of 4s exceeded with 2 chunks of 1659 total bytes.
nats [7] 2024/06/10 15:39:38.161377 [INF] 10.202.171.13:55896 - cid:3330 - Slow Consumer Detected: WriteDeadline of 4s exceeded with 35 chunks of 929026 total bytes.
nats [7] 2024/06/10 15:41:54.142104 [INF] 10.202.171.13:48106 - cid:3335 - Slow Consumer Detected: WriteDeadline of 4s exceeded with 2 chunks of 8820 total bytes.
nats [7] 2024/06/10 17:08:54.921921 [INF] 10.202.171.13:37126 - cid:3409 - Slow Consumer Detected: WriteDeadline of 4s exceeded with 61 chunks of 1927533 total bytes.
nats [7] 2024/06/10 17:16:09.376586 [INF] 10.202.171.13:39610 - cid:3415 - Slow Consumer Detected: WriteDeadline of 4s exceeded with 2 chunks of 5772 total bytes.
nats [7] 2024/06/10 17:18:45.193519 [INF] 10.202.171.13:56224 - cid:3416 - Slow Consumer Detected: WriteDeadline of 4s exceeded with 2 chunks of 2065 total bytes.
nats [7] 2024/06/10 17:28:55.946395 [INF] 10.202.171.13:53416 - cid:3417 - Slow Consumer Detected: WriteDeadline of 4s exceeded with 2 chunks of 13288 total bytes.
nats [7] 2024/06/10 17:38:25.867114 [INF] 10.202.171.13:48406 - cid:3422 - Slow Consumer Detected: WriteDeadline of 4s exceeded with 2 chunks of 16039 total bytes.
nats [7] 2024/06/10 17:38:41.448495 [INF] 10.202.171.13:48482 - cid:3423 - Slow Consumer Detected: WriteDeadline of 4s exceeded with 2 chunks of 18763 total bytes
  ```
</details>

### PR DESCRIPTION
**Pull request by kozlovic**
When a slow consumer error is detected, the server will close the connection. In some race situations, it could be that the subscription interest is left intact, which would cause routed servers to continue routing messages although the interest should have been gone.

The subscription could still be seen in the monitoring subscriptions list (when displaying with details), referencing a client connection that would be in the closed connection state.
The monitoring route page of the other servers would still indicate that there is interest for this subject on the origin server.

Resolves #5539

Signed-off-by: Ivan Kozlovic <ivan@synadia.com>

### CODE REVIEW

File: server/client.go [hunk 1]
```diff
@@ -1827,9 +1827,20 @@ func (c *client) markConnAsClosed(reason ClosedState) {
...
+			if len(c.subs) > 0 {
+				subs = make([]*subscription, 0, len(c.subs))
+				for _, sub := range c.subs {
+					subs = append(subs, sub)
+				}
+			}
 			// TODO: May want to send events to single go routine instead
 			// of creating a new go routine for each save.
-			go c.srv.saveClosedClient(c, nc, reason)
+			go c.srv.saveClosedClient(c, nc, subs, reason)
```
Comment (derekcollison) [inline server/client.go:1843]: Could we just pass the c.subs map to saveClosedClient and avoid copy and heap alloc?

That way no additional allocs, but since we pas directly ok if c.subs is nil'd out.

**Review by derekcollison — COMMENTED** [review]
In general LGTM - question about avoiding a copy.

**Review by neilalexander — APPROVED** [review]
LGTM, good spot!

File: server/client.go (hunk 1 above)
Comment (kozlovic) [reply server/client.go:1843]: Well no, that's what was there originally (meaning saveClosedClient() was using c.subs directly). The issue is that at one point we have to set `c.subs = nil` and we use c.subs in `closeConnection()`, but `markConnAsClosed` (which start the `saveClosedClient` go routine can be invoked either in `closeConnection()` or in some other places when detecting a slow consumer, etc..

We could use some more state to detect when it is safe to set `c.subs = nil`.

(and to answer your comment: if we have c.subs that is nil when using it in saveClosedClient, then we could have closed client connections that do not reflect their real list of subscriptions. I am expecting some tests that would then flap).

Comment (kozlovic) [reply server/client.go:1843]: For instance, we could use a waitgroup/channel to wait for saveClosedClient() to be done using c.subs in closeConnection where I now set the c.subs to nil.

Comment (derekcollison) [reply server/client.go:1843]: I meant still pass it in as an arg to saveClosedConn, so c.subs, that way if it is nil'd out inside client struct won't matter but this would avoid additional allocation plus copy.

Comment (kozlovic) [reply server/client.go:1843]: I would have thought that it would not help for the TestNoRaceConnectionObjectReleased, but seems to be ok. Let me push the modifications and make sure that test is green. I will ping when I confirm it is ok.

Comment (kozlovic) [reply server/client.go]: @derekcollison Ok, Travis is green (at least for push, waiting on PR to complete, but I think it is ok).

Comment (kozlovic) [reply server/client.go]: Ok, Travis all green. Ready for review/merge.

Comment (derekcollison) [reply server/client.go]: Thanks.

File: server/client.go [hunk 2]
```diff
@@ -5511,6 +5513,14 @@ func (c *client) closeConnection(reason ClosedState) {
 		}
 	}
 
+	// Now that we are done with subscriptions, clear the field so that the
+	// connection can be released and gc'ed.
+	if kind == CLIENT || kind == LEAF {
```
Comment (derekcollison) [inline server/client.go:5518]: FYI when we set this to nil in saveClosedClient it was a much broader set of connection types. Do we think this might cause any GC issues on non client/leaf connections?

**Review by derekcollison — APPROVED** [review]
LGTM

File: server/client.go (hunk 2 above)
Comment (kozlovic) [reply server/client.go:5518]: No because we invoked saveClosedClient() only for CLIENT and LEAF: https://github.com/nats-io/nats-server/blob/02bd28438a538c9182ee1ebf2b04d29dc4842483/server/client.go#L1828

Comment (derekcollison) [reply server/client.go:5518]: Sorry was just looking at the internal if..
