### PR TITLE
[FIXED] Fix logic bug that would prevent some stream messages from being deleted.

### LINKED ISSUE #3612: "Dangling" messages on stream
nats-server: synadia/nats-server:nightly-20221107 (Git: [4e8d1ae])
nats: 0.0.34
3 node cluster, AWS EC2 Ubuntu

We have a interest based stream with 2 consumers, push subscribe, auto ack. We see no issues in our consuming services logs. But a lot of messages in the stream seemingly not consumed. Though vast majority of messages do get removed from the stream. Stream collects messages that are published using NATS core publish by a number of different services on different hosts. When issuing `nats stream view logs` it seems to clear most messages in the stream. But new ones continue to accumulate immediately.

1. `nats stream info logs; nats consumer info logs c1; nats consumer info logs c2;`

```
Information for Stream logs created 2022-07-13 20:07:45

             Subjects: logs.>
             Replicas: 3
              Storage: File

Options:

            Retention: Interest
     Acknowledgements: true
       Discard Policy: Old
     Duplicate Window: 2m0s
    Allows Msg Delete: true
         Allows Purge: true
       Allows Rollups: false

Limits:

     Maximum Messages: unlimited
  Maximum Per Subject: unlimited
        Maximum Bytes: 1.0 GiB
          Maximum Age: 5d0h0m0s
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited


Cluster Information:

                 Name: nats-cluster
               Leader: n1
              Replica: n3, current, seen 0.07s ago
              Replica: n2, current, seen 0.07s ago

State:

             Messages: 23,229
                Bytes: 20 MiB
             FirstSeq: 134,390,673 @ 2022-11-07T21:52:23 UTC
              LastSeq: 134,849,300 @ 2022-11-08T08:23:30 UTC
     Deleted Messages: 435,399
     Active Consumers: 2
   Number of Subjects: 20

Information for Consumer logs > c1 created 2022-11-04T14:04:16Z

Configuration:

        Durable Name: c1
    Delivery Subject: c1.logs
      Deliver Policy: All
 Deliver Queue Group: c1
          Ack Policy: Explicit
            Ack Wait: 30s
       Replay Policy: Instant
     Max Ack Pending: 1,000
        Flow Control: false

Cluster Information:

                Name: nats-cluster
              Leader: n1
             Replica: n3, current, seen 0.17s ago
             Replica: n2, current, seen 0.17s ago

State:

   Last Delivered Message: Consumer sequence: 134,827,928 Stream sequence: 134,849,303 Last delivery: 0.17s ago
     Acknowledgment floor: Consumer sequence: 134,827,928 Stream sequence: 134,849,303 Last Ack: 0.17s ago
         Outstanding Acks: 0 out of maximum 1,000
     Redelivered Messages: 0
     Unprocessed Messages: 0
          Active Interest: Active using Queue Group c1
Information for Consumer logs > c2 created 2022-11-04T15:36:04Z

Configuration:

        Durable Name: c2
    Delivery Subject: c2.logs
      Deliver Policy: All
 Deliver Queue Group: c2
          Ack Policy: Explicit
            Ack Wait: 30s
       Replay Policy: Instant
     Max Ack Pending: 1,000
        Flow Control: false

Cluster Information:

                Name: nats-cluster
              Leader: n2
             Replica: n3, current, seen 0.50s ago
             Replica: n1, current, seen 0.50s ago

State:

   Last Delivered Message: Consumer sequence: 134,835,616 Stream sequence: 134,849,303 Last delivery: 0.50s ago
     Acknowledgment floor: Consumer sequence: 134,835,616 Stream sequence: 134,849,303 Last Ack: 0.50s ago
         Outstanding Acks: 0 out of maximum 1,000
     Redelivered Messages: 0
     Unprocessed Messages: 0
          Active Interest: Active using Queue Group c2
```

2. `nats stream view logs`

```
...
[messages removed for brevity]
...

? Next Page? No
```

3. `nats stream info logs; nats consumer info logs c1; nats consumer info logs c2;`

```
Information for Stream logs created 2022-07-13 20:07:45

             Subjects: logs.>
             Replicas: 3
              Storage: File

Options:

            Retention: Interest
     Acknowledgements: true
       Discard Policy: Old
     Duplicate Window: 2m0s
    Allows Msg Delete: true
         Allows Purge: true
       Allows Rollups: false

Limits:

     Maximum Messages: unlimited
  Maximum Per Subject: unlimited
        Maximum Bytes: 1.0 GiB
          Maximum Age: 5d0h0m0s
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited


Cluster Information:

                 Name: nats-cluster
               Leader: n1
              Replica: n3, current, seen 1.30s ago
              Replica: n2, current, seen 1.31s ago

State:

             Messages: 35
                Bytes: 33 KiB
             FirstSeq: 134,848,747 @ 2022-11-08T08:22:17 UTC
              LastSeq: 134,849,345 @ 2022-11-08T08:23:42 UTC
     Deleted Messages: 564
     Active Consumers: 2
   Number of Subjects: 5

Information for Consumer logs > c1 created 2022-11-04T14:04:16Z

Configuration:

        Durable Name: c1
    Delivery Subject: c1.logs
      Deliver Policy: All
 Deliver Queue Group: c1
          Ack Policy: Explicit
            Ack Wait: 30s
       Replay Policy: Instant
     Max Ack Pending: 1,000
        Flow Control: false

Cluster Information:

                Name: nats-cluster
              Leader: n1
             Replica: n3, current, seen 0.00s ago
             Replica: n2, current, seen 0.00s ago

State:

   Last Delivered Message: Consumer sequence: 134,827,973 Stream sequence: 134,849,348 Last delivery: 0.04s ago
     Acknowledgment floor: Consumer sequence: 134,827,973 Stream sequence: 134,849,348 Last Ack: 0.02s ago
         Outstanding Acks: 0 out of maximum 1,000
     Redelivered Messages: 0
     Unprocessed Messages: 0
          Active Interest: Active using Queue Group c1
Information for Consumer logs > c2 created 2022-11-04T15:36:04Z

Configuration:

        Durable Name: c2
    Delivery Subject: c2.logs
      Deliver Policy: All
 Deliver Queue Group: c2
          Ack Policy: Explicit
            Ack Wait: 30s
       Replay Policy: Instant
     Max Ack Pending: 1,000
        Flow Control: false

Cluster Information:

                Name: nats-cluster
              Leader: n2
             Replica: n3, current, seen 0.27s ago
             Replica: n1, current, seen 0.27s ago

State:

   Last Delivered Message: Consumer sequence: 134,835,662 Stream sequence: 134,849,349 Last delivery: 0.27s ago
     Acknowledgment floor: Consumer sequence: 134,835,662 Stream sequence: 134,849,349 Last Ack: 0.27s ago
         Outstanding Acks: 0 out of maximum 1,000
     Redelivered Messages: 0
     Unprocessed Messages: 0
          Active Interest: Active using Queue Group c2
```

4. `nats stream purge logs; nats stream info logs; nats consumer info logs c1; nats consumer info logs c2;`

```
? Really purge Stream logs Yes
Information for Stream logs created 2022-07-13 20:07:45

             Subjects: logs.>
             Replicas: 3
              Storage: File

Options:

            Retention: Interest
     Acknowledgements: true
       Discard Policy: Old
     Duplicate Window: 2m0s
    Allows Msg Delete: true
         Allows Purge: true
       Allows Rollups: false

Limits:

     Maximum Messages: unlimited
  Maximum Per Subject: unlimited
        Maximum Bytes: 1.0 GiB
          Maximum Age: 5d0h0m0s
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited


Cluster Information:

                 Name: nats-cluster
               Leader: n1
              Replica: n3, current, seen 0.00s ago
              Replica: n2, outdated, seen 0.13s ago, 1 operation behind

State:

             Messages: 0
                Bytes: 0 B
             FirstSeq: 134,857,694 @ 0001-01-01T00:00:00 UTC
              LastSeq: 134,857,693 @ 2022-11-08T08:39:56 UTC
     Active Consumers: 2
Information for Stream logs created 2022-07-13 20:07:45

             Subjects: logs.>
             Replicas: 3
              Storage: File

Options:

            Retention: Interest
     Acknowledgements: true
       Discard Policy: Old
     Duplicate Window: 2m0s
    Allows Msg Delete: true
         Allows Purge: true
       Allows Rollups: false

Limits:

     Maximum Messages: unlimited
  Maximum Per Subject: unlimited
        Maximum Bytes: 1.0 GiB
          Maximum Age: 5d0h0m0s
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited


Cluster Information:

                 Name: nats-cluster
               Leader: n1
              Replica: n3, current, seen 0.27s ago
              Replica: n2, current, seen 0.27s ago

State:

             Messages: 0
                Bytes: 0 B
             FirstSeq: 134,857,695
              LastSeq: 134,857,694 @ 2022-11-08T08:39:56 UTC
     Active Consumers: 2

Information for Consumer logs > c1 created 2022-11-04T14:04:16Z

Configuration:

        Durable Name: c1
    Delivery Subject: c1.logs
      Deliver Policy: All
 Deliver Queue Group: c1
          Ack Policy: Explicit
            Ack Wait: 30s
       Replay Policy: Instant
     Max Ack Pending: 1,000
        Flow Control: false

Cluster Information:

                Name: nats-cluster
              Leader: n1
             Replica: n3, current, seen 0.09s ago
             Replica: n2, current, seen 0.09s ago

State:

   Last Delivered Message: Consumer sequence: 134,836,321 Stream sequence: 134,857,696 Last delivery: 0.10s ago
     Acknowledgment floor: Consumer sequence: 134,836,321 Stream sequence: 134,857,696 Last Ack: 0.10s ago
         Outstanding Acks: 0 out of maximum 1,000
     Redelivered Messages: 0
     Unprocessed Messages: 0
          Active Interest: Active using Queue Group c1
Information for Consumer logs > c2 created 2022-11-04T15:36:04Z

Configuration:

        Durable Name: c2
    Delivery Subject: c2.logs
      Deliver Policy: All
 Deliver Queue Group: c2
          Ack Policy: Explicit
            Ack Wait: 30s
       Replay Policy: Instant
     Max Ack Pending: 1,000
        Flow Control: false

Cluster Information:

                Name: nats-cluster
              Leader: n2
             Replica: n3, current, seen 0.41s ago
             Replica: n1, current, seen 0.40s ago

State:

   Last Delivered Message: Consumer sequence: 134,844,004 Stream sequence: 134,857,696 Last delivery: 0.41s ago
     Acknowledgment floor: Consumer sequence: 134,844,004 Stream sequence: 134,857,696 Last Ack: 0.41s ago
         Outstanding Acks: 0 out of maximum 1,000
     Redelivered Messages: 0
     Unprocessed Messages: 0
          Active Interest: Active using Queue Group c2
```

5. `nats stream info logs; nats consumer info logs c1; nats consumer info logs c2;`

```
Information for Stream logs created 2022-07-13 20:07:45

             Subjects: logs.>
             Replicas: 3
              Storage: File

Options:

            Retention: Interest
     Acknowledgements: true
       Discard Policy: Old
     Duplicate Window: 2m0s
    Allows Msg Delete: true
         Allows Purge: true
       Allows Rollups: false

Limits:

     Maximum Messages: unlimited
  Maximum Per Subject: unlimited
        Maximum Bytes: 1.0 GiB
          Maximum Age: 5d0h0m0s
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited


Cluster Information:

                 Name: nats-cluster
               Leader: n1
              Replica: n3, current, seen 0.29s ago
              Replica: n2, current, seen 0.29s ago

State:

             Messages: 44
                Bytes: 40 KiB
             FirstSeq: 134,857,701 @ 2022-11-08T08:39:59 UTC
              LastSeq: 134,858,552 @ 2022-11-08T08:41:21 UTC
     Deleted Messages: 808
     Active Consumers: 2
   Number of Subjects: 6

Information for Consumer logs > c1 created 2022-11-04T14:04:16Z

Configuration:

        Durable Name: c1
    Delivery Subject: c1.logs
      Deliver Policy: All
 Deliver Queue Group: c1
          Ack Policy: Explicit
            Ack Wait: 30s
       Replay Policy: Instant
     Max Ack Pending: 1,000
        Flow Control: false

Cluster Information:

                Name: nats-cluster
              Leader: n1
             Replica: n3, current, seen 0.61s ago
             Replica: n2, current, seen 0.61s ago

State:

   Last Delivered Message: Consumer sequence: 134,837,177 Stream sequence: 134,858,552 Last delivery: 0.62s ago
     Acknowledgment floor: Consumer sequence: 134,837,177 Stream sequence: 134,858,552 Last Ack: 0.61s ago
         Outstanding Acks: 0 out of maximum 1,000
     Redelivered Messages: 0
     Unprocessed Messages: 0
          Active Interest: Active using Queue Group c1
Information for Consumer logs > c2 created 2022-11-04T15:36:04Z

Configuration:

        Durable Name: c2
    Delivery Subject: c2.logs
      Deliver Policy: All
 Deliver Queue Group: c2
          Ack Policy: Explicit
            Ack Wait: 30s
       Replay Policy: Instant
     Max Ack Pending: 1,000
        Flow Control: false

Cluster Information:

                Name: nats-cluster
              Leader: n2
             Replica: n3, current, seen 0.16s ago
             Replica: n1, current, seen 0.16s ago

State:

   Last Delivered Message: Consumer sequence: 134,844,859 Stream sequence: 134,858,554 Last delivery: 0.16s ago
     Acknowledgment floor: Consumer sequence: 134,844,859 Stream sequence: 134,858,554 Last Ack: 0.16s ago
         Outstanding Acks: 0 out of maximum 1,000
     Redelivered Messages: 0
     Unprocessed Messages: 0
          Active Interest: Active using Queue Group c2
```

From then on messages and deleted messages count on the stream continues to increase. Delete messages count increases faster than messages count.

### PR DESCRIPTION
**Pull request by derekcollison**
Signed-off-by: Derek Collison <derek@nats.io>

Resolves #3612 

/cc @nats-io/core

### CODE REVIEW

File: server/jetstream_cluster_3_test.go [hunk 1]
```diff
@@ -1315,3 +1316,60 @@ func TestJetStreamClusterHAssetsEnforcement(t *testing.T) {
 	})
 	require_Error(t, err, exceededErrs...)
 }
+
+func TestJetStreamClusterInterestStreamConsumer(t *testing.T) {
+	c := createJetStreamClusterExplicit(t, "R5S", 5)
```
Comment (kozlovic) [inline server/jetstream_cluster_3_test.go:1321]: No need to change, but curious if this needs to be a 5 nodes to easily reproduce or it is just a copy paste from another test and this could have been a 3 nodes cluster?

**Review by kozlovic — APPROVED** [review]
LGTM

File: server/jetstream_cluster_3_test.go (hunk 1 above)
Comment (derekcollison) [reply server/jetstream_cluster_3_test.go:1321]: 5 nodes showed it more repeatedly vs 3.
